### ISSUE TITLE
Incorrect order for steps

### ISSUE THREAD

**Issue by billypms** [MicrosoftDocs/ATADocs#100]
The step to start ATA Center service should be after the system profile import
Step 5, a, iii - Start the ATA Center service
** should be moved to before Step 5, c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c282b250-a2a2-a03c-1190-91c36839bf1a
* Version Independent ID: 3fa962d4-5d35-3edb-635d-09e81c5ca378
* Content: [Disaster recovery for Advanced Threat Analytics](https://docs.microsoft.com/en-us/advanced-threat-analytics/disaster-recovery#feedback)
* Content Source: [ATADocs/disaster-recovery.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/disaster-recovery.md)
* Service: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thank you for your feedback. Steps updated to correct order.
