### ISSUE TITLE
gold-ciclet-194322

### ISSUE THREAD

**Issue by Jc692488** [MicrosoftDocs/ATADocs#103]
fix issues please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbd5a7f-77eb-bc4c-d696-e834ac108be0
* Version Independent ID: 164d99ad-3ecc-0031-b722-75533f8348f1
* Content: [Troubleshooting Azure Advanced Threat Protection using the logs](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-using-logs#azure-atp-deployment-logs)
* Content Source: [ATPDocs/troubleshooting-atp-using-logs.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-using-logs.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
Thanks for your feedback. Please let us know what issues you see with the article so that we can review and try to address them.

**Comment by Jc692488** [comment]
I really can’t read this content I don’t know how to identify the issues

**Comment by mlottner** [comment]
Thanks again for taking the time to comment. Can you tell us what about the article is difficult to read or understand? Have you contacted your Microsoft representative to try to resolve your logs issue?

**Comment by bradrush** [comment]
I think these log locations might be out of date as I cannot find anything in most of the suggested places despite ATP being installed and working.
