### ISSUE TITLE
Domain synchronizer candidate for ATP sensors

### ISSUE THREAD

**Issue by idarryl** [MicrosoftDocs/ATADocs#104]
Could clarity be added in the 'Domain synchronizer candidate' section to understand if Azure ATP sensors should be enable as synchronizer candidates in an exclusively ATP sensor environment (i.e. no ATP Standalone sensors)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e1c17a-2f22-6a6f-d5ba-bedda3984aef
* Version Independent ID: 8531caef-8ef2-1f45-6362-0c83bd1de9dc
* Content: [Azure Advanced Threat Protection architecture](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-architecture#azure-atp-sensor-features)
* Content Source: [ATPDocs/atp-architecture.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-architecture.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by Jc692488** [comment]
After issues are identified what next

**Comment by Jc692488** [comment]
Looks like I have 8 issues to fix and I the email address I used to sign in now it says that the email is not Microsoft accounts

**Comment by mlottner** [comment]
Thanks for your valuable feedback. Additional information was added about when and how to enable Azure ATP sensors as domain synchronizer candidates. Let us know if anything is still unclear.
