### ISSUE TITLE
"a static non-routable IP address"sample has been used

### ISSUE THREAD

**Issue by blackfoxsar** [MicrosoftDocs/ATADocs#107]
The Sample is "1.1.1.1/32", but this ip has been used by CloudFlare. it have sensor and it's DNS server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
Thank you for your feedback. The text has been revised to avoid any possible confusion.
