### ISSUE TITLE
Missing Images and Formatting

### ISSUE THREAD

**Issue by bakerds** [MicrosoftDocs/ATADocs#111]
The images are missing, and there is broken formatting in Step 2, section 1c.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28fa6a0b-94b7-d2cd-96fb-1a3f08dab87f
* Version Independent ID: d6ea7d74-4377-63ff-ff41-6a7404297e20
* Content: [Configure Windows Event Forwarding in Advanced Threat Analytics](https://docs.microsoft.com/en-us/advanced-threat-analytics/configure-event-collection)
* Content Source: [ATADocs/configure-event-collection.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/configure-event-collection.md)
* Service: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thanks for your feedback. The missing images and broken formatting have been fixed.
