### ISSUE TITLE
Event Viewer Subscriptions on Server Core?

### ISSUE THREAD

**Issue by bakerds** [MicrosoftDocs/ATADocs#112]
Can you update this document to include instructions for Server Core? Subscriptions is not accessible from Event Viewer connected to a remote computer, and Event Viewer is not available on Server Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28fa6a0b-94b7-d2cd-96fb-1a3f08dab87f
* Version Independent ID: d6ea7d74-4377-63ff-ff41-6a7404297e20
* Content: [Configure Windows Event Forwarding in Advanced Threat Analytics](https://docs.microsoft.com/en-us/advanced-threat-analytics/configure-event-collection)
* Content Source: [ATADocs/configure-event-collection.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/configure-event-collection.md)
* Service: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thank you for your feedback! I added an update with a Server Core note to assist.
