### ISSUE TITLE
Wrong information?

### ISSUE THREAD

**Issue by artoroth** [MicrosoftDocs/ATADocs#114]
Should registry value DefaultConnectionSetting be DefaultConnectionSettings ? Like HKCU\Software\Microsoft\Windows\CurrentVersion\InternetSetting\Connections\DefaultConnectionSettings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7823584-21cb-81b3-7e2b-8fd521bc3ae1
* Version Independent ID: f312a146-a76c-9adb-0e36-f0f98d91051a
* Content: [Configure your proxy or firewall to enable Azure ATP communication with the sensor](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/configure-proxy)
* Content Source: [ATPDocs/configure-proxy.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-proxy.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thanks for your feedback. Yes, the correct registry value is DefaultConnectionSettings. The page has been updated with the correction.
