### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by artoroth** [MicrosoftDocs/ATADocs#120]
Item 6. Go to Account Logon , double click on Audit Security Group Management and select Configure the following audit events for both success and failure events.
Should be:
Go to Account Management , double click on Audit Security Group Management and select Configure the following audit events for both success and failure events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7793d9-995f-fae7-8422-304e5738201c
* Version Independent ID: 0382809d-cb98-8ac0-421d-7e526a596f17
* Content: [Azure Advanced Threat Protection Advanced Audit Policy check](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-advanced-audit-policy)
* Content Source: [ATPDocs/atp-advanced-audit-policy.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-advanced-audit-policy.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
Thanks for your feedback! Updated with your correction.
