### ISSUE TITLE
PDF not working

### ISSUE THREAD

**Issue by arnaudinsinger** [MicrosoftDocs/ATADocs#130]
https://docs.microsoft.com/en-us/advanced-threat-analytics/opbuildpdf/TOC.pdf?branch=live
...has a Download PDF option, that doesn't open.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55eafa55-876f-04e8-d0ce-6deff81e8f40
* Version Independent ID: 131ad34f-9004-761c-87aa-1563841616db
* Content: [Planning your Advanced Threat Analytics deployment](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-capacity-planning)
* Content Source: [ATADocs/ata-capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-capacity-planning.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thanks for your feedback. I'm investigating what is causing the issue, and will respond (hopefully with a fix)ASAP.

**Comment by msmbaldwin** [comment]
This has been fixed; see https://opdhsblobprod02.blob.core.windows.net/contents/e242e04c74e94335b608dba5a998281a/0bebe7b431e4f01f317c749ca7e310c6?sv=2015-04-05&sr=b&sig=fUFeL1izXfWkDQKgjyLV3Nt8XFL9eVUHpiHT0TslQfE%3D&st=2018-10-11T16%3A58%3A51Z&se=2018-10-12T17%3A08%3A51Z&sp=r.  Thanks for letting us know!
