### ISSUE TITLE
Offline installsource is wrong

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/ATADocs#131]
@mbrogies commented on [Mon Oct 08 2018](https://github.com/MicrosoftDocs/ATADocs.de-de/issues/23)

The offline install source of .net4.7 is wrong. 
It's referencing to .net4.6.1

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4856b2df-3ad3-526f-b7cf-a24a44340744
* Version Independent ID: fd11c910-7991-cdf1-8ca7-7e7d61ec19bf
* Content: [Automatisches Installieren von Azure Advanced Threat Protection](https://docs.microsoft.com/de-de/azure-advanced-threat-protection/atp-silent-installation)
* Content Source: [ATPDocs/atp-silent-installation.md](https://github.com/MicrosoftDocs/ATADocs.de-de/blob/live/ATPDocs/atp-silent-installation.md)
* Service: **azure-advanced-threat-protection**
* Product: ****
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by CeciAc** [comment]
Hello, @mbrogies,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/ATADocs/issues/131.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by mlottner** [comment]
Hello @mbrogies
The article was updated with the correct link based on your feedback.
Thank you! We appreciate your contribution.
