### ISSUE TITLE
Missing letter

### ISSUE THREAD

**Issue by 1800Zeta** [MicrosoftDocs/ATADocs#135]
In the paragraph:
Optional: When deploying the standalone sensor, it is necessary to forward Windows events 4776, 4732, 4733, 4728, 4729, 4756, 4757, and 7045 to zure ATP to further enhance Azure ATP Pass-the-Hash, Brute Force, Modification to sensitive groups, Honey Tokens detections, and malicious service creation. Azure ATP sensor receives these events automatically. In Azure ATP standalone sensor, these events can be received from your SIEM or by setting Windows Event Forwarding from your domain controller. Events collected provide Azure ATP with additional information that is not available via the domain controller network traffic.

After 7045 you're missing the A in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
Thanks for your feedback. Great catch! Fix being published now.
