### ISSUE TITLE
Additional instruction request

### ISSUE THREAD

**Issue by 1800Zeta** [MicrosoftDocs/ATADocs#136]
Please can you add Command Line/PowerShell commands for resolving the VMWare issue? 

Set the following settings to 0 or Disabled in the virtual machine's NIC configuration: TsoEnable, LargeSendOffload, TSO Offload, Giant TSO Offload. 

I need to do the TSO Offload (as per the note) on Windows Server Core in particular

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a56ac5-d132-1427-4c55-12921ec978c7
* Version Independent ID: aad125e7-7fa3-5fec-e025-2da79e11f44a
* Content: [Troubleshooting Azure ATP known issues](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues)
* Content Source: [ATPDocs/troubleshooting-atp-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
Thanks for taking the time to comment.  
There is more than one way to resolve the issue and it is outside the scope of Azure ATP documentation. 
Some suggestions below:

The following example of PowerShell command disables TCP/IPv4 checksum offload on all network adapters, then restarts them:
`Disable-NetAdapterChecksumOffload -Name "*" - TcpIPv4
`

Possible to use this command:` Get-NetOffloadGlobalSetting` – TaskOffload Disable
TaskOffload: Specifies the global TCP/IP task offload settings on the computer. Task offload settings include IP checksum offload, Internet Protocol security (IPsec) task offload, and Large Send Offload. These features reduce the overhead of per-packet processing by distributing packet processing tasks, such as checksum calculation, to a network adapter. 

Disables all LSO properties, such as LSOv4 and LSOv6, of the network adapter.
`Disable-NetAdapterLso -Name "MyAdapter" -IPv4
`
