### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by toanyonebutyou** [MicrosoftDocs/ATADocs#145]
How does ATA know where to send this notification email to? Is this a configurable field?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d201f184-989f-9f14-3463-7b054290f895
* Version Independent ID: 48d17f07-1d6b-18b6-f664-3677e17e1089
* Content: [Setting email notification settings in Advanced Threat Analytics](https://docs.microsoft.com/en-us/advanced-threat-analytics/setting-syslog-email-server-settings)
* Content Source: [ATADocs/setting-syslog-email-server-settings.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/setting-syslog-email-server-settings.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thanks for your feedback @toanyonebutyou   
This article explains how to set your syslog email server settings. See https://docs.microsoft.com/advanced-threat-analytics/setting-ata-alerts for configuring your notification email addresses. Yes, the field is entirely configurable.
