### ISSUE TITLE
Schedule the time for daily reports

### ISSUE THREAD

**Issue by cis4cookie** [MicrosoftDocs/ATADocs#146]
The daily reports are always sent shortly after midnight, UTC - that's not great for our timezone (which changes based on daylight savings). Can this be configurable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc9f5742-faf6-f294-440d-d038268a52c8
* Version Independent ID: ed4a451b-733e-13ba-b21a-3962cd4b8ab8
* Content: [Working with ATA Reports](https://docs.microsoft.com/en-us/advanced-threat-analytics/reports)
* Content Source: [ATADocs/reports.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/reports.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thanks for your feedback and suggestion @cis4cookie 
At present, the time at which daily reports are issued and sent is not customizable.
