### ISSUE TITLE
How to manually create a backup on demand?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/ATADocs#149]
It's great that ATA backs up it's config every 4 hours, but let's say I've just made a change and want to manually backup the config.  How can I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46b4018-4e09-73a2-e729-dcf18a504fc3
* Version Independent ID: a3e8bb31-3fa3-99ee-5920-2ae870257061
* Content: [Export and Import Advanced Threat Analytics Configuration](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-configuration-file)
* Content Source: [ATADocs/ata-configuration-file.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-configuration-file.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by NeighborGeek** [comment]
Since the documentation includes the command line required to import the database using the mongodb tools, I would suggest that it should include a corresponding command line to manually export the db using the same tools.

**Comment by mlottner** [comment]
@NeighborGeek 
For version 1.9 (only) you can use: 
mongoexport.exe -d ATA -c SystemProfile -o "C:\Backup\SystemProfile_ManualBackup.json" -q "{ '_t' : { '$in' ['CenterSystemProfile', 'GatewaySystemProfile', 'LicenseSystemProfile'] } }"  

As the export method changes  (the import does not), this is version specific.

**Comment by jonmpayne** [comment]
@NeighborGeek @
The JSON document in the query option ("-q"), seems to be missing a colon (":"). 

Try the following: 

`mongoexport.exe -d ATA -c SystemProfile -o "..\..\Backup\SystemProfile_ManualBackup.json" -q "{'_t' : {'$in' : ['CenterSystemProfile', 'GatewaySystemProfile', 'LicenseSystemProfile'] } }"`
