### ISSUE TITLE
Unable to download report from ATA

### ISSUE THREAD

**Issue by Zanber82** [MicrosoftDocs/ATADocs#152]
I have a ATA 1.9.7312.32791. When ever i go to reports and try to download, it would not download with a error. please help. I am very sure it is not the browser issue and i have reinstall ATA a few times, and even create a new OS from start and reinstall it. Seems like it does not work. 

![image](https://user-images.githubusercontent.com/45255869/48889794-f68dbf80-ee71-11e8-8d87-bb57c0574ba5.png)

**Comment by mlottner** [comment]
Thanks for your comment. 
From the screen you sent, you are not running the latest version of ATA (ATA 1.9 Update 1). 
[Download ATA v1.9, update 1 here](https://www.microsoft.com/download/details.aspx?id=56725)

If your report download issue is not resolved with the update, reach out to support to help you troubleshoot this specific issue.

**Comment by mlottner** [comment]
@Zanber82 [Open a support case](https://support.microsoft.com/gp/contactus81?forceorigin=esmc&Audience=Commercial)

**Comment by Zanber82** [comment]
After much struggling, no money to log a case, below is the answer

Turn off IE Enhance Security Configuration.

![image](https://user-images.githubusercontent.com/45255869/49193726-26c9e680-f3bb-11e8-9c12-00c5d5de968e.png)
