### ISSUE TITLE
Monitored user activities: AD security principal operations

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/ATADocs#158]
I just wonder, for these, i notice it says it is changed, but it did not say who change it. Is this something can be done in Azure ATP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef45b794-07fd-7e28-c2f9-07a6e8d1a9db
* Version Independent ID: 9959c52f-8fd9-b34d-1d1e-86079cb2ea4b
* Content: [Azure ATP monitored domain activities](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/monitored-activities)
* Content Source: [ATPDocs/monitored-activities.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/monitored-activities.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by limjianan** [comment]
I think this is product issue rather than content. close this.

**Comment by mlottner** [comment]
@limjianan Thanks for your feedback. This page is the monitored activity list. Meaning the activities that are collected and analyzed by Azure ATP. For information about each entity when Azure ATP is deployed, use the [Azure ATP entity profile](https://docs.microsoft.com/azure-advanced-threat-protection/entity-profiles) or [Azure ATP security alerts](https://docs.microsoft.com/azure-advanced-threat-protection/working-with-suspicious-activities) for a deep dive into specific information about which users or actors made changes and where.
