### ISSUE TITLE
Step 5 screenshot does not match text

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#166]
The text states that the screen shot should show a standalone install, but the screen shot shows the installation on a domain controller. Please make the text and image consistent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee91dca-7081-4eaa-8728-7674d7cd4870
* Version Independent ID: 2eae6069-f58f-ad69-3511-1a4e204db31e
* Content: [Install Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step4)
* Content Source: [ATPDocs/install-atp-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step4.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@DeanGross Thanks for taking the time to give us feedback. Text was updated in the latest doc publish to match screens.
