### ISSUE TITLE
Wrong syntax for ATP sensor install

### ISSUE THREAD

**Issue by nadrii** [MicrosoftDocs/ATADocs#167]
The syntax for the install of the azure atp sensor has an inconsistency on the AccessKey param. In the syntax box is shows as prefaced with a slash but in the installation params section it doesn't. The install fails with an error "Option /AccessKey is unknown" if you include the slash. 

This was mentioned in [issue 98](https://github.com/MicrosoftDocs/ATADocs/issues/98) but wasn't corrected completely.

**Comment by mlottner** [comment]
@nadrii Thanks for your feedback. This install syntax was fixed in the latest publishing build. Appreciate you taking the time to contribute to the Azure ATP community.
