### ISSUE TITLE
Licensing Requirements

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/ATADocs#170]
What user accounts specifically need to be licensed for this feature? Admins? Users? Both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73885e78-0c05-9359-b85d-e76e12f02662
* Version Independent ID: be8e600a-3e61-ce2b-1cb7-09a40ef66533
* Content: [Azure Advanced Threat Protection frequently asked questions](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-technical-faq)
* Content Source: [ATPDocs/atp-technical-faq.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-technical-faq.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@pyoungberg Thanks for your question. Can you clarify which feature in the article you linked is the subject of your question?

**Comment by DeanGross** [comment]
Why was the question about licensing closed with out an answer. I have the same question.

**Comment by JeremyTBradshaw** [comment]
How can we reopen this issue?  I have a similar question - if Azure ATP is concerned with on-premises AD, what is the point of requiring "all Azure AD users" to be licensed?  It seems strange and random.
