### ISSUE TITLE
How to Verify the machine has connectivity to the relevant Azure ATP cloud service endpoint(s)

### ISSUE THREAD

**Issue by cjwest77** [MicrosoftDocs/ATADocs#172]
One thing my might be helpful would be to give some options on how to verify connectivity to the ATP Cloud service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee91dca-7081-4eaa-8728-7674d7cd4870
* Version Independent ID: 2eae6069-f58f-ad69-3511-1a4e204db31e
* Content: [Install Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step4)
* Content Source: [ATPDocs/install-atp-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step4.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@cjwest77 Thanks for your feedback. I've added connectivity verification information to the [next article in the series](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step5#validate-installations) and really appreciate you taking the time to contribute to the Azure ATP community!
