### ISSUE TITLE
Please add that this is only for "standard Active Directory"

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/ATADocs#178]
Hi,
We are a pure Azure Active Directory shop and when I went through the motions to set this up, one of the first steps was indeed to download the sensor to one of our Domain controllers, which we don't have since we don't have Domain Controllers. 
Please add some clarification that this is not for Azure Active Directory. And maybe you can then also point users of Azure Active Directory to ATP for those setups, if they exist?
Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee91dca-7081-4eaa-8728-7674d7cd4870
* Version Independent ID: 2eae6069-f58f-ad69-3511-1a4e204db31e
* Content: [Install Azure ATP sensor quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step4)
* Content Source: [ATPDocs/install-atp-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step4.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@blouwagie Thanks for your feedback. 
I had thought that the [What is Azure ATP](https://docs.microsoft.com/azure-advanced-threat-protection/what-is-atp) and [Azure ATP prerequisites](https://docs.microsoft.com/azure-advanced-threat-protection/atp-prerequisites) pages used clear enough terms to specify that to use Azure ATP, an **on-premises** AD user account was required. 
I'll take another look at adding language to help clarify exactly which environments the service is and is not intended for.

**Comment by blouwagie** [comment]
Thank you.
