### ISSUE TITLE
Please clarify how to use as a Pure Azure AD customer

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/ATADocs#179]
Hi,
The path/prerequisites don't seem to explain how a customer that has implemented pure Azure AD, with Azure AD joined systems could possibly implement Azure ATP. It seems like the pre-requisites should mention that this only applies for on-premise (or traditional) Windows domains. I know that one can conclude that after reading all content carefully but why lead us down a path that is in the end invalid.
Also: What if we have a radius server that is connected to Azure AD, what document do we need to consult? How can we possible set up Azure ATP. Did Microsoft built ATP sensors into Azure AD?
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@blouwagie Thanks for taking the time to give us your feedback. 
I've now updated both of the pages you commented on with additional information to try to make it more clear that the Azure ATP service is directed at organizations with on-premesis Active Directory, and organizations looking to protect an environment made up of only AAD users, should see [AAD Identity Protection](https://docs.microsoft.com/azure/active-directory/identity-protection/overview]. Let me know if you feel the distinction is now more clear, and you know which service to use to protect your environment scenario.
