### ISSUE TITLE
server 2019

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/ATADocs#181]
After KB4487044 Windows Server 2019 should be supported. isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@grex86 Thanks for your question. 
At present, Windows Server 2019 (even with KB4487044) remains without support. As soon as that changes, I'll update the prerequisites page with the revised support specifics and the updates required.

**Comment by mlottner** [comment]
@grex86 v2.71 officially added support for Windows Server 2019, with an added requirement for installation of [KB4487044](https://support.microsoft.com/en-us/help/4487044/windows-10-update-kb4487044). See the sensor updates on this page for more details. 
Thanks for taking the time to contribute to the Azure ATP docs community.
