### ISSUE TITLE
If you use Azure AD Connect ... Beware

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/ATADocs#182]
If your using Azure AD Connect, make sure you add the MSOL_XXXYYY account to this policy else you will not be able to do password reset or self service password resets.  Also just be very very wary of this, once we turned it on, a lot of poorly developed apps broke, which required the service account being added to this policy.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92c4e348-5e88-e1d9-6379-80582041a35a
* Version Independent ID: 3a9bc6be-b1ce-2d08-d8b4-a04c75f9abc4
* Content: [Configure SAM-R to enable lateral movement path detection in Azure ATP](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step8-samr#feedback)
* Content Source: [ATPDocs/install-atp-step8-samr.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step8-samr.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@SquirrelAssassin Thanks for taking the time to comment. Unfortunately, we can't document every possible "use with" scenario, but we've added additional clarity that it needs to be set on all computers, and an additional reminder to setup in a lab environment before deploying to production. 
Appreciate your contribution to our community.

**Comment by mlottner** [comment]
#please-close

**Comment by SquirrelAssassin** [comment]
Recommend showing your test suite that you did so we can do our own against it.  AD connect population ...  95%.  I would make sure the foundational items work before publishing breaking changes.

**Comment by mlottner** [comment]
@SquirrelAssassin Not sure I understand. Did you mean to ask how we suggest testing? 
"Do this by first enabling and then verifying compatibility of proposed changes in audit mode before making changes to your production environment." Are you unable to make use of **audit mode**? 
Is that wasn't the problem or suggestion, let us know so we can try to improve. Thanks again.

**Comment by SquirrelAssassin** [comment]
No show us your pester testing or devops testing line of products you tested against.

**Comment by mlottner** [comment]
@SquirrelAssassin Based on your feedback, our product team is considering adding AD Connect to the list of Known Issues. In the meantime, please do make sure to test in **audit mode** before making any changes to your production environment. Send your product feedback to aatpfeedback@microsoft.com. Thanks again.

**Comment by mlottner** [comment]
#please-close
