### ISSUE TITLE
Please support GMSA or "run as service" identities, so passwords are not needed...

### ISSUE THREAD

**Issue by mschrisran** [MicrosoftDocs/ATADocs#194]
Requiring a username/password and service account that isn't a GMSA is very old school.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed304132-bdfe-bea6-e9f8-44f45d1651c2
* Version Independent ID: f5bdd742-716b-de60-1f73-3555c460f03c
* Content: [Connect Azure ATP to Active Directory quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step2)
* Content Source: [ATPDocs/install-atp-step2.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step2.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@mschrisran Thanks for your docs comment. Please make sure to reach out to the product feedback group with your suggestion at aatpfeedback@microsoft.com

**Comment by mlottner** [comment]
#please-close
