### ISSUE TITLE
Provide a DSC and/or Powershell automated installation for this.

### ISSUE THREAD

**Issue by mschrisran** [MicrosoftDocs/ATADocs#195]
In environments with many, many DC's, it's very useful to be able to install via automation / unattended. Please add support for DSC or Powershell based automation...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee91dca-7081-4eaa-8728-7674d7cd4870
* Version Independent ID: 2eae6069-f58f-ad69-3511-1a4e204db31e
* Content: [Install Azure ATP sensor quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step4)
* Content Source: [ATPDocs/install-atp-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step4.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@mschrisran Thanks for your docs comment. Please make sure to reach out to the product feedback group with your suggestion at aatpfeedback@microsoft.com

**Comment by mlottner** [comment]
#please-close
