### ISSUE TITLE
Missing graphic

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/ATADocs#196]
![Sample capacity planning tool](media/capacity tool.png)

I assume there was supposed to be a graphic embedded in the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55eafa55-876f-04e8-d0ce-6deff81e8f40
* Version Independent ID: 131ad34f-9004-761c-87aa-1563841616db
* Content: [Planning your Advanced Threat Analytics deployment](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-capacity-planning)
* Content Source: [ATADocs/ata-capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-capacity-planning.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
@vboyev-MSFT Thanks for your review! Indeed, the graphic someone how went missing and has now been restored. Thanks for contributing to our community.

**Comment by mlottner** [comment]
#please-close
