### ISSUE TITLE
Support for Windows Server 2019 not mentioned

### ISSUE THREAD

**Issue by piazzaandrea** [MicrosoftDocs/ATADocs#201]
Since release of 1.9.2, Windows Server 2019 should be supported on ATA Center and Gateways. This is not mentioned in the prerequisites page.

**Comment by mlottner** [comment]
@piazzaandrea Thanks for taking the time to suggest an update to the prerequisites page. We've added the update to Windows Server 2019. 
Appreciate your contribution to the community!

**Comment by mlottner** [comment]
#please-close
