### ISSUE TITLE
Configuration recommendations - which Windowa Firewall rules should be enabled?

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/ATADocs#205]
please be specific
and please fix the doc:
"Port 135" should be changed to "TCP port 135"
"Port 137" should be changed to "UDP port 137"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fcd13c-b9a0-bb56-3bcc-c9981530aaf5
* Version Independent ID: a36ab1d9-02c8-6339-6237-99679b250f75
* Content: [Azure Advanced Threat Protection Network Name Resolution](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-nnr-policy#feedback)
* Content Source: [ATPDocs/atp-nnr-policy.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-nnr-policy.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@rafalfitt Thanks for your comment. I had thought the table above was specific enough, but I'll modify the bullet mentions to be more specific. 
Appreciate you taking the time to contribute to the Azure ATP community.

**Comment by mlottner** [comment]
#please-close

**Comment by rafalfitt** [comment]
another place to fix:
"Check that Port 137 is open for inbound communication from Azure ATP sensors, on all computers in the environment." in the Health issue list in the AATP web console

**Comment by rafalfitt** [comment]
and even worse news:
it is not enough just to open UDP port 137, you need to (re-)enable "Enable NetBIOS over TCP/IP" in IPv4 configuration for internal network interfaces :-( This is "no go" for me

**Comment by mlottner** [comment]
@rafalfitt you wrote: >another place to fix "Check that Port 137 is open for inbound communication from Azure ATP sensors, on all computers in the environment." in the Health issue list in the AATP web console -not clear if you were suggesting to revise the UI text displayed in the Azure ATP web console or you were referring to another location in docs that you felt UDP needed to be added? Please advise. 

With regards to your feedback about the "need to re-enabling NetBIOS over TCP/IP", product feature comments and suggestions can be sent directly to the [Azure ATP product team](https://microsoftsecurity.uservoice.com/forums/905791-azure-advanced-threat-protection-ata-in-the-cloud). Thanks again for contributing to our docs community!

**Comment by rafalfitt** [comment]
yes, the UI text displayed in the Azure ATP web console could mention the protocol, not only the port number.
