### ISSUE TITLE
npcap installer options should be changed

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/ATADocs#207]
According to https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-installation-options  the installer options should be
/loopback_support=no /winpcap_mode=no

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a56ac5-d132-1427-4c55-12921ec978c7
* Version Independent ID: aad125e7-7fa3-5fec-e025-2da79e11f44a
* Content: [Troubleshooting Azure ATP known issues](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues#feedback)
* Content Source: [ATPDocs/troubleshooting-atp-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@rafalfitt Thanks for your comment. I'll research with our engineering team and update the article as needed. Appreciate you taking the time to contribute to our community!

**Comment by mlottner** [comment]
Hi @rafalfitt, after reviewing the npcap installation page you referenced, the installer option defaults are **no**, but can be changed as needed. [The following options are presented as checkboxes in the installer, but can be set or locked via command-line flags. Unless otherwise noted, the default for these options is no](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-installation-options).
Thanks again for contributing!

**Comment by mlottner** [comment]
#please-close

**Comment by rafalfitt** [comment]
I know what the defaults are, but:
1) they can change without notice, so it is better to specify it explicitly
2) please note the difference between (my suggestion) "/loopback_support=no /winpcap_mode=no" and (the current documentation) "loopback_support=no & winpcap_mode=yes"

#please-fix

Thanks again for reading-carefully-before-writing!

**Comment by mlottner** [comment]
@rafalfitt As confirmed with engineering, Azure ATP requirements as written are current and the need for wincap_mode=yes is explicitly specified. 
#please-close
