### ISSUE TITLE
Recommendations for HoneyToken user

### ISSUE THREAD

**Issue by KjetilEVRY** [MicrosoftDocs/ATADocs#209]
Please give recommendations for for the HT user. The documenation is lacking information about this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f77d1a5-6730-91f4-35c3-d9b12bbf67bb
* Version Independent ID: 4c98c142-02f1-bd74-f75e-75e5a14c0e07
* Content: [Azure Advanced Threat Protection configure detection exclusions and honeytoken accounts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step7#feedback)
* Content Source: [ATPDocs/install-atp-step7.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step7.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@KjetilEVRY Appreciate your feedback. What type of honeytoken recommendations would you like or expect to see? Best practices, configuration suggestions? Something else entirely? Let us know how we can help!

**Comment by KjetilEVRY** [comment]
Yes, some best practices, maybe an example or two. I think that the name and description might be important for example. And of course, that it should be in a disabled state.

**Comment by mlottner** [comment]
@KjetilEVRY Thanks for the feedback. I'll work with the product team to create some best practice examples and update the page.

**Comment by mlottner** [comment]
#please-close

**Comment by bartlettdn** [comment]
This document still need recommendations. There is minimal guidance on how to set this up.
