### ISSUE TITLE
Tip for "All domain controllers are unreachable by a sensor"

### ISSUE THREAD

**Issue by KjetilEVRY** [MicrosoftDocs/ATADocs#210]
Make sure you have defined credentials for the forest under Directory Services in Settings. (I forgot to enter a Service account, and the install package includes all the service accounts for all forests). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10026f2d-c134-2c37-237d-98387b11a146
* Version Independent ID: f11aee98-6da1-2a4e-c2fd-4b0539023657
* Content: [Understanding Azure ATP monitoring alerts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/monitoring-alerts)
* Content Source: [ATPDocs/monitoring-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/monitoring-alerts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@KjetilEVRY Thanks so much for your submission. 
I've updated the page with your suggested fix. Appreciate you taking the time to contribute to our docs community!

**Comment by mlottner** [comment]
#please-close
