### ISSUE TITLE
The "Before you Start" Section has incorrect licensing info on it

### ISSUE THREAD

**Issue by WorldMir** [MicrosoftDocs/ATADocs#213]
The top bullet point "Acquire a license for Enterprise Mobility + Security 5 (EMS E5) directly via the Microsoft 365 portal or through the Cloud Solution Partner (CSP) licensing model." is not factually correct. 

Azure ATP may be procured as a standalone product by a customer. EM+S E5 is not required. However, if a customer owns EM+S E5, then yes, they will also own Azure ATP as well. Same thing as Microsoft 365 E5 -- if you own that license, then you also already own Azure ATP (because M365 E5 includes the EM+S E5 suite). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites#feedback)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@WorldMir Thanks for your feedback. I'll update the article to make the licensing more clear. Appreciate you taking the time to contribute to the docs community.

**Comment by mlottner** [comment]
#please-close
