### ISSUE TITLE
Ports in use?

### ISSUE THREAD

**Issue by JamesFKoenig** [MicrosoftDocs/ATADocs#215]
Great article, it would be nice to see what ports need to be open by ATA when using the gateway agent.  Tyipcally this would be in the architecture documenation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aef862a-ca68-b031-0d7e-f34ba1e05600
* Version Independent ID: 687b3e16-69ec-a0af-7ce8-db750bb4f1da
* Content: [Advanced Threat Analytics architecture](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-architecture#feedback)
* Content Source: [ATADocs/ata-architecture.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-architecture.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@JamesFKoenig Thanks for the time to give us feedback. Typically, we list ports in the prerequisites and leave specific technical details out of the high level architecture articles. For Advanced Threat Analytics, port details are provided in the [prerequisites](https://docs.microsoft.com/advanced-threat-analytics/ata-prerequisites#ports) like in other services. Would you also want to see a reference to port information in the architecture, or just a link letting you know where to find the information?

**Comment by mlottner** [comment]
#please-close
