### ISSUE TITLE
Antivirus Exclusions

### ISSUE THREAD

**Issue by drewPrince** [MicrosoftDocs/ATADocs#218]
Do the virus exclusions for the ATA Center server apply to the Gateway and Lightweight Gateway?  Exact same? Or not required at all?  (I know mongo isn't on gateway...)

This is the page I'm referring to where the exceptions are noted
https://docs.microsoft.com/en-us/advanced-threat-analytics/install-ata-step1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8be1e66-483b-d4d0-855c-defbbbb38a83
* Version Independent ID: 1671b6f3-5371-00e4-b05f-0d725c1c48a8
* Content: [Install Advanced Threat Analytics - Step 4](https://docs.microsoft.com/en-us/advanced-threat-analytics/install-ata-step4#feedback)
* Content Source: [ATADocs/install-ata-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/install-ata-step4.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
@drewPrince Thanks for your question. These exclusions are for the Center component only.

**Comment by mlottner** [comment]
#please-close
