### ISSUE TITLE
Alert maximum retention period

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/ATADocs#219]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/ATADocs.ja-jp/issues/23
The user is making a suggestion on the original documentation

@kakojima commented 10 hours ago
Please list the maximum retention period for alerts.
I checked with the development people as well, and it was 10 months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518df292-7c68-eafb-c968-d7df3c004b6f
* Version Independent ID: 8a3bd941-a035-a667-705a-3bf593c16536
* Content: [Working with security alerts in Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/working-with-suspicious-activities#review-security-alerts-on-the-attack-timeline-)
* Content Source: [ATPDocs/working-with-suspicious-activities.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/working-with-suspicious-activities.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@CeciAc Thanks for the translation. Actually, Azure ATP doesn't delete alerts until the customer closes them or the entire instance is deleted. Unclear exactly what the user would like changed.

**Comment by mlottner** [comment]
#please-close
