### ISSUE TITLE
Breaks end-user RDP-sessions.

### ISSUE THREAD

**Issue by mmaraa** [MicrosoftDocs/ATADocs#221]
New Issue opening based on this: https://github.com/MicrosoftDocs/ATADocs/issues/92

This is required for Server 2016 and Windows 10 1607 or above and operating systems below patched with MSRC 31343 and MSRC 34200. This is not affecting to the policies which are not patched and are below mentioned that operating systems versions.

If you run this policy to every machine and operating systems, which are patched and are prior Windows Server 2016 or Windows 10 1607 it will break regular user RDP-connections. You should add Authenticated Users also to restricted SAMRPC readers to avoid breaking current environments or use one reg fix.

**Comment by mlottner** [comment]
@mmaraa Thanks for taking the time to give us your feedback. 
We've always noted that all changes to settings should be tested in audit mode prior to putting these types of changes into production. To avoid any future confusion, I've moved the note to the top of the page so it will hopefully be more clear.

**Comment by mlottner** [comment]
#please-close
