### ISSUE TITLE
Additional info on configuring recommended settings.

### ISSUE THREAD

**Issue by ivandretvic** [MicrosoftDocs/ATADocs#222]
Can we get clarity on how we are expected to configure additional auditing?
'To enable NTLM auditing, turn on Windows Event 8004'
There are a number of external articles but nothing official from Microsoft, that doesnt involve an unsupported OS, or uses Registry settings as opposed to a Domain Controller Group Policy setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca3290d-5627-1038-af60-32571c8061ac
* Version Independent ID: a8120377-18c6-b2ca-6cfe-168f2cbadcea
* Content: [Azure ATP compromised credentials phase security alerts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-compromised-credentials-alerts#feedback)
* Content Source: [ATPDocs/atp-compromised-credentials-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-compromised-credentials-alerts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@ivandretvic Thanks for asking great questions. I'll modify the article to try to provide more clarity. In the meantime, after discussing the issue with our security research team, they suggested using the following guidance. Let me know if this helps or you need more information: [Enable 8004 events](https://blogs.technet.microsoft.com/askds/2009/10/08/ntlm-blocking-and-you-application-analysis-and-auditing-methodologies-in-windows-7/)

**Comment by ivandretvic** [comment]
That's great. Look forward to reading the official article.
Is ghouls be noted that the data may not be compete in Los and may need to be coupled with other log data like firewall or network data.

Ivan Dretvic
________________________________

**Comment by mlottner** [comment]
#please-close
