### ISSUE TITLE
Azure ATP user based or tenant based license

### ISSUE THREAD

**Issue by BharathiAN** [MicrosoftDocs/ATADocs#223]
HI,

To use Azure ATP, all of the users monitored should have E5 or one E5 license is required or admins require E5 license in the tenant.
Pl clarify.
Thanks

**Comment by mlottner** [comment]
@BharathiAN Thanks for your question and contribution to our Azure ATP community!
To learn more about licensing requirements for Azure ATP and E5, see [How to buy](https://www.microsoft.com/en-us/licensing/product-licensing/microsoft-365-enterprise). Let us know if you need additional information.

**Comment by mlottner** [comment]
#please-close

**Comment by BharathiAN** [comment]
@mlottner - my query is how many E5 licenses required for azure atp, for all users or one E5 license is enough ?. It is not mentioned in the article which you referred. Thanks

**Comment by mlottner** [comment]
@BharathiAN 
"Microsoft 365 Office 365 products are available as user subscription licenses (USLs) and are licensed on a **per-user** basis, where **each user** that accesses a Microsoft 365 subscription must have a USL. There are four types of USLs: Full USL, From SA USL, Add-on USL, and Step-up USL." You can read the full licensing requirements on the **How to buy** tab of the [Microsoft 365 page](https://www.microsoft.com/en-us/licensing/product-licensing/microsoft-365-enterprise). If you are asking if only the ATP administrator needs a license, or all of the active users in the tenant, the answer is all of the active users in the tenant. Let me know if this answers your question.

**Comment by BharathiAN** [comment]
Thanks Lottner.

Regards,

Bharathi
