### ISSUE TITLE
Missing RSS Feed

### ISSUE THREAD

**Issue by jwindmiller** [MicrosoftDocs/ATADocs#231]
Azure ATP page needs to have an RSS feed like the Azure AD, MCAS and Intune pages have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e190d2eb-0b65-f6f5-a4a8-71a52b3bac65
* Version Independent ID: ccf16734-ef56-8f5f-e2c7-654b63a1da81
* Content: [What's new in Azure Advanced Threat Protection (Azure ATP)](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-whats-new#feedback)
* Content Source: [ATPDocs/atp-whats-new.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-whats-new.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@jwindmiller Thanks for taking the time to leave feedback! I've added the RSS feed to the top of What's new page and it will appear shortly. Let me know if there are other ways you think we can improve.

**Comment by mlottner** [comment]
#please-close
