### ISSUE TITLE
Time-based group memberships not updating in ATA

### ISSUE THREAD

**Issue by sneakernuts** [MicrosoftDocs/ATADocs#232]
We noticed updates to time-based group memberships do not show up in ATA. Adding users to the group logs an entry in ATA, but the automatic removal due to the set expiry never shows up properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889e3da9-98f3-206b-4594-4eebb32822fd
* Version Independent ID: 12deccbc-3310-6c44-4299-f20ca06fbc28
* Content: [Advanced Threat Analytics update to 1.9.2 migration guide](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-update-1.9.2-migration-guide#feedback)
* Content Source: [ATADocs/ata-update-1.9.2-migration-guide.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-update-1.9.2-migration-guide.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@sneakernuts Thanks for taking the time to give us feedback. Rather than a documentation comment,  issues related to product functionality should be directed to the ATA product team at ATAEval@microsoft.com. Appreciate your contribution to our community.

**Comment by mlottner** [comment]
#please-close
