### ISSUE TITLE
Issue with the Microsoft ATA temp logs

### ISSUE THREAD

**Issue by FrankHu-MSFT** [MicrosoftDocs/ATADocs#233]
Issue with the Microsoft ATA temp logs: 
When the user is NOT admin, it will show up under their user folder. 

This : C:\Users\Administrator\AppData\Local\Temp

Should be this : C:\Users\&lt;your-logged-in-user&gt;\AppData\Local\Temp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f7a8c7e-482f-ed7f-797c-9090521da5d6
* Version Independent ID: dfa2b723-33ee-bd83-0f05-8b0dc96f1bd0
* Content: [Troubleshooting Advanced Threat Analytics using the logs](https://docs.microsoft.com/en-us/advanced-threat-analytics/troubleshooting-ata-using-logs#ata-deployment-logs)
* Content Source: [ATADocs/troubleshooting-ata-using-logs.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/troubleshooting-ata-using-logs.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
@FrankHu-MSFT
Thanks for your feedback and suggestion. I've modified the temp log locations as you suggested. 

Appreciate your contribution to our documentation!

**Comment by mlottner** [comment]
#please-close
