### ISSUE TITLE
Domain Synchronizer

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/ATADocs#238]
It's rather vague, if your entire gateway deployment uses the lightweight gateway deployment method, if you need to make any of the lightweight gateways a domain synchronizer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aef862a-ca68-b031-0d7e-f34ba1e05600
* Version Independent ID: 687b3e16-69ec-a0af-7ce8-db750bb4f1da
* Content: [Advanced Threat Analytics architecture](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-architecture#ata-lightweight-gateway-features)
* Content Source: [ATADocs/ata-architecture.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-architecture.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@poortom1004 Thanks for taking the time to comment and ask questions. 
I've modified the page to give more information about domain synchronizer candidates for installations where only Lightweight Gateways are in use. In this scenario, it is recommended to assign at least one Lightweight Gateway as the domain synchronizer (and potentially another as a backup). 
Appreciate your contribution.

**Comment by mlottner** [comment]
#please-close
