### ISSUE TITLE
SIEM forwarding to ATA Gateway

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/ATADocs#239]
It's vague what type of gateway is supported for forwarding SIEM data.  Can you forward SIEM data to both the lightweight gateway and dedicated gateway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89d6c0f-0950-88ca-4530-3b309526213f
* Version Independent ID: 87f5118f-d246-46c5-7711-8e2de2606b33
* Content: [Install Advanced Threat Analytics - Step 6](https://docs.microsoft.com/en-us/advanced-threat-analytics/install-ata-step6)
* Content Source: [ATADocs/install-ata-step6.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/install-ata-step6.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
@poortom1004 Thanks for taking the time to comment here. 
I've updated the notes and text around Windows event collection to hopefully make it more clear.  

There is no need to forward Windows events to Lightweight Gateways as they already read Window events locally. The need to forward for Gateways remains as specified. 

Let me know if this is now clear, or you think it needs additional clarification. 

Appreciate your contribution!

**Comment by mlottner** [comment]
#please-close
