### ISSUE TITLE
GPO Link

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/ATADocs#240]
Most other documentation specifies or recommends where or how to make the GPO link.  My assumption you want to cover all computers in the domain, so I would therefore state that the GPO should be linked to the root of the domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af4ac6cb-9755-50f5-b7f1-b7ce2a2a2f17
* Version Independent ID: 88cde4bc-114b-31ed-7eba-f3aefdce7dda
* Content: [Configure SAM-R to enable lateral movement path detection in Advanced Threat Analytics](https://docs.microsoft.com/en-us/advanced-threat-analytics/install-ata-step9-samr)
* Content Source: [ATADocs/install-ata-step9-samr.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/install-ata-step9-samr.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@poortom1004 Thanks for taking the time to leave your feedback and suggestions. I've modified the page to reflect that the group policy should be applied for every device in your organization. 

Appreciate your contribution to our community.

**Comment by mlottner** [comment]
#please-close
