### ISSUE TITLE
Can we use any AAD Tenant (public or gov or other sovereign cloud) to setup ATP?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/ATADocs#241]
Does ATP requires AAD Tenant in Azure Public Cloud only or can we use AAD Tenant from any Azure Sovereign cloud AAD tenant - like Azure Government Cloud ? Otherwise are there any restrictions or limitations related to AAD Tenant as a prerequisite for ATP setup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73885e78-0c05-9359-b85d-e76e12f02662
* Version Independent ID: be8e600a-3e61-ce2b-1cb7-09a40ef66533
* Content: [Azure Advanced Threat Protection frequently asked questions](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-technical-faq)
* Content Source: [ATPDocs/atp-technical-faq.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-technical-faq.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Anand-Moghe Thanks for taking the time to ask your question here!
Currently researching the tenants your listed in order to provide you with a complete answer and will respond as soon as I can.

**Comment by mlottner** [comment]
@Anand-Moghe At present, Azure ATP supports AAD tenants in Azure Public Cloud. As soon as support for others is added in general availability, the documentation will be updated. 

Appreciate your contribution to our community!
