### ISSUE TITLE
VMWare Virtual Machine Sensor Issue Section - Clarification Requested

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/ATADocs#242]
Hello!  The section for "VMware virtual machine sensor issue" at https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues#vmware-virtual-machine-sensor-issue first indicates that to resolve the issue, that we need to "set the following settings to 0 or Disabled in the virtual machine's NIC configuration: TsoEnable, LargeSendOffload, TSO Offload, Giant TSO Offload."  However right after this, it mentions a note that we "only need to disable IPv4 TSO Offload under the NIC configuration".

So I wanted to clarify whether we only need to disable "IPv4 TSO Offload", or whether we also need to disable TsoEnable, LargeSendOffload and Giant TSO Offload since the page appears to be offering conflicting advice.

If we do also need to disable TsoEnable and Giant TSO Offload, where are those options in the interface?  I do see LargeSendOffload called "Large Send Offload V2 (IPv4)" and "Large Send Offload V2 (IPv6)", but I am unable to find options for TsoEnable and Giant TSO Offload.

Also, it would be helpful to indicate what the impact is of disabling these options.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a56ac5-d132-1427-4c55-12921ec978c7
* Version Independent ID: aad125e7-7fa3-5fec-e025-2da79e11f44a
* Content: [Troubleshooting Azure ATP known issues](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues#vmware-virtual-machine-sensor-issue)
* Content Source: [ATPDocs/troubleshooting-atp-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@aakash-shah 
Thanks so much for your question. 
After completing advanced research with our team on this issue, we've determined the only relevant setting for Azure ATP sensors (and standalone sensors) is in the Note (under the NIC configuration, set **IPv4 TSO Offload** to **Disable**). 

The page is currently being updated to reflect the correction. 

Appreciate you taking the time to contribute to our community!

**Comment by mlottner** [comment]
#please-close
