### ISSUE TITLE
Technical Details About Not Using Dynamic Memory Or Other Memory Ballooning Feature

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/ATADocs#243]
Hello!  Our VMWare team is interested in more technical details/information on what specific problems occur if memory ballooning is used, and if this applies to VMWare, or if this only applies to Hyper-V.  Could additional detail be added either on this page or perhaps a FAQ somewhere?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@aakash-shah Thanks for your question!

The Azure ATP sensor has built-in logic to prevent a downgraded domain controller experience. For that reason, any VM-specific resource handling solutions such as Dynamic Memory or Memory Ballooning should be disabled on a virtual machine running the sensor. 
When additional resource management solutions are introduced such as Dynamic Memory or Memory Ballooning, they interfere with the sensor’s resource management assessments, resulting in poor sensor performance and dropped traffic.
The Azure ATP sensor resource manager assumes the allocated memory is fully reserved for the machine at all times. This behavior is true for all virtualization platforms. 

I'll update the FAQ to provide more information on this issue. Appreciate your contribution to our community.

**Comment by mlottner** [comment]
#sign-off

**Comment by mlottner** [comment]
#please-close
