### ISSUE TITLE
Can't select all groups

### ISSUE THREAD

**Issue by Maaarteen** [MicrosoftDocs/ATADocs#245]
We can't select any group except for cloud only security groups. Is there no way to select groups that were synched to AAD using AAD Connect? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04567e4-6efd-adfe-8367-d6bf3535607e
* Version Independent ID: 21365359-28dd-7aa4-cb62-b08cc90abb2a
* Content: [Tag sensitive accounts with Azure ATP](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/sensitive-accounts#feedback)
* Content Source: [ATPDocs/sensitive-accounts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/sensitive-accounts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Maaarteen Thanks for your question. 
You should be able to choose any/all groups in Active Directory, whether they are synced to Azure AD or not. If you can't chose groups configured in AD, open a support ticket to help resolve the  issue. 
Appreciate your contribution to our docs community!

**Comment by mlottner** [comment]
#please-close
