### ISSUE TITLE
Bandwidth usage

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/ATADocs#246]
How much data it will upload/download between AATP sensor and Azure ATP? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e1c17a-2f22-6a6f-d5ba-bedda3984aef
* Version Independent ID: 8531caef-8ef2-1f45-6362-0c83bd1de9dc
* Content: [Azure Advanced Threat Protection architecture](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-architecture)
* Content Source: [ATPDocs/atp-architecture.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-architecture.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@mzafzal1 Thanks for your question. 
We cannot provide data guidelines as it depends entirely on the amount of traffic in your environment. Azure ATP does compress and encrypt the data beforehand.

Appreciate you taking time to contribute to our community.

**Comment by mlottner** [comment]
#please-close
