### ISSUE TITLE
Typo in See Also section

### ISSUE THREAD

**Issue by CraigWilsonOZ** [MicrosoftDocs/ATADocs#247]
The last link in the Seel Also section is "Check out the zure ATP forum!", it should be "Check out the Azure ATP forum!"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f77d1a5-6730-91f4-35c3-d9b12bbf67bb
* Version Independent ID: 4c98c142-02f1-bd74-f75e-75e5a14c0e07
* Content: [Azure Advanced Threat Protection configure detection exclusions and honeytoken accounts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step7#feedback)
* Content Source: [ATPDocs/install-atp-step7.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step7.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@craigcaseyMSFT Thanks for catching that. Page will be updated with the fix shortly. 
Appreciate your contribution to our community!

**Comment by mlottner** [comment]
#please-close
