### ISSUE TITLE
Confusion on the direction of traffic.

### ISSUE THREAD

**Issue by JDWNL** [MicrosoftDocs/ATADocs#250]
The articles says "Alerts are sent from the Azure ATP sensor that detected the activity directly to the Syslog server."

Shouldn't this be "from the Azure ATP Sensor that was nominated to forward Syslog traffic" or something along those lines? Since it's the Azure ATP _Workspace_ that's technically doing the detections and subsequently forwards them via Syslog to a designated Sensor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1a48e5-a4ea-495b-6656-793e23d807ef
* Version Independent ID: 9908c36d-b7b7-ab72-f162-77a54da8b42d
* Content: [Setting Syslog settings in Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/setting-syslog#feedback)
* Content Source: [ATPDocs/setting-syslog.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/setting-syslog.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@JDWNL Thanks for your question. 
I'm double checking with product to make sure the information flow described here is correct. Will update the page with their answer.

**Comment by mlottner** [comment]
@JDWNL Thanks for your patience while I researched this issue. 

The decision to send a syslog message is made on the backend, and the nominated Azure ATP sensor pulls the send requests from the backend, and then sends the message. 
The page will be updated with a fixed explanation in the next publish. 

Appreciate your contribution to our docs community!

**Comment by mlottner** [comment]
#please-close
