### ISSUE TITLE
Page Typo

### ISSUE THREAD

**Issue by eltoncarr** [MicrosoftDocs/ATADocs#259]
"The Attack time line This is the default landing page you are taken to when you log in to the Azure ATP portal." should read like "The Attack time line is the default landing page you are taken to when you log in to the Azure ATP portal." or something similar. "The Attackk timeline This is..." is incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b42fe40-5997-589e-a195-955dbcc256cf
* Version Independent ID: a1fed995-fcfa-99a1-5fc1-ebde8f5264c6
* Content: [Understanding the Azure Advanced Threat Protection portal](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/workspace-portal#feedback)
* Content Source: [ATPDocs/workspace-portal.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/workspace-portal.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@eltoncarr Thanks for catching that. This page is fixed in the next site publish. 
Make sure to try the new [Cloud App Security portal](https://portal.cloudappsecurity.com) for enhanced features and access capabilities. 
Appreciate you taking the time to contribute to Azure ATP docs!

**Comment by mlottner** [comment]
#please-close
