### ISSUE TITLE
NNR missing on architecture scheme

### ISSUE THREAD

**Issue by Lelivienne** [MicrosoftDocs/ATADocs#263]
since "Network Name Resolution (NNR) is a main component of Azure ATP functionality" why it is missing from architecture schematics? after reading this page you can't actually tell what it is or where it sits.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e880e6e-9cae-b122-14d9-963eee86d9cc
* Version Independent ID: c8ab5d85-f3a4-2c24-d6c6-5940e26aea42
* Content: [Azure Advanced Threat Protection prerequisites](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-prerequisites#feedback)
* Content Source: [ATPDocs/atp-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-prerequisites.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Lelivienne Thanks for your feedback. 

Network Name Resolution is a main component of the Azure ATP service but it can only be provided when the source information is available to Azure ATP for ingestion and analysis (as specified in the requirements). The Azure ATP service provides multiple services on top of the data received - one of which is NNR. Were you expecting all of the functional services to be detailed within the Azure ATP cloud in the schematic? 
If you can think of a great way to express all of the service functionalities visually, I'd be happy to enhance the schematic.

Appreciate you taking the time to comment and contribute to our community!

**Comment by Lelivienne** [comment]
as a person which tries to understand how it works, what you said is not what i undestand from https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-nnr-policy where it suggests it is working as a part ATP Sensor. 
it looks like it is about semantics - 'component' suggest something 'physical' like ATP sensor, and portal, and what you describing is a 'feature' or 'capability'. 
i will be smarter after deployment, but it would be better to understand 'main coponents' before you actually deploy (;

**Comment by mlottner** [comment]
@Lelivienne Thanks for the feedback. It is super important to learn what wasn't explained well. I'll work to improve the language and drawing to make it more clear. 

Appreciate your contribution to our community!

**Comment by mlottner** [comment]
#please-close
