### ISSUE TITLE
Out of date information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#265]
this page references Ignite 2018, please replace those presentation as appropriate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad74a8f3-7431-410b-9a72-a6422a64a7fa
* Version Independent ID: ed3c9821-093e-4015-ec33-943c28d843ce
* Content: [What is Azure Advanced Threat Protection (Azure ATP)?](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/what-is-atp#microsoft-ignite)
* Content Source: [ATPDocs/what-is-atp.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/what-is-atp.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@DeanGross Thanks for your feedback. 
The presentations will be updated in the next publish.

**Comment by mlottner** [comment]
#please-close

**Comment by DeanGross** [comment]
Why was this closed? the page still references Ignite 2018 and has not been updated to the latest presentations from the conference in 2019
