### ISSUE TITLE
managing atp health 

### ISSUE THREAD

**Issue by NTDS** [MicrosoftDocs/ATADocs#266]
The text in this page is relevant to security alerts.  For the health alerts, wouldn't expect to see delete (at least I don't see it in my ATP health section), and I would expect the text for suppress to indicate it is to suppress that alert type temporarily, and alert again if it recurs after one day, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5753ba00-e959-33ed-8b0d-6e9082a3dd5b
* Version Independent ID: 3abbc70b-3d9d-9bc0-2274-c4efe2bc2b5f
* Content: [Monitor Azure Advanced Threat Protection System Health and Events](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-health-center#feedback)
* Content Source: [ATPDocs/atp-health-center.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-health-center.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@NTDS Thanks for taking the time to give us feedback. 
The text in this page is relevant to Azure ATP service health alerts as they appear in the same timeline as security alerts. 
I'll work to improve the page to add clarity for health alert only actions and their definitions. 
Thanks for contributing to our docs community!

**Comment by mlottner** [comment]
#please-close
