### ISSUE TITLE
Broken link to "Service Description"

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/ATADocs#267]
This link is broken:
"A list of feature variances can be found in the Service Description."
https://docs.microsoft.com/enterprise-mobility-security/solution/ems-azure-atp-govt-service-description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf65633-f9a6-d971-410b-e0dcd1868cb8
* Version Independent ID: 3e923229-f1ac-50ba-27a6-429212f54138
* Content: [Azure Advanced Threat Protection for US Government GCC Highs](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-us-govt-gcc-high)
* Content Source: [ATPDocs/atp-us-govt-gcc-high.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-us-govt-gcc-high.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@SwiftOnSecurity Thanks for taking the time to give us feedback on this page. 
Appreciate you catching the broken link. Link will be updated within the next republish (~24 hours).

**Comment by mlottner** [comment]
#please-close
