### ISSUE TITLE
Add access requirements to MCAS section

### ISSUE THREAD

**Issue by astridmcclean** [MicrosoftDocs/ATADocs#268]
Update this note to ensure that AATP administrators are aware that the MCAS admin permissions may be different between the portals.

Note

If you don't have a subscription for Cloud App Security, you will still be able to use the Cloud App Security portal to investigate Azure ATP alerts and deep dive on users and their on-premise managed activities, but you won't receive related insights from your cloud applications. Details on managing administrative permissions to the Cloud App Security portal can be found here < https://docs.microsoft.com/en-us/cloud-app-security/manage-admins >

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23856fa8-a218-5cb2-b65d-8e42fd3df0e9
* Version Independent ID: 64b6a426-ed36-5c8f-50d7-84dfcf4e4938
* Content: [Azure Advanced Threat Protection in Microsoft Cloud App Security](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-mcas-integration#feedback)
* Content Source: [ATPDocs/atp-mcas-integration.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-mcas-integration.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@astridmcclean Thanks for taking the time to give us feedback. 
I'll add your note and publish in the next docs release (~24 hours).
Appreciate your contribution to our community.

**Comment by mlottner** [comment]
#please-close
