### ISSUE TITLE
Npcap guide

### ISSUE THREAD

**Issue by st-christ** [MicrosoftDocs/ATADocs#269]
Hi Team,

You should try to have someone do the Npcap installation that hasn't done it before. It's not really very useful the guide since there is no direct link to the download and the command line is someting we have to find ourselves.

1. Uninstall WinPcap
2. Download Npcap from:
https://nmap.org/npcap/dist/
find the latest npcap-version.exe file (0.9984 as of 2019-12-12)
3. Install with this command:
npcap-version.exe /loopback_support=no /winpcap_mode=yes
Ps. You can also just untick loopback support and tick WinPcap mode in the GUI
4. Install the sensor

Friendly regards
StChrist (Microsoft)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a56ac5-d132-1427-4c55-12921ec978c7
* Version Independent ID: aad125e7-7fa3-5fec-e025-2da79e11f44a
* Content: [Troubleshooting Azure ATP known issues](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues#feedback)
* Content Source: [ATPDocs/troubleshooting-atp-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@st-christ Thanks so much for taking the time to give us feedback. 
We've re-tested the scenario and I've updated the page based on your suggestions and feedback from the product group. . 
This page with go live with new information in the next publish (~24 hours). 
Appreciate your contribution to our user community!

**Comment by mlottner** [comment]
#please-close
