### ISSUE TITLE
Important note missing!

### ISSUE THREAD

**Issue by st-christ** [MicrosoftDocs/ATADocs#271]
It would be nice if you would add a note to this article that says that you should NOT disable the Print Spooler on all DC's, since that would break the print queue pruning function for printers listed in AD:
https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server#print-spooler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31d4964-423b-d3cf-9872-aafb9253da4c
* Version Independent ID: b943f06f-29f8-690a-6204-125acee3007f
* Content: [Azure Advanced Threat Protection Print spooler identity security posture assessments](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-cas-isp-print-spooler)
* Content Source: [ATPDocs/atp-cas-isp-print-spooler.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-cas-isp-print-spooler.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@st-christ Thanks for your feedback. 
Will discuss with the product team and update the page as needed. 
Appreciate your contribution to docs. 
#please-close
