### ISSUE TITLE
The Azure Advisors group mentioned in this article has been closed

### ISSUE THREAD

**Issue by Joon** [MicrosoftDocs/ATADocs#275]
Azure Advisors reorganized in January 2020 into Azure Customer Connection and Azure Partner Connection. The linked group under the heading "Join the Azure ATP Yammer community" is now closed. 

There is a new group in Azure Customer Connection called "Security", which might be a good replacement. This is the link to that group: https://www.yammer.com/azureadvisors/#/threads/inGroup?type=in_group&feedId=13248053248

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad74a8f3-7431-410b-9a72-a6422a64a7fa
* Version Independent ID: ed3c9821-093e-4015-ec33-943c28d843ce
* Content: [What is Azure Advanced Threat Protection (Azure ATP)?](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/what-is-atp#feedback)
* Content Source: [ATPDocs/what-is-atp.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/what-is-atp.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Joon Thanks for taking the time to share this update. 
We'll update the page ASAP with the correction. 
@shsagir 
#please-close

**Comment by rohancragg** [comment]
The Yammer group is now showing as [CLOSED]

https://www.yammer.com/azureadvisors/#/threads/inGroup?type=in_group&feedId=9386893

This one is probably the closest equivalent:

https://www.yammer.com/azureadvisors/#/threads/inGroup?type=in_group&feedId=13301702656
