### ISSUE TITLE
"Service Description" link is broken again

### ISSUE THREAD

**Issue by grbray** [MicrosoftDocs/ATADocs#276]
Link should go here:
https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-azure-atp-govt-service-description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf65633-f9a6-d971-410b-e0dcd1868cb8
* Version Independent ID: 3e923229-f1ac-50ba-27a6-429212f54138
* Content: [Azure Advanced Threat Protection for US Government GCC Highs](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-us-govt-gcc-high)
* Content Source: [ATPDocs/atp-us-govt-gcc-high.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-us-govt-gcc-high.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by shsagir** [comment]
@grbray Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
