### ISSUE TITLE
Events can be forwarded only to Azure ATP standalone sensor? Or perhaps to an AATP sensor installed on another DC?

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/ATADocs#277]
"These events can either be read automatically by the Azure ATP sensor or in case the Azure ATP sensor is not deployed, they can be forwarded to the _Azure ATP standalone sensor_ in one of two ways, by configuring the Azure ATP standalone sensor to listen for SIEM events or by Configuring Windows Event Forwarding."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/configure-windows-event-collection)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-windows-event-collection.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@rafalfitt Thanks for taking the time to post your question. 
No, in that scenario, as written, they can only be forwarded to a standalone sensor. They cannot be forwarded to a different sensor on another domain controller. 
Appreciate your contribution to our docs community!
#please-close
