### ISSUE TITLE
About Azure ATP sensor network entity resolution

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/ATADocs#278]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/ATADocs.ja-jp/issues/25

@kahosoka commented 7 hours ago
"Perform resolution of network entities (users, groups, and computers)" in the Azure ATP sensor description, please provide details here.
■Contents to be described
・What exactly does user name, group name, and computer name resolution do?
・Which values are used specifically to resolve user names, group names, and computer names?

If you do not provide this information, we will not be able to accurately provide you with Azure ATP, so please cooperate.
![imagen](https://user-images.githubusercontent.com/26746247/72622553-350df580-3922-11ea-8594-02a3eeffe4f7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e1c17a-2f22-6a6f-d5ba-bedda3984aef
* Version Independent ID: 8531caef-8ef2-1f45-6362-0c83bd1de9dc
* Content: [Azure Advanced Threat Protection architecture](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-architecture#feedback)
* Content Source: [ATPDocs/atp-architecture.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-architecture.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by mlottner** [comment]
@CeciAc Resolution of user name, group name and computer name determined what these entities are, meaning which user name, group name and computer name are the origination of the suspicious activity being reported. The values used are determined by Azure ATP from the sensor data and applied using network name and entity resolution techniques of the service.
I'm closing this issue for now, but feel free to continue to comment if/as needed.

**Comment by mlottner** [comment]
#please-close
