### ISSUE TITLE
VMWare NIC issue 

### ISSUE THREAD

**Issue by maclaes** [MicrosoftDocs/ATADocs#281]
Hey,

The documentation states to change the following parameter:
"Set the following to Disabled in the virtual machine's NIC configuration: IPv4 TSO Offload. "

however, on our vmware Domain controller, we have an Intel PRO/1000 MT network adapter which has different  Advanced Properties options. 

Is the "IPv4 Checksum Offload" parameter the same as "IPv4 TSO Offload" ?

thanks!

**Comment by mlottner** [comment]
Hi Maclaes 

Are you using a NIC Passthrough?

Are you receiving health alerts for dropped packets or trying to be proactive with this approach?

**Comment by maclaes** [comment]
Hey,

Our infrastructure/vm architect wanted to know the exact NIC parameter to
change on a normal VM (just one NIC). Since our VM NIC brand differs
slightly from the one in the documentation, we wanted to verify if "IPv4
Checksum Offload" on our NIC (Intel PRO/1000 MT) is the same as "IPv4 TSO
Offload" on the vmxnet3 ethernet adapter from the documentation.

Kr!
Maarten.

**Comment by mlottner** [comment]
@maclaes 
No, these are two different things. 

You would need to disable TSO (TCP segmentation offload) or something also known as LSO (large send offload). 
https://en.wikipedia.org/wiki/Large_send_offload

However, still not clear if you mapped a physical NIC to the VM, and are therefore not using a virtual NIC? If so, not sure it is relevant for you to change offloading at all.

I'm closing this issue for now, but feel free to continue to answer/ask in the thread if/as needed.

**Comment by mlottner** [comment]
#please-close
