### ISSUE TITLE
Scheduled Reports - should have the option actually include the reports

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/ATADocs#285]
At the moment, scheduled reports provide links to the reports.  Which when combined with MFA for the admin accounts, etc, it takes more time to pull the reports...might as well just have gone to the portal and requested it since not much value in emailing a report that isn't attached other than to serve as a reminder that you need to pull the report.  Would be significantly more valuable to have the reports attached - can determine quickly if it is the "norm" or if need to investigate more, etc.  Some may like reports to stay out of email, but that can be an option to turn off/on depending on preferences.
Thanks.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b70670-d462-093c-c876-9316d58c5aeb
* Version Independent ID: 2104e967-cca7-8cf9-abe6-e0fa55742ff7
* Content: [Working with Azure ATP Reports](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/reports)
* Content Source: [ATPDocs/reports.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/reports.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by mlottner** [comment]
@J-Fedor Thanks for taking the time to leave us documentation feedback. 
I believe your intended audience was product feedback, so I forwarded your feedback to the Azure ATP product team. If you had a documentation issue, feel free to add it here.
Appreciate your contribution!
#please-close
