### ISSUE TITLE
Lack of details in the doc

### ISSUE THREAD

**Issue by KjetilEVRY** [MicrosoftDocs/ATADocs#287]
It's not clear exactly why an account is considered dormant, and what's the logic behind it. We sync all cloud accounts from our on-prem AD with AAD Connect, and I find it hilarious that my own and several daily administrators got reported as dormant accounts. Please provide more detail here, otherwise this will be a needle-in-a-haystack drill (and thereby little true security value). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e536d6-4dc8-5432-0672-94e7044a99fa
* Version Independent ID: 91364dbb-a9c1-68c3-6a5f-e08d4005a6be
* Content: [Azure Advanced Threat Protection dormant entities security assessments](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-cas-isp-dormant-entities)
* Content Source: [ATPDocs/atp-cas-isp-dormant-entities.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-cas-isp-dormant-entities.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by mlottner** [comment]
@KjetilEVRY Thanks for taking the time to leave us docs feedback. 
The Dormant Entities report logic is included in the report UI as shown below.
As it is displayed in the tooltip, I didn't think it was necessary to also detail it in the docs. Was that a mistake? Would it help to clarify the distinction between on-premises and cloud based user activities? 
Dormant Entities logic is based on your on-premises activities
So if your AD sign-in data is older than 6 months, the account is disabled or expired.
Even if that user has cloud activities, that user is still profiled by this report as dormant.   
Happy to hear your thoughts and the page can be updated if needed. 
![dormant entities from sensitive groups](https://user-images.githubusercontent.com/41567042/74602703-5cd4b280-50b4-11ea-919f-2c3b7295277d.png)

**Comment by KjetilEVRY** [comment]
Hi, some more information in the docs would be great yes, tooltips is not always the best place to put detailed explanations. 
However, it should be crystal clear that this will also create a lot of false positives.

A common scenario for many organizations, is to have all their users sourced from AD even if they use Intune/AzureAD/O365 only. This is due to internal HR workflow and employee onboarding, and most organizations with a moderately complex environment (VPN, WiFi with Radius authentication, printer with followme-capabilites, etc) still require a traditional AD. Even if those users never authenticate directly to a domain controller, they are still in use. And my self, who never uses a domain-joined device (only Intune/AzureAD joined) will never authenticate to a DC - but I can assure you that I do work everyday even if MCAS insists that I am a dormant user.

I also don't understand what is the sensitive group logic here, as I got used to AzureATP notifying me about changes to for example Domain Admins. My own business account that MCAS reports as dormant does not have any special AD admin group membership (separate admin account ref priviledged workstation principle). The same goes for many other accounts reported by MCAS as dormant.

**Comment by mlottner** [comment]
@KjetilEVRY  Thanks for taking the time to explain what you were looking for. I've passed your product/logic feedback on to the Azure ATP product team and we'll improve this page to add more of the logic explanation around what gets reported. 
I'm closing the docs issue for now, but feel free to continue to send docs feedback here, or by opening an additional issue on other pages. 
Appreciate your contribution to our community!

**Comment by mlottner** [comment]
#please-close
