### ISSUE TITLE
Incorrect RFC

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/ATADocs#293]
Hi there,

Great page, very informative on expected log content. You reference RFC5242 when you mean RFC5424, easy mistake to make. 

Keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff82a4d-1c0d-7d05-f383-78a5506dda02
* Version Independent ID: 02bd7bc8-76ca-2511-93cb-f3f3de46337d
* Content: [Azure ATP SIEM log reference](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/cef-format-sa#feedback)
* Content Source: [ATPDocs/cef-format-sa.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/cef-format-sa.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@phillym Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@phillym Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
