### ISSUE TITLE
Successor to ATA?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#297]
The Uservoice page is discontinued so it seems. Therefore I put my question here. What is the recommended successor product now ATA is declared end of life in jan 2021? It is one of the cloud variants of (Defender) ATP is presume. But what product is replacing the ATA functionality for on-premises behaviour analysis? In other words, what product/licenses do we need and what do we need to configure to protect our on-premises systems at the same level?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cddc0d9a-9a14-4993-cb28-43b72d8dbe4f
* Version Independent ID: 499064ba-7008-0d40-6cb0-457494a4cb13
* Content: [Advanced Threat Analytics recommended upgrade path](https://docs.microsoft.com/en-us/advanced-threat-analytics/upgrade-path)
* Content Source: [ATADocs/upgrade-path.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/upgrade-path.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@andrePKI Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@andrePKI Thanks for your feedback.

After investigating your queries, we will submit an update link and regarding the successor product, you can use the follwoing guide: [Advanced Threat Analytics (ATA) to Azure Advanced Threat Protection (Azure ATP)](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/ata-atp-move-overview)

Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
