### ISSUE TITLE
Which version am I running

### ISSUE THREAD

**Issue by jwilleke** [MicrosoftDocs/ATADocs#307]
[Enter feedback here]
So the docs say "Applies to: Advanced Threat Analytics version 1.9"

And this nice pages shows which versions are supported.
"Updates" shows the versions of the ATA Gateways.
How do I know which version of the ATA Center is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d587c5ad-4a52-c244-5142-f780cc3a2c96
* Version Independent ID: e34d972f-ee87-9845-1165-76fdaf956c2c
* Content: [Advanced Threat Analytics versions](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-versions)
* Content Source: [ATADocs/ATA-versions.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ATA-versions.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jwilleke Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@jwilleke Thanks again for your question. I received the following response from the product team.

> The Center version is viewable in the About dialog. Gateway does not have an interface, but you can view the versions in the configuration menus in Center,

You can click the 3 vertical dots to open the menu and then click About.

Hope that helps. In the meantime I am closing this issue. If you have any further assistance with this, please contact support.
