### ISSUE TITLE
Rename product references

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#308]
Windows Defender ATP has been renamed to Microsoft Defender ATP. please update to decrease confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329ebdcf-c057-ee03-e478-58e497024bee
* Version Independent ID: b67561aa-d033-5375-27b4-9dc6c199ab8a
* Content: [Azure Advanced Threat Protection integration with Windows Defender ATP](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/integrate-wd-atp)
* Content Source: [ATPDocs/integrate-wd-atp.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/integrate-wd-atp.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
