### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/ATADocs#309]
link "BRK3117" - SecOp and incident response with Azure ATP - 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad74a8f3-7431-410b-9a72-a6422a64a7fa
* Version Independent ID: ed3c9821-093e-4015-ec33-943c28d843ce
* Content: [What is Azure Advanced Threat Protection (Azure ATP)?](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/what-is-atp)
* Content Source: [ATPDocs/what-is-atp.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/what-is-atp.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@challengelogic Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
