### ISSUE TITLE
ATA update

### ISSUE THREAD

**Issue by sneakernuts** [MicrosoftDocs/ATADocs#310]
Looks like 1.9.2 is approaching EOL. Any news on an update soon? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d587c5ad-4a52-c244-5142-f780cc3a2c96
* Version Independent ID: e34d972f-ee87-9845-1165-76fdaf956c2c
* Content: [Advanced Threat Analytics versions](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-versions#feedback)
* Content Source: [ATADocs/ATA-versions.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ATA-versions.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@sneakernuts Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@name Thanks again for contacting Microsoft. The following information I received from support may be helpful to you:

> Microsoft ATA support is defined by the [Microsoft Lifecycle Policy for ATA 1.x,](https://support.microsoft.com/en-us/lifecycle/search?alpha=Advanced%20Threat%20Analytics%201.X) with mainstream support ending on January 12, 2021. Extended support (which provides only security fixes) will continue until January 2026. Update 1.9.3 is also expected later this year and will be the final update released for ATA.  We are encouraging all ATA customers to move to Azure ATP.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
