### ISSUE TITLE
HP ArcSight is MicroFocus ArcSight

### ISSUE THREAD

**Issue by Fredengren** [MicrosoftDocs/ATADocs#319]
[Enter feedback here]
HP ArcSight is MicroFocus ArcSight

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813a14c6-6b22-95e6-43c6-a8f29425f1b4
* Version Independent ID: b301043f-fe9e-2cff-3f33-d1a69ef38055
* Content: [Install Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/configure-event-collection#feedback)
* Content Source: [ATPDocs/configure-event-collection.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-event-collection.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Fredengren Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
