### ISSUE TITLE
Plan capacity for your Azure ATP solution, takes you to a wrong page

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/ATADocs#321]
Plan capacity for your Azure ATP solution link in Next Steps takes you to a wrong link.
https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step5 instead of https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-capacity-planning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee91dca-7081-4eaa-8728-7674d7cd4870
* Version Independent ID: 2eae6069-f58f-ad69-3511-1a4e204db31e
* Content: [Install Azure ATP sensor quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step4)
* Content Source: [ATPDocs/install-atp-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step4.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@zlDev Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
