### ISSUE TITLE
memory vs space

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/ATADocs#323]
Hi

When referred to "Memory (GB)", do you mean RAM?
When referred to "minimum of 6 GB of space", do you mean disk storage?

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29720d50-2bdb-f6a8-5be0-71bc27bef143
* Version Independent ID: 6be60338-bb13-e166-946a-067de5daa5b9
* Content: [Planning your Azure Advanced Threat Protection deployment quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-capacity-planning#sizing)
* Content Source: [ATPDocs/atp-capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-capacity-planning.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@zlDev Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
