### ISSUE TITLE
Broken link!

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/ATADocs#338]
This link is broken (code 404) : Microsoft 365 Enterprise GDPR Compliance site.
![image](https://user-images.githubusercontent.com/48426980/83219519-a315d380-a1c4-11ea-9352-89dd7d026b57.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e4133e-5dd2-d460-829b-ba378109fec3
* Version Independent ID: f1a283fe-164f-9c60-bef0-ad5094447ae7
* Content: [Azure Advanced Threat Protection personal data policy](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-privacy-compliance)
* Content Source: [ATPDocs/atp-privacy-compliance.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-privacy-compliance.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@PeteHaigh-MSFT Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@PeteHaigh-MSFT Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
