### ISSUE TITLE
Configure SAM-R capabilities from ContosoDC

### ISSUE THREAD

**Issue by tc-p** [MicrosoftDocs/ATADocs#339]
I think inclusion of few more configuration changes in ContosoDC Domain policy will help attack simulation.

I setup lab environment as per playbook and started attack simulation with Reconnaissance playbook. At Directory Service Reconnaissance I was getting "system error 5" while executing _net user /domain_ command line, tried again with elevated command prompt but result was same. PFB screenshot

![System Error](https://user-images.githubusercontent.com/64949635/83249744-ae68ff00-a1c4-11ea-8af7-4feb3ef991b4.jpg)

Post doing following changes at ContosoDC Domain policy the issue was resolved

1. Goto Server Manager --> Tools --> Group Policy Management
2. Right click on domain control and select edit
3. Goto Computer configuration --> Policies --> Windows Settings--> security settings --> local policies --> security options
4. Define below SAM policies as disabled
Network access: Do not allow anonymous enumeration of SAM accounts
Network access: Do not allow anonymous enumeration of SAM accounts and shares
5. Add _Everyone_ to the list of approved accounts under _Network access: Restrict clients allowed to make remote calls to SAM_ SAM policy

![add-everyone](https://user-images.githubusercontent.com/64949635/83661941-7d356800-a5e4-11ea-96f3-c81fa2bb4276.jpg)

6. open cmd and run _gpupdate /force_ on DC, Adminpc and Victimpc

After above steps I tried Directory Service Reconnaissance again and this time it worked!

![Success](https://user-images.githubusercontent.com/64949635/83251561-6697a700-a1c7-11ea-873e-52245f6d0cb4.jpg)

Hope this helps.

**Comment by shsagir** [comment]
@tc-p Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@tc-p Thanks again for the feedback. A task has been added to look into the feasibility of adding the external IDs to the topic, but it will take a while to implement. In the meantime, we are closing this issue. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.
