### ISSUE TITLE
External ID of health alert

### ISSUE THREAD

**Issue by ginjih** [MicrosoftDocs/ATADocs#340]
[Enter feedback here]
It's very useful if this health alert list includes each external-ids.
We are receiving syslog from Azure ATP sensor but I didn't find each ext-ids in docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79c7f20-b009-da8a-5fdd-13f5902e772f
* Version Independent ID: 6c6fa2c6-1d3c-f8b3-af9a-9a6b7ca0d4af
* Content: [Understanding Azure ATP health alerts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/health-alerts)
* Content Source: [ATPDocs/health-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/health-alerts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ginjih Thanks for contacting Microsoft with feedback about our product documentation. I like the suggestion and will follow up with the product team.

Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ginjih Thanks for your feedback. We've added the suggestion to our docs feature request list. In the meantime, we are closing this issue. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
