### ISSUE TITLE
Should disable Print Spooler service or not? 

### ISSUE THREAD

**Issue by ClaudioMerola** [MicrosoftDocs/ATADocs#361]
This page explicitly says the Print Spooler should be disabled on Domain Controllers and even gives a good explanation on why. 

But this other page: 
https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server 

About which services can be disable on Windows Server 2016 also explicitly says that Print Spooler service should not be disable on domain controllers because:

"On a domain controller, the installation of the DC role adds a thread to the spooler service that is responsible for performing print pruning – removing the stale print queue objects from the Active Directory. If the spooler service is not running on at least one DC in each site, then the AD has no means to remove old queues that no longer exist. Ask the performance team blog. "

So, what page is correct? 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31d4964-423b-d3cf-9872-aafb9253da4c
* Version Independent ID: b943f06f-29f8-690a-6204-125acee3007f
* Content: [Azure Advanced Threat Protection Print spooler identity security posture assessments](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-cas-isp-print-spooler)
* Content Source: [ATPDocs/atp-cas-isp-print-spooler.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-cas-isp-print-spooler.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ClaudioMerola Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ClaudioMerola Thanks so much for taking the time to leave us your comment on our documentation. We're working with the Windows Server team to align our documentation based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
