### ISSUE TITLE
Syslog step 10 miss-type

### ISSUE THREAD

**Issue by byronsims** [MicrosoftDocs/ATADocs#372]
This page: https://docs.microsoft.com/en-us/azure-advanced-threat-protection/setting-syslog
Step 10 says: "Select **Send text Syslog message** and then verify the message is received in your Syslog infrastructure solution."
It should say:  "Select **Send test Syslog message** and then verify the message is received in your Syslog infrastructure solution."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1a48e5-a4ea-495b-6656-793e23d807ef
* Version Independent ID: 9908c36d-b7b7-ab72-f162-77a54da8b42d
* Content: [Setting Syslog settings in Azure Advanced Threat Protection](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/setting-syslog)
* Content Source: [ATPDocs/setting-syslog.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/setting-syslog.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@byronsims Thanks for reporting the issue. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
