### ISSUE TITLE
This page doesn't actually contain a powershell command

### ISSUE THREAD

**Issue by yojo056** [MicrosoftDocs/ATADocs#377]
Hi! you wrote on here their should be command line and powershell commands, you didn't include the powershell command, only command line. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4856b2df-3ad3-526f-b7cf-a24a44340744
* Version Independent ID: fd11c910-7991-cdf1-8ca7-7e7d61ec19bf
* Content: [Install Azure Advanced Threat Protection Silently](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-silent-installation)
* Content Source: [ATPDocs/atp-silent-installation.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-silent-installation.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@yojo056 Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
