### ISSUE TITLE
Missing line from code snippet

### ISSUE THREAD

**Issue by IanJDan** [MicrosoftDocs/ATADocs#388]
Code snippet on this page appears to be missing a line at the end:
`$EventLogConfiguration.SaveChanges()`

That would make the last three lines:
```
$EventLogConfiguration = New-Object -TypeName System.Diagnostics.Eventing.Reader.EventLogConfiguration("Security")
$EventLogConfiguration.SecurityDescriptor = $EventLogConfiguration.SecurityDescriptor + $ATADaclEntry
$EventLogConfiguration.SaveChanges()
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1ec89c-59c1-8802-bd46-729867ecfa64
* Version Independent ID: 8d702acc-d376-f828-f66a-4181663bfcba
* Content: [What's new in ATA version 1.8](https://docs.microsoft.com/en-us/advanced-threat-analytics/whats-new-version-1.8#ata-gateway-on-windows-server-core)
* Content Source: [ATADocs/whats-new-version-1.8.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/whats-new-version-1.8.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@IanJDan  Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by shsagir** [comment]
@IanJDan Thanks again for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
