### ISSUE TITLE
not explained acronyms

### ISSUE THREAD

**Issue by hontoz** [MicrosoftDocs/ATADocs#397]
It would be really helpful if you described at least once what a TP, B-TP, and FP are within the page. I had to look that up separately and it made reading the documentation more confusing. 

I also would recommend maybe considering just not abbreviating them at all, and leaving them as True Positive, Benign True Positive, and False Positive as it's much clearer within the context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a4ad8f-0039-5a6c-c97a-3a0dcdbfd492
* Version Independent ID: 4ec306c4-50c3-9745-682c-0e131d2a90c2
* Content: [Azure ATP reconnaissance phase security alerts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-reconnaissance-alerts#account-enumeration-reconnaissance-external-id-2003)
* Content Source: [ATPDocs/atp-reconnaissance-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-reconnaissance-alerts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@hontoz  Thanks for your feedback. The definitions are in the [Understanding security alerts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/understanding-security-alerts) topic featured at the beginning of each alert tutorial. However, we'll also link the section heading to the definition. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
