### ISSUE TITLE
message in document does not match message in portal.

### ISSUE THREAD

**Issue by jimtr123** [MicrosoftDocs/ATADocs#421]
in the AATP portal the message reads "Some forwarded events **are not being** analyzed"
in this document it reads "Some forwarded events **could not be** analyzed"

documentation of the errors should match the wording in the portal exactly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79c7f20-b009-da8a-5fdd-13f5902e772f
* Version Independent ID: 6c6fa2c6-1d3c-f8b3-af9a-9a6b7ca0d4af
* Content: [Understanding Azure ATP health alerts](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/health-alerts)
* Content Source: [ATPDocs/health-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/health-alerts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jimtr123 Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
