### ISSUE TITLE
Expand to other products

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#425]
[Enter feedback here]
Could someone please create a similar page for all of the other Defender products that leverage the Mitre ATT&CK framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac27fc05-6fd3-d558-7772-16bf0b9873d2
* Version Independent ID: 8b9f6583-95c2-9948-7bee-428fbd8e1629
* Content: [Azure ATP security alert guide](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/suspicious-activity-guide?tabs=external)
* Content Source: [ATPDocs/suspicious-activity-guide.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/suspicious-activity-guide.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. I've forwarded your suggestion and am closing this issue.
