### ISSUE TITLE
Update Ignite Reference

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#433]
A link points to Ignite 2018, please update this to more current information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8df167b-3d6a-ebd1-4401-4596565b9238
* Version Independent ID: 56c40693-376f-4a86-ca85-5ecfd9cb3558
* Content: [What is Azure Advanced Threat Protection (Azure ATP)?](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/what-is#microsoft-ignite)
* Content Source: [ATPDocs/what-is.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/what-is.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
