### ISSUE TITLE
Highlight NOT to enable that policy on Domain Controllers

### ISSUE THREAD

**Issue by tobiasabele** [MicrosoftDocs/ATADocs#434]
Highlight **NOT** to enable this policy on Domain Controllers, as it will bring down the Logons to the Domain!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2fca484-a7a3-a364-2f0f-439d5be6e75a
* Version Independent ID: 7c9e77cb-2db5-5816-e323-c52eee4d12b1
* Content: [Configure SAM-R to enable lateral movement path detection in Microsoft Defender for Identity](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-step8-samr)
* Content Source: [ATPDocs/install-step8-samr.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-step8-samr.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@tobiasabele Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

**Comment by Mike-Crowley** [comment]
I will also add that enabling it prevented remote desktop. Separately it brought down DirectAccess running on Windows 2012 R2.
