### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dbronco3** [MicrosoftDocs/ATADocs#438]
Powershell command should start with .\ not ./

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2cb616-13e9-65be-94b6-de46ab00bafc
* Version Independent ID: 0313bbbd-5ec6-f850-4b02-cb10f4b599c5
* Content: [Install Microsoft Defender for Identity Silently](https://docs.microsoft.com/en-us/defender-for-identity/silent-installation)
* Content Source: [ATPDocs/silent-installation.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/silent-installation.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@dbronco3 Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @dbronco3
