### ISSUE TITLE
doesn't mention that restart is required

### ISSUE THREAD

**Issue by HenrikBernhard** [MicrosoftDocs/ATADocs#452]
[Enter feedback here]
for the section about TSO and vmxnet 3 NICs - it could mention that a restart of the server is required after changing the setting. 
https://docs.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues#vmware-virtual-machine-sensor-issue

It would also be helpful to put powershell to change both IPv4 TSO offload, as well as the LRO setting - instead of having GUI for one, and powershell for others. 

Could be something like: 
1. find name of network adapter with 
get-netadapter

2. replace "Ethernet0" and run the 3 commands. 
Set-NetAdapterAdvancedProperty Ethernet0 -DisplayName "IPv4 TSO Offload" -DisplayValue "Disabled" –NoRestart
    Set-NetAdapterAdvancedProperty Ethernet0 -DisplayName "Large Send Offload V2 (IPv4)" -DisplayValue "Disabled" –NoRestart
    Set-NetAdapterAdvancedProperty Ethernet0 -DisplayName "Large Send Offload V2 (IPv6)" -DisplayValue "Disabled" –NoRestart

3. restart server when convenient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de7f0b7-1c29-6714-51b9-75df6731ce25
* Version Independent ID: c6ada0cd-4fb8-b1eb-db34-206660e33e9f
* Content: [Troubleshooting Microsoft Defender for Identity known issues](https://docs.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues)
* Content Source: [ATPDocs/troubleshooting-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@HenrikBernhard Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
