### ISSUE TITLE
Do not require Kerberos preauthentication

### ISSUE THREAD

**Issue by stephanwaelde** [MicrosoftDocs/ATADocs#458]
The first row in the Remediation table should list "Remove Do not require Kerberos preauthentication" under "Recommended Action". The phrase "Remove Use Kerberos DES encryption types for this account" is for the last row.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade1b68-cd1e-0772-f0ed-f639cbc6bbce
* Version Independent ID: c43b2bee-dce5-4337-3618-5224aa13597e
* Content: [Microsoft Defender for Identity unsecure account attributes assessments](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-unsecure-account-attributes)
* Content Source: [ATPDocs/cas-isp-unsecure-account-attributes.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/cas-isp-unsecure-account-attributes.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@stephanwaelde Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@stephanwaelde Thanks for your feedback. Please can you provide a little more detail on the issue you raised?

**Comment by stephanwaelde** [comment]
Hi Shlomo,

sure. The table in https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-unsecure-account-attributes#remediation has six rows.
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-unsecure-account-attributes#remediation>
Microsoft Defender for Identity unsecure account attributes assessments | Microsoft Docs<https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-unsecure-account-attributes#remediation>
Security assessment: Unsecure account attributes. 10/26/2020; 2 minutes to read; s; m; In this article What are unsecure account attributes? Microsoft Defender for Identity continuously monitors your environment to identify accounts with attribute values that expose a security risk, and reports on these accounts to assist you in protecting your environment.
docs.microsoft.com
[cid:2eba9c4f-7409-479f-aba1-1eb0e26ca14a]

The wording "Remove Use Kerberos DES encryption types for this account" occurs in row 1 and in row 6. It is correct in row 6.



But in row 1 it should be "Remove Do not require Kerberos preauthentication" instead. "Remove Do not require Kerberos preauthentication" is an Unsecured account attributes recommended action, and it fits to the reason given in row 1.


Regards,
Stephan




________________________________

**Comment by shsagir** [comment]
@stephanwaelde Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
