### ISSUE TITLE
RSS provided on "What's new in Microsoft Defender for Identity" don't work

### ISSUE THREAD

**Issue by swolosz** [MicrosoftDocs/ATADocs#460]
I configured the RSS feed in Outlook and in my RSS feed plugin in the browser and it does not have any news. The new MDI sensor release was yesterday and I don't get any feed about it... Could you please fix it?

Regards,
Sebastian Wolosz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8285b5-f6ff-ef1e-fa89-399b54edb185
* Version Independent ID: bccc3696-64a5-73a4-b565-f0e56322d04f
* Content: [What's new in Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/whats-new)
* Content Source: [ATPDocs/whats-new.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/whats-new.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@swolosz Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page with an updated RSS feed. Relevant changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
