### ISSUE TITLE
Bad link in document

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/ATADocs#461]
The ATA Sizing Tool link in the article is broken.  It currently references : https://aka.ms/atasizingtool which is not the correct link to the tool.  Can we please get this updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55eafa55-876f-04e8-d0ce-6deff81e8f40
* Version Independent ID: 131ad34f-9004-761c-87aa-1563841616db
* Content: [Planning your Advanced Threat Analytics deployment](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-capacity-planning)
* Content Source: [ATADocs/ata-capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ata-capacity-planning.md)
* Product: **advanced-threat-analytics**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@tomdan-MSFT Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
