### ISSUE TITLE
ATA - End of Support

### ISSUE THREAD

**Issue by rtlewkowski** [MicrosoftDocs/ATADocs#463]
Since ATA is at the end of support, it should probably be noted on the Docs page.

https://techcommunity.microsoft.com/t5/microsoft-security-and/end-of-mainstream-support-for-advanced-threat-analytics-january/ba-p/1539181

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f1f588-72cb-e671-578d-92c472fbebf4
* Version Independent ID: 18c17328-b24d-8496-4a3a-31f3506c84e1
* Content: [What is Microsoft Advanced Threat Analytics (ATA)?](https://docs.microsoft.com/en-us/advanced-threat-analytics/what-is-ata)
* Content Source: [ATADocs/what-is-ata.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/what-is-ata.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@rtlewkowski Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
