### ISSUE TITLE
Cloud App Security - alerts name/title different from the official documentation

### ISSUE THREAD

**Issue by barberae** [MicrosoftDocs/ATADocs#464]
We are trying to use Demisto (SOAR) in order to automate and track the alerts coming from Cloud App Security. In order to do that we have to map the alert name/title with the right security incident type. We noticed that the alert name/title coming from Cloud App Security, for example "Active Directory attributes Reconnaissance using LDAP" is different from the same reported in the official documentation "Active Directory attributes reconnaissance (LDAP) (external ID 2210)" (https://docs.microsoft.com/en-us/defender-for-identity/reconnaissance-alerts#active-directory-attributes-reconnaissance-ldap-external-id-2210). 
Is it possible to fix the title or create a new page with the complete list of updated alerts name/title?  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52af70b6-86d4-5dd4-0c17-d4e0a5f6e0ed
* Version Independent ID: 63d594b0-4656-1938-98da-da5494321df9
* Content: [Microsoft Defender for Identity reconnaissance phase security alerts](https://docs.microsoft.com/en-us/defender-for-identity/reconnaissance-alerts#active-directory-attributes-reconnaissance-ldap-external-id-2210)
* Content Source: [ATPDocs/reconnaissance-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/reconnaissance-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@barberae Thanks for your query. You can find a mapping to Cloud App Security IDs in [Security alert name mapping and unique external IDs](https://docs.microsoft.com/en-us/defender-for-identity/suspicious-activity-guide?tabs=cloud-app-security). Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

**Comment by barberae** [comment]
@shsagir I already saw that page but there isn't for example neither in "Cloud App Security IDs" tab nor in "External IDs" tab the alert title "Active Directory attributes Reconnaissance using LDAP" that we receive in the JSON object from Cloud App Security endpoint. This is the JSON:

[
    {
        "URL": "https://ynap.portal.cloudappsecurity.com/#/alerts/xxxxxxxxxxxxxxxxxx",
        "_id": "xxxxxxxxxxxxxxxxxxx",
        "contextId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "description": "An actor on xxxxxxxxxxxxxxx sent suspicious LDAP queries, searching for Use Des Key on corp.net-a-porter.com, london.net-a-porter.com, net-a-porter.com and newyork.net-a-porter.com",
        "device": [
            {
                "entityRole": "Source",
                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "label": "xxxxxxxxxxxxxxxxxx",
                "type": "device"
            }
        ],
        "idValue": 15795497,
        "isSystemAlert": false,
        "is_open": true,
        "policyRule": [
            {
                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "label": "**Active Directory attributes Reconnaissance using LDAP**",
                "policyType": "ANOMALY_DETECTION",
                "type": "policyRule"
            }
        ],
        "service": [
            {
                "id": 20940,
                "label": "Active Directory",
                "type": "service"
            }
        ],
        "severityValue": 1,
        "statusValue": 0,
        "stories": [
            0
        ],
        "threatScore": 0,
        "timestamp": 1613639895229,
        "title": "**Active Directory attributes Reconnaissance using LDAP**"
    }
]

Reading your documentation's link we don't expect to receive this alert but the "Active Directory attributes reconnaissance (LDAP)". I hope now the issue is more clear than before.
