### ISSUE TITLE
Export Issue : Not All fields are populated in the MCAS Identity Security Posture

### ISSUE THREAD

**Issue by arvinder-dhar** [MicrosoftDocs/ATADocs#465]
Hello Team,

We Sync multiple on-premises Active Directory Domain to Azure. When Navigating portal.cloudappsecurity.com --> Investigate --> Identity Security Posture and trying to export report e.g. Unsecure Kerberos delegation , Domain Column is not been exported.

I tried to look up several ways to export this MCAS API, Powershell but all in vain.
Can you please provide any guidance in how I can go and achieve this.

Kindly note that we need this data badly to improve our Organization's overall Security Posture.
Refer attached images (Exported report and MCAS UI)

Thank You
![Exported_Report](https://user-images.githubusercontent.com/30565401/110288831-930e0880-800e-11eb-8619-43dcb89ac363.JPG)
![MCAS_UI](https://user-images.githubusercontent.com/30565401/110288854-9a351680-800e-11eb-9127-afa549c61c02.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ac1c39-fce7-aa71-b56b-385c2b72ca63
* Version Independent ID: 6813852c-5cbc-9843-fd43-53972d120ae5
* Content: [Microsoft Defender for Identity's identity security posture assessments](https://docs.microsoft.com/en-us/defender-for-identity/isp-overview)
* Content Source: [ATPDocs/isp-overview.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/isp-overview.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@arvinder-dhar Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@arvinder-dhar We researched your issue and determined it's a bug. An internal ticket has been raised.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
