### ISSUE TITLE
Major updates notification

### ISSUE THREAD

**Issue by swolosz** [MicrosoftDocs/ATADocs#466]
I'm missing information about the notification when the major release needs a DC reboot. There will be a mail notification or information on the MDI console about pending reboot? If DC pending reboot after the major update that mean the MDI sensor service does not work?
Could you add the screenshots how the notification could look like?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 795cece7-503b-064a-fd1a-cf598fe4cf89
* Version Independent ID: b731596e-1cbf-42ff-0bcd-2a27cc362985
* Content: [Update your Microsoft Defender for Identity sensors](https://docs.microsoft.com/en-us/defender-for-identity/sensor-update)
* Content Source: [ATPDocs/sensor-update.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/sensor-update.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@swolosz Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@swolosz Thanks so much for taking the time to leave us your comment on our documentation. We acknowledge the reboot concerns and are working to improve the technology, and we're working to update the page. Changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
