### ISSUE TITLE
Duplicate pages

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#467]
There are 2 "Configure Detection Exclusion" pages listed in the left side navigation. Please remove the duplicate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab71dff0-18cc-3267-52ab-66f01986edb0
* Version Independent ID: 2b6fe284-8481-ebb2-8d2e-4af0a91d968b
* Content: [Microsoft Defender for Identity configure detection exclusions](https://docs.microsoft.com/en-us/defender-for-identity/configure-detection-exclusions)
* Content Source: [ATPDocs/configure-detection-exclusions.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-detection-exclusions.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your helpful comment. The duplicate entry has been removed.
