### ISSUE TITLE
Defender for Identity Architecture architecture page: no mention of standalone sensor

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/ATADocs#469]
Seems as if the architecture page for Defender for Identity should have some mention of the standalone sensor as an option for an implementation of Defender for Identity. It is mentioned on the prerequisites page. When I was reading this architecture page, I questioned whether the standalone sensor option was still available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d74f052e-fd05-b96e-fb2a-0f67b7a6d4da
* Version Independent ID: 80591357-4e2e-be6c-e31f-c92b2d5215b0
* Content: [Microsoft Defender for Identity architecture](https://docs.microsoft.com/en-us/defender-for-identity/architecture)
* Content Source: [ATPDocs/architecture.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/architecture.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We will investigate the issue and get back to you.

**Comment by dcurwin** [comment]
The standalone sensor is still available, but is not fully recommended, which is why you don't see it in the Architecture page. We have a note mentioning this in the Prerequisites page:

> Defender for Identity standalone sensors do not support the collection of Event Tracing for Windows (ETW) log entries that provide the data for multiple detections. For full coverage of your environment, we recommend deploying the Defender for Identity sensor.

Thanks again for your comment.
