### ISSUE TITLE
ATA Support

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/ATADocs#470]
[Enter feedback here]

You should update the end of support date for the ATA version:
https://techcommunity.microsoft.com/t5/security-compliance-identity/end-of-mainstream-support-for-advanced-threat-analytics-january/ba-p/1539181

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d587c5ad-4a52-c244-5142-f780cc3a2c96
* Version Independent ID: e34d972f-ee87-9845-1165-76fdaf956c2c
* Content: [Advanced Threat Analytics versions](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-versions)
* Content Source: [ATADocs/ATA-versions.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/ATA-versions.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your comment. We've updated the table.
