### ISSUE TITLE
Provide more info about ADFS

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#471]
While going through the steps, all of sudden it states "if installing on an AD FS Server", this configuation option was not previously mentioned. Please provide more explanation about monitoring AD FS needs to be planned for and included in the process. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f643c8da-665d-75b5-0233-d849394aef77
* Version Independent ID: db3bb712-25d1-cfe9-fe90-d65400921484
* Content: [Install Microsoft Defender for Identity sensor quickstart](https://docs.microsoft.com/en-us/defender-for-identity/install-step4)
* Content Source: [ATPDocs/install-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-step4.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your request. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Sorry I didn't write this earlier. We updated the document a few weeks ago. Thanks for your contribution.
