### ISSUE TITLE
Incorrect Guidance on "Security assessment: Weak cipher usage"

### ISSUE THREAD

**Issue by NickGuyver** [MicrosoftDocs/ATADocs#472]
The remediation guidance is wrong, it has nothing to do with Kerberos ciphers. The correct way to remediate this is to modify the msDS-SupportedEncryptionTypes AD attribute on the applicable devices/accounts and to remove the weak ciphers based on these bit flags (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-kile/6cfc7b50-11ed-4b4d-846d-6f08f0812919). After ensuring that devices/accounts are no longer leveraging the weak ciphers then you would modify the domain controller security policy to drop the weak ciphers from the "Network security: Configure encryption types allowed for Kerberos" (https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70cfa5f8-33eb-ac55-15fa-2e1925d641db
* Version Independent ID: 1360939f-6120-7a26-47bf-11456d8e16c7
* Content: [Microsoft Defender for Identity weak cipher identity security posture assessment report](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-weak-cipher)
* Content Source: [ATPDocs/cas-isp-weak-cipher.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/cas-isp-weak-cipher.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your comment. We've updated the page.
