### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#474]
we have been troubleshooting this and finally figured out that we did not have KDSRootKey in our domain. Please add something to these instructions to clearly identify this requirement so that others don't waste as much time as we have. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e36ca9c-b3b9-27e0-508b-13041113d7c7
* Version Independent ID: d52d7291-3bf8-d209-e278-5259aa750b71
* Content: [Connect Microsoft Defender for Identity to Active Directory quickstart](https://docs.microsoft.com/en-us/defender-for-identity/install-step2)
* Content Source: [ATPDocs/install-step2.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-step2.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DeanGross  - Thank you again for your comment. I'm sorry about your frustrating experience.

I did check, and in the article, we do provide this link: Create a [gMSA account](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/getting-started-with-group-managed-service-accounts#BKMK_CreateGMSA).

On that page, the requirement to create a master root key for Active Directory and instructions on how to do so is mentioned.

But to make it more clear, I will add a note suggesting to review the prerequisites for creating the GSMA account. 

Thanks again for your contribution.
