### ISSUE TITLE
Preview alerts

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#475]
Why is the alert for external ID 2406 in Preview? what does it mean when an alert is not GA?

  ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7137cd0-1ce4-bd31-4bcb-30f2b30d2959
* Version Independent ID: d0dd1602-4625-78da-1a21-211d85a2baab
* Content: [Microsoft Defender for Identity lateral movement security alerts](https://docs.microsoft.com/en-us/defender-for-identity/lateral-movement-alerts)
* Content Source: [ATPDocs/lateral-movement-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/lateral-movement-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DeanGross - The alert is no longer labeled as preview. 

I'm closing this issue, but if you have further questions, feel free to ask.
