### ISSUE TITLE
Where is the script?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#476]
The page states "It is important to run the Defender for Identity auditing script ", where is this script located? please add a link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813a14c6-6b22-95e6-43c6-a8f29425f1b4
* Version Independent ID: b301043f-fe9e-2cff-3f33-d1a69ef38055
* Content: [Install Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/configure-event-collection)
* Content Source: [ATPDocs/configure-event-collection.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you soon.

**Comment by DeanGross** [comment]
Ok thanks. I am curious what did it do? Is there a replacement?

**Comment by dcurwin** [comment]
It did what the documentation previously said it did, but since it wasn't updated, it was no longer performing that task. There is some discussion about a replacement - if and when that happens, we'll update the documentation.
