### ISSUE TITLE
Next steps - confusing

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#477]
The Next Steps link points to information about planning capacity which seems out of order, that type of activity should have been done before the installation. I would expect the next step to be something about configuring the sensor settings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f643c8da-665d-75b5-0233-d849394aef77
* Version Independent ID: db3bb712-25d1-cfe9-fe90-d65400921484
* Content: [Install Microsoft Defender for Identity sensor quickstart](https://docs.microsoft.com/en-us/defender-for-identity/install-step4)
* Content Source: [ATPDocs/install-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-step4.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you soon.

**Comment by dcurwin** [comment]
Thank you for the suggestion! We've replaced the Next Steps.

**Comment by DeanGross** [comment]
wow, this is the fastest response I have ever had to one of my comments :)

**Comment by dcurwin** [comment]
We're always happy to respond quickly :)
