### ISSUE TITLE
Standalone Sensor Supported OS List

### ISSUE THREAD

**Issue by bekirdur** [MicrosoftDocs/ATADocs#480]
MDI Standalone Sensor Supported OS List is not as clear as the MDI Sensor Supported OS list. Just like MDI Sensor, I believe MDI standalone sensor also supports Server 2019, but it looks like it is not mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://docs.microsoft.com/en-us/defender-for-identity/prerequisites#azure-atp-standalone-sensor-requirements)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@bekirdur - Sorry for the delay in our response. The product group has confirmed that Server 2019 is supported, and the documentation has been updated.
