### ISSUE TITLE
Number of supported Directory Service account

### ISSUE THREAD

**Issue by bekirdur** [MicrosoftDocs/ATADocs#481]
Number of supported Directory Service account is increased from 10 to 30 with release number 2.1.47
https://docs.microsoft.com/en-us/defender-for-identity/whats-new#defender-for-identity-release-2148

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a307c34-87b2-4982-ee89-1ffb56996060
* Version Independent ID: ded9e856-0cd7-79d0-9f9c-e66adca87863
* Content: [Microsoft Defender for Identity frequently asked questions](https://docs.microsoft.com/en-us/defender-for-identity/technical-faq)
* Content Source: [ATPDocs/technical-faq.yml](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/technical-faq.yml)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@bekirdur  - Thank you for opening the issue. Could you clarify your question?

**Comment by bekirdur** [comment]
No questions. Just offering an update for the Directory Service account limit, stated as 10 in the doc. However, it is raised to 30 by engineering. Thanks.

**Comment by dcurwin** [comment]
Ok, thanks for the suggestion. The page has been updated.
