### ISSUE TITLE
Documentation regarding specifying the service account

### ISSUE THREAD

**Issue by leewsullivan** [MicrosoftDocs/ATADocs#482]
The documentation does not mention the requirement of appending $ to the username when specifying a gMSA account. Also, the gMSA account needs to be able to logon as a service on each Domain Controller.

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@leewsullivan - You didn't mention which page you would like to update. Could you please inform me here?

**Comment by leewsullivan** [comment]
Sure - https://docs.microsoft.com/en-us/defender-for-identity/install-step2

I can provide a screenshot if needed of the account config page

**Comment by dcurwin** [comment]
@leewsullivan - Sure, that would be great, thanks.

**Comment by leewsullivan** [comment]
The config is here - https://ibb.co/23ctJHD

Note the requirement of appending $ to the username when specifying a gMSA account.

**Comment by dcurwin** [comment]
@leewsullivan  - Thanks again for your feedback. 

I've investigated with the product team, and both configurations of the username work: with and without the $.

Also, logon on as a service is not required, unless there have been customizations made to the policy in your organization. In those scenarios, it may be necessary to grant logon as a service to that account.

We appreciate your contributions to Docs!
