### ISSUE TITLE
Sentence requires clarification

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/ATADocs#486]
Howdy - can you please fix up this sentence? Not sure what it really means :)
"Defender for Identity data cannot be moved once your Defender for Identity instance is created to a different data center"

Reading the previous sentence it appears that you can't choose where the service is stood up - it just co-locates with your AAD tenant - so how can it be "created to a different data center" at all??

Cheers!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a307c34-87b2-4982-ee89-1ffb56996060
* Version Independent ID: ded9e856-0cd7-79d0-9f9c-e66adca87863
* Content: [Microsoft Defender for Identity frequently asked questions](https://docs.microsoft.com/en-us/defender-for-identity/technical-faq)
* Content Source: [ATPDocs/technical-faq.yml](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/technical-faq.yml)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@PeteHaigh-MSFT - Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for the suggestion. I've reworded the sentence to make it more clear.

**Comment by PeteHaigh-MSFT** [comment]
Thanks again!
