### ISSUE TITLE
Consolidate service/data location please - for simplicity and consistency

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/ATADocs#487]
Hi there

Could you please consolidate the data location info onto the "Defender for Identity data security and privacy" page to help everyone who's working through assurance processes for our security tools?

1. Please move /copy this from https://docs.microsoft.com/en-us/defender-for-identity/install-step1 "Currently, Defender for Identity data centers are deployed in Europe, UK, North America/Central America/Caribbean and Asia. Your instance is created automatically in the data center that is geographically closest to your Azure Active Directory (Azure AD). Once created, Defender for Identity instances aren't movable."
2. Please move the 3 security/privacy questions from the FAQ page to this page
3. Please get MDI added to this page https://www.microsoft.com/en-nz/trust-center/privacy/data-location -conspicuous by its absence...

That would be a big help :)

Cheers, Peter from NZ
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e5897-d642-c71a-7212-0f7cca46c8b9
* Version Independent ID: 1b66013a-33ed-fe34-0ab6-241050ef1240
* Content: [Microsoft Defender for Identity personal data policy](https://docs.microsoft.com/en-us/defender-for-identity/privacy-compliance)
* Content Source: [ATPDocs/privacy-compliance.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/privacy-compliance.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
I've updated the **Microsoft Defender for Identity personal data policy** page.  

Regarding the https://www.microsoft.com/en-us/trust-center/privacy/data-location page, I don't maintain that, but I've requested that the link to MDI be added.

**Comment by PeteHaigh-MSFT** [comment]
Cheers! 🙏

Pete from NZ

Peter Haigh - Technology Strategist, NZ Public Sector Team
Mobile: +64 27 2235329 | ***@***.******@***.***>
