### ISSUE TITLE
ATT&CK ID's to include

### ISSUE THREAD

**Issue by rubinatorz** [MicrosoftDocs/ATADocs#488]
Hi there,

I have some proposals of ATT&CK ID's that can be mapped to some rules in MDI:

- Suspected AS-REP Roasting attack (external ID 2412) -> can be mapped to T1558.004 [Steal or Forge Kerberos Tickets: AS-REP Roasting](https://attack.mitre.org/techniques/T1558/004/)
- Suspected Kerberos SPN exposure (external ID 2410) -> seems to me that's it's part of T1558.003 [Steal or Forge Kerberos Tickets: Kerberoasting](https://attack.mitre.org/techniques/T1558/003/)

Regards,
Ruben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9bf93d-2f09-90ca-5feb-4106a4f8abb2
* Version Independent ID: e03df8b6-624b-30a8-2502-6be59ff98606
* Content: [Microsoft Defender for Identity compromised credentials phase security alerts](https://docs.microsoft.com/en-us/defender-for-identity/compromised-credentials-alerts#suspected-as-rep-roasting-attack-external-id-2412)
* Content Source: [ATPDocs/compromised-credentials-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/compromised-credentials-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@rubinatorz - Thank you for your feedback. We've updated the documentation with additional ATT&CK IDs.
