### ISSUE TITLE
Pruning printers

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/ATADocs#489]
This document contains this line:

     To address the issue, you should consider periodically pruning stale print queue objects, either manually or using an automation script.

I feel without any guide or reference at all to either of these, the tradeoff is substantively more difficult. I'd greatly appreciate even a hint about cleaning these up, either manually or automatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d73e6a7-9223-20f8-1775-6e9a9cfb17ea
* Version Independent ID: aade81d9-8031-27c1-2915-44ea068e3403
* Content: [Microsoft Defender for Identity Print spooler identity security posture assessments](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-print-spooler)
* Content Source: [ATPDocs/cas-isp-print-spooler.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/cas-isp-print-spooler.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@technion  - Thank you again for your comment. We realize this is a complicated issue. Unfortunately, we don't have a script available for pruning printer objects. To avoid confusion, we've removed that phrase from the document.
