### ISSUE TITLE
Many Errors in these docs

### ISSUE THREAD

**Issue by danielmarker** [MicrosoftDocs/ATADocs#490]
- ADFS is running and working successfully on Windows Server 2012 R2
- Is there an issue in installing the ATP Sensor on the ADFS Primary node - error of "OS Not Supported" - but secondary node with exactly the same setup worked?!
- GMSA Account needs to be in the Domain Users Group (which allows Access across the Network to other computers)

Still finding more issues as we go - will update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://docs.microsoft.com/en-us/defender-for-identity/prerequisites#ports)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by danielmarker** [comment]
Further - the GMSA requires logon as a service and Logon as batch to run.

**Comment by dcurwin** [comment]
Thanks for your comments. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@danielmarker - I researched your points, and this is what I heard from the product team.

>ADFS is running and working successfully on Windows Server 2012 R2

Even if it is running, does not mean it is supported. 

> Is there an issue in installing the ATP Sensor on the ADFS Primary node - error of "OS Not Supported" - but secondary node with exactly the same setup worked?!

There should be no difference regarding OS version support between the primary and secondary node of the AD FS.

> GMSA Account needs to be in the Domain Users Group (which allows Access across the Network to other computers)

This is not a requirement. 

> the GMSA requires logon as a service and Logon as batch to run.

This is not needed by default, unless a policy was modified requiring it. 


In light of the above, I won't be modifying the documentation. However, if the product is not performing for you as documented, we recommend you open a support case.


Thanks for reaching out!
