### ISSUE TITLE
Broken link in Document

### ISSUE THREAD

**Issue by CarlH2** [MicrosoftDocs/ATADocs#491]
Link broken under Heading "Deploy Defender for Identity"

**Try Defender for Identity (part of EMS E5) The trial is valid for 90 days.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed5b3f3-a6ea-f89c-2170-620b9c005bc2
* Version Independent ID: 188d24d6-fe0a-04f7-67b7-03cef5b78407
* Content: [List of helpful resources for Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/resources)
* Content Source: [ATPDocs/resources.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/resources.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for the comment. We've updated the link.
