### ISSUE TITLE
Incorrect Command

### ISSUE THREAD

**Issue by over2under3** [MicrosoftDocs/ATADocs#492]
[Enter feedback here]

Near the middle of the page you want the customer to run the following command:
**Get-NetLocalGroup <Admin PC IP Address>**

This is not correct. The correct command to get the results from the page is Get-**NetLocalGroupMember**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfe698-05a4-8d4c-75b8-024ab912e18c
* Version Independent ID: 4d58c76d-b7b5-9900-9c14-557f892cc54e
* Content: [Microsoft Defender for Identity Security Alert Lateral Movement Playbook](https://docs.microsoft.com/en-us/defender-for-identity/playbook-lateral-movement)
* Content Source: [ATPDocs/playbook-lateral-movement.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/playbook-lateral-movement.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment, We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@over2under3  - Thank you again for your feedback. PowerSploit is a third party tool, and as such, we do not take responsibility for the changes that the tool undergoes. We've updated the disclaimer in our documentation to indicate that. 
Thanks.
