### ISSUE TITLE
Incorrect URL reference

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/ATADocs#493]
[Enter feedback here]
This section:
Optional Honeytoken: A user account of a user who has no network activities. This account is configured as a Defender for Identity Honeytoken user. For more information about using Honeytokens, see Configure exclusions and Honeytoken user.

Includes a URL to the ' exclusions' page, but honeytokens aren't explained there. they are explained in this article: 
https://docs.microsoft.com/en-us/defender-for-identity/manage-sensitive-honeytoken-accounts
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://docs.microsoft.com/en-us/defender-for-identity/prerequisites)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your suggestion. We've updated the link on the page.
