### ISSUE TITLE
SAMR Policy Edit - Local or domain policy?

### ISSUE THREAD

**Issue by jhaprakash26** [MicrosoftDocs/ATADocs#495]
It isn't clear to me whether to edit local policy/domain policy or the domain controller policy for SAMR. Kindly elaborate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b9eb03-cb5e-ab2b-c088-2badd87cc682
* Version Independent ID: ab8cbfa9-7f3f-e635-f977-0652c8511397
* Content: [Microsoft Defender for Identity security alert lab setup tutorial](https://docs.microsoft.com/en-us/defender-for-identity/playbook-setup-lab)
* Content Source: [ATPDocs/playbook-setup-lab.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/playbook-setup-lab.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
