### ISSUE TITLE
Steps for lateral movement playbook missing

### ISSUE THREAD

**Issue by billypms** [MicrosoftDocs/ATADocs#497]
Security alert lab 3 - Lateral movement playbook - Additional lateral move

The steps for "Additional lateral move" are not complete. The command in step 1 pulls group information but the example output shows user data. I believe there should be an additional PowerShell command from the PowerSploit module : "Get-NetLocalGroupMember 10.1.0.6 -GroupName Administrators"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfe698-05a4-8d4c-75b8-024ab912e18c
* Version Independent ID: 4d58c76d-b7b5-9900-9c14-557f892cc54e
* Content: [Microsoft Defender for Identity Security Alert Lateral Movement Playbook](https://docs.microsoft.com/en-us/defender-for-identity/playbook-lateral-movement)
* Content Source: [ATPDocs/playbook-lateral-movement.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/playbook-lateral-movement.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@billypms  - Thanks for your contribution. After consulting with the product group, we've updated the page according to your suggestion.
