### ISSUE TITLE
Missing word in line 

### ISSUE THREAD

**Issue by Surakshit007** [MicrosoftDocs/ATADocs#498]
I believe the highlighted heading is incorrect. I  think it is missing the word "analyze"
[https://docs.microsoft.com/en-us/defender-for-identity/what-is](url)

![pic](https://user-images.githubusercontent.com/81862027/132262403-367cffaf-d612-4842-bb86-2bd58047bb64.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8df167b-3d6a-ebd1-4401-4596565b9238
* Version Independent ID: 56c40693-376f-4a86-ca85-5ecfd9cb3558
* Content: [What is Microsoft Defender for Identity?](https://docs.microsoft.com/en-us/defender-for-identity/what-is)
* Content Source: [ATPDocs/what-is.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/what-is.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your comment. We've updated the heading accordingly.
