### ISSUE TITLE
Defender For Identity Alert IDs

### ISSUE THREAD

**Issue by BALROG3** [MicrosoftDocs/ATADocs#499]
Please can you update this page with the new detections (last update Oct 2020) including their External IDs and Cloud App Security IDs?

https://docs.microsoft.com/en-us/defender-for-identity/suspicious-activity-guide?tabs=cloud-app-security#security-alert-name-mapping-and-unique-external-ids

For example I understand there is now a detection for PetitPotam which is External ID 2416 (not sure what the Cloud App Security ID is). Many of us rely on these IDs to trigger alerts in our SIEM or XDR. We can't do this if we don't know what the IDs are. I suppose that External IDs 2412-2416 need to be added to this documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac27fc05-6fd3-d558-7772-16bf0b9873d2
* Version Independent ID: 8b9f6583-95c2-9948-7bee-428fbd8e1629
* Content: [Microsoft Defender for Identity security alert guide](https://docs.microsoft.com/en-us/defender-for-identity/suspicious-activity-guide?tabs=cloud-app-security#security-alert-name-mapping-and-unique-external-ids)
* Content Source: [ATPDocs/suspicious-activity-guide.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/suspicious-activity-guide.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your feedback. We've updated the tables with the new alerts.

**Comment by BALROG3** [comment]
Perfect - thanks!
