### ISSUE TITLE
Object Auditing of 4662 Events - More Explanation

### ISSUE THREAD

**Issue by i-am-ari** [MicrosoftDocs/ATADocs#504]
Hi There,

This is going to sound silly, but I got stuck on Step 8 of Object Auditing for the collection of 4662 Events.

At Step 8, the instructions detail what changes to make under the Permissions area, but it does not specify whether any changes to the Properties section should be made.

If I make the permission changes (as shown on screenshot on the webpage), make no changes to the Properties area and then hit okay, and then reopen the view the audit entry again, I note that the "Read all Properties" attribute under the Permissions area is checked. 

This led me to assume that maybe I should be "unchecking" all the Read attributes in the Properties section, but the instructions do not say to do this. If I uncheck them, will the logs not be collected properly? If I leave the Properties section as it is by default, am I unintentionally creating a security hole? 

I am stuck in a loop of uncertainty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@i-am-ari @schottky81  Thanks again for your comments. We've updated the documentation to say:

Under Permissions, scroll down and select Clear all. Scroll up and select Full Control. All the permissions will be selected. Then uncheck the List contents, Read permissions, and Read all properties permissions. Then select OK. This will set all the Properties settings to Write. Now when triggered, all relevant changes to directory services will appear as 4662 events.

**Comment by ryanhelmer** [comment]
@dcurwin @i-am-ari @schottky81 I also have this exact question. Specifically regarding this: "Then uncheck the List contents, Read permissions, and _Read all properties_ permissions."

When following these steps exactly, _Read all properties_ is already unchecked ("Clear all" clears everything). If you then go back in to Edit, even though all the Properties section was unchecked, it now shows ALL the Properties as checked--both read and write. If _Read all properties_ is then unchecked, it unchecks _only_ that checkbox--not the rest of the Read properties. If OK is then clicked, it throws a warning about a great number of auditing entries being adding to the access control list. Unchecking all the Read entries manually is extremely tedious and somewhat error-prone, as they are somewhat scattershot throughout the many pages of checkboxes. 

This can't be right. Surely I'm missing something? 

Thank you!

**Comment by dcurwin** [comment]
@ryanhelmer 

Thank you for your comment. We'll investigate and get back to you.

**Comment by ryanhelmer** [comment]
@dcurwin Thank you very much, David! I really appreciate it.

**Comment by dcurwin** [comment]
@ContreBombarde  - There is no need to manually select each write property and we removed the misleading (second) screenshot to make this more clear.
