### ISSUE TITLE
Include the default exclusions for the detection rules

### ISSUE THREAD

**Issue by brportela** [MicrosoftDocs/ATADocs#505]
[Enter feedback here]
Some rules have default exclusions configured by default like the DNS: https://techcommunity.microsoft.com/t5/microsoft-defender-for-identity/default-exclusions-in-suspicious-communication-over-dns-sa/m-p/285348

Include in the documentation which rules have default exclusions shipped with the product

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab71dff0-18cc-3267-52ab-66f01986edb0
* Version Independent ID: 2b6fe284-8481-ebb2-8d2e-4af0a91d968b
* Content: [Microsoft Defender for Identity configure detection exclusions](https://docs.microsoft.com/en-us/defender-for-identity/configure-detection-exclusions)
* Content Source: [ATPDocs/configure-detection-exclusions.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-detection-exclusions.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks again for your suggestion. We've updated the documentation to mention those default exclusions. It should be visible shortly.
