### ISSUE TITLE
Guidance to leverage MFA, MCAS and AIP for privileged on-prem accounts is not applicable unless the account is synced to AAD

### ISSUE THREAD

**Issue by jkdevore** [MicrosoftDocs/ATADocs#506]
[Enter feedback here]

"enable MFA or, if you've configured the relevant high-risk user policies in Azure Active Directory Identity Protection, you can use the Confirm user compromised action in the Cloud App Security portal."

The above mitigation is mentioned 7 times but it really is not applicable for on-prem privileged service accounts which are primary target of adversaries.  Our guidance discourages syncing privileged on-prem AD accounts to Azure AD so AIP would not be an option for those accounts nor would Cloud App Security.  Additionally enforcing MFA for network, batch, and service logon type is not feasible regardless if the MFA solution is 1st or 3rd party.  As a result it appears to the reader that the writer of the guidance does not understand the different between on-prem legacy auth security controls and the modern auth controls available from Azure AD.

Feel free to contact me at jdevore@microsoft.com if you want to discuss how to best re-phrase the guidance.  As a Sr Customer Engineer I work with MDI customers on a weekly basis and understand how they are confused by the current wording.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52af70b6-86d4-5dd4-0c17-d4e0a5f6e0ed
* Version Independent ID: 63d594b0-4656-1938-98da-da5494321df9
* Content: [Microsoft Defender for Identity reconnaissance phase security alerts](https://docs.microsoft.com/en-us/defender-for-identity/reconnaissance-alerts)
* Content Source: [ATPDocs/reconnaissance-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/reconnaissance-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@jkdevore - The product group has investigated this issue. Their response to me is that they've added it to the product Wishlist for identity based assessments and will take it under consideration.

Thanks again for your contribution.
