### ISSUE TITLE
T-BP instead of B-TP

### ISSUE THREAD

**Issue by sslawter** [MicrosoftDocs/ATADocs#507]
In the Suspected Golden Ticket usage (encryption downgrade) (external ID 2009) section, there is a reference to T-BP that I think should be B-TP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70225acf-8584-2d88-755a-dde2fbad5b74
* Version Independent ID: 5d6a4bff-44f1-1fb0-fca7-59f406e3b8be
* Content: [Microsoft Defender for Identity domain dominance security alerts](https://docs.microsoft.com/en-us/defender-for-identity/domain-dominance-alerts#suspected-golden-ticket-usage-encryption-downgrade-external-id-2009)
* Content Source: [ATPDocs/domain-dominance-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/domain-dominance-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@sslawter  - Thank you for catching that. We've corrected the typo - it should be visible shortly.
