### ISSUE TITLE
Windows Server 2022 support

### ISSUE THREAD

**Issue by baf** [MicrosoftDocs/ATADocs#508]
Is the Defender for Identity sensor officially supported on Server 2022? If so, the documentation should be updated to reflect that.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://docs.microsoft.com/en-us/defender-for-identity/prerequisites)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@baf  - After checking with the product group, I was informed that Server 2022 is not supported yet. When it is, we will update the documentation.

Thanks for your question!

**Comment by baf** [comment]
@dcurwin Thanks for checking into it but sorry to hear that. I hope it will be available in the near future. Please provide my feedback to the PG: these inconsistencies between Microsoft technologies make it harder to adopt the latest and greatest and/or best practice solutions. Another example is the inability to use the Azure AD Connect Health for AD DS agent on Server Core - we'd love to use Core for our DCs but can't because Microsoft's own health monitoring solution doesn't support it.

**Comment by dcurwin** [comment]
@baf  - Thanks for the feedback. I'll let them know.
