### ISSUE TITLE
Comparison to AAD Legacy Protocols Workbook

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#509]
Please add some information about how this compares to the Legacy Protocols workbook in AAD and a link to that documentation. Does it matter which one we use? when should we use each?
TIA
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51df47d3-d163-5337-f46b-b5ab1681839b
* Version Independent ID: 4c6e3f7b-1fb3-e20b-079d-ac41973bf1a4
* Content: [Microsoft Defender for Identity legacy protocols identity security posture assessment](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-legacy-protocols)
* Content Source: [ATPDocs/cas-isp-legacy-protocols.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/cas-isp-legacy-protocols.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DeanGross  - Thanks again for your contribution. We added a note saying:

`This assessment currently focuses on on-premises Active Directory legacy protocols. For information about legacy protocols in Azure Active Directory, see [How to block legacy authentication to Azure Active Directory with Conditional Access](/azure/active-directory/conditional-access/block-legacy-authentication).`
