### ISSUE TITLE
Minimum Storage Size for Defender for Identity sensor 

### ISSUE THREAD

**Issue by naotoinamori** [MicrosoftDocs/ATADocs#510]
[Enter feedback here]
According to the MDI this DOCS, "A minimum of **5 GB** of disk space is required and 10 GB is recommended. This includes space needed for the Defender for Identity binaries, Defender for Identity logs, and performance logs." but the other MDI DOCS page also says "A minimum of **6 GB** of hard drive space is required, 10 GB is recommended, including space needed for the Defender for Identity binaries and logs." (URL: https://docs.microsoft.com/en-us/defender-for-identity/capacity-planning#defender-for-identity-sensor-sizing)

Which minimum storage sizes are accurate? thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://docs.microsoft.com/en-us/defender-for-identity/prerequisites#general)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@naotoinamori - Thanks for your feedback. We've updated the docs to say that the requirement is 6 GB.
