### ISSUE TITLE
gMSA account rights documented

### ISSUE THREAD

**Issue by KevIvers** [MicrosoftDocs/ATADocs#511]
I setup the sensor service to run under a gMSA account.
In the first instance the service wouldn't start and threw an exception in the logs that alluded to service not having access to write to the performance logs.

I added the gMSA account to the Performance Monitor Users groups and the service started, but it was still throwing errors in the logs relating to access to WMI.

I subsequently added gMSA account to Performance Log Users and restarted the service. 

No more access errors were logged.

This doc( or any other I could find) does not mention the fact that the above memberships are required for the sensor to run.

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@KevIvers  - The product team has looked into your issue, and this is unexpected behavior. If you would like to investigate what might be causing it in your environment, we recommend opening a support case.

Thanks again for your question.
