### ISSUE TITLE
Kerberoasting vs. Golden Ticket

### ISSUE THREAD

**Issue by TareqAlKhatib** [MicrosoftDocs/ATADocs#512]
Hey team,

I might be misreading this, but the following sounds a lot more like Kerberoasting detection than Golden Ticket:
https://docs.microsoft.com/en-us/defender-for-identity/domain-dominance-alerts#suspected-golden-ticket-usage-encryption-downgrade-external-id-2009

The giveaway line is this one:

> "In a Golden Ticket alert, the encryption method of the TGT field of TGS_REQ (service request) message from the source computer was detected as downgraded compared to the previously learned behavior."

which reads similar to this line from the MITRE ATT&CK technique for [Kerberoasting](https://attack.mitre.org/techniques/T1558/003/):

> "Adversaries possessing a valid Kerberos ticket-granting ticket (TGT) may request one or more Kerberos ticket-granting service (TGS) service tickets for any SPN from a domain controller (DC). Portions of these tickets may be encrypted with the RC4 algorithm, meaning the Kerberos 5 TGS-REP etype 23 hash of the service account associated with the SPN is used as the private key and is thus vulnerable to offline Brute Force attacks that may expose plaintext credentials."

Is this correct or am I missing something?

Tareq

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by TareqAlKhatib** [comment]
Hello,

Just checking if there was any update on this one? I need clarification on what the rule is doing so we can write Playbooks for it.

Tareq

**Comment by dcurwin** [comment]
Still investigating.

**Comment by TareqAlKhatib** [comment]
Hello,

I don't suppose there are any updates on this?

Tareq

**Comment by dcurwin** [comment]
@TareqAlKhatib -  Sorry for the delay. I was able to get this response from the product group:

> I can see the confusion -- The TGS request comes without valid TGT, meaning it was signed by the attacker and not the KDC, and this is an indication he has KRBTGT to create his own TGT.
> 
> Once attacker has KRBTGT he has no reason to create tickets for offline bruteforce, like in Kerberoasting, but for lateral movement. And this is what we trigger. We trigger a flavor of golden ticket.

In light of this, the documentation won't be updated. Thanks again for your question.
