### ISSUE TITLE
Prerequisites section - ADFS/SQL

### ISSUE THREAD

**Issue by Dusted1969** [MicrosoftDocs/ATADocs#513]
[Enter feedback here]
Ref: prerequisites and ADFS/SQL
Is there clarification needed here?  This references SQL however its possible to use WID for ADFS - does this requirement still apply in that case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f643c8da-665d-75b5-0233-d849394aef77
* Version Independent ID: db3bb712-25d1-cfe9-fe90-d65400921484
* Content: [Install Microsoft Defender for Identity sensor quickstart](https://docs.microsoft.com/en-us/defender-for-identity/install-step4)
* Content Source: [ATPDocs/install-step4.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-step4.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@Dusted1969  - Thanks again for your question. We've updated the page with instructions on how to give the sensor access to WID for ADFS.

https://docs.microsoft.com/en-us/defender-for-identity/technical-faq#how-do-i-grant-access-to-the-ad-fs-database-via-tsql-or-powershell
