### ISSUE TITLE
SMB Session Enumeration - issues

### ISSUE THREAD

**Issue by szymonslipek** [MicrosoftDocs/ATADocs#515]
Hi there,

Any idea why I do get "Error: NetSessionEnum (5) Access is denied." when trying Netsess my DC from victim machine?
Windows Server 2019 Datacenter Evaluation, Build 17763.rs5_release.180914-1434, setup just for Defender for Identity demo purposes, no customisation. 
Can it be, that Windows Server 2012 R2 is a must here?
Any advice, what I may switch in order to successfully simulate behaviour?
Defender for Identity captures my try, however its failed - nothing exposed.

Kind regards
Szymon
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e25c94-6630-21d7-f39d-0d8684779ba0
* Version Independent ID: 05bbc224-6c7d-3166-9f10-b798b044be6d
* Content: [Microsoft Defender for Identity Reconnaissance playbook tutorial](https://docs.microsoft.com/en-us/defender-for-identity/playbook-reconnaissance)
* Content Source: [ATPDocs/playbook-reconnaissance.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/playbook-reconnaissance.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Sorry, this is not a documentation question.

As noted in the document:

The third-party hacking tools in this lab are presented for research purposes only. Microsoft does not own these tools and Microsoft cannot and does not guarantee or warranty their behavior. They are subject to change without notice. These tools should be run in a test lab environment only.

**Comment by szymonslipek** [comment]
Sure & clear.
This wasn’t about netsess itself but lab config. And Yes, WinServer version plays a matter here. Up to 2012R2 it works as expected, under does not.
Thank You.
