### ISSUE TITLE
Possible Typo in this article

### ISSUE THREAD

**Issue by Abhishek-Sharan** [MicrosoftDocs/ATADocs#517]
[Enter feedback here]

Hi Team - I see 7 entries for "T-BP activity" in this page, can you please cross check if this is a typo as we have TP, B-TP & FP activities only. I'm MSFT employee, please feel free to share your thoughts on absharan@microsoft.com. 

Regards
Abhishek Sharan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9bf93d-2f09-90ca-5feb-4106a4f8abb2
* Version Independent ID: e03df8b6-624b-30a8-2502-6be59ff98606
* Content: [Microsoft Defender for Identity compromised credentials phase security alerts](https://docs.microsoft.com/en-us/defender-for-identity/compromised-credentials-alerts#feedback)
* Content Source: [ATPDocs/compromised-credentials-alerts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/compromised-credentials-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your contribution. The typos have been corrected.
