### ISSUE TITLE
Incorrect Portal links for GCC-High and DoD

### ISSUE THREAD

**Issue by stephen-mitchell-interfuze** [MicrosoftDocs/ATADocs#518]
I believe the portal links listed on this page for GCC-High and DoD are incorrect.  They list portal.azure.atp.us; however, I think it should be portal.atp.azure.us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c1267e-9737-e08b-6da5-732f67337b90
* Version Independent ID: e76864fb-664e-d57a-fa86-c4a1acc97faa
* Content: [Microsoft Defender for Identity for US Government offerings](https://docs.microsoft.com/en-us/defender-for-identity/us-govt-gcc-high)
* Content Source: [ATPDocs/us-govt-gcc-high.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/us-govt-gcc-high.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for the comment. We'll update the page and get back to you.

**Comment by dcurwin** [comment]
The page has been updated. Thanks!
