### ISSUE TITLE
one gMSA and many DCs

### ISSUE THREAD

**Issue by joestern** [MicrosoftDocs/ATADocs#520]
Does this gMSA need to be associated with all domain controllers or just the one where it was created?

If so, I assume that any time in the future a new DC is added, the gMSA linkages will need to be adjusted, and our procedure documents as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Version Independent ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Content: [Manage action accounts](https://docs.microsoft.com/en-us/defender-for-identity/manage-action-accounts)
* Content Source: [ATPDocs/manage-action-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/manage-action-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@joestern - Thanks again for your question. It is sufficient to create a gMSA on one domain controller for each domain. It is associated with the domain, not the domain controller. We've updated the documentation to make that more clear.
