### ISSUE TITLE
Change Slash

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/ATADocs#521]
This should be a backslash not a forwardslash

When using the Powershell syntax, omitting the ./ preface results in an error that prevents silent installation.

The example code in the line above is correct.  

Cheers,
Rhoderick 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2cb616-13e9-65be-94b6-de46ab00bafc
* Version Independent ID: 0313bbbd-5ec6-f850-4b02-cb10f4b599c5
* Content: [Install Microsoft Defender for Identity Silently](https://review.docs.microsoft.com/en-us/defender-for-identity/silent-installation?source=docs&branch=main)
* Content Source: [ATPDocs/silent-installation.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/silent-installation.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your correction. We've updated the page.
