### ISSUE TITLE
<instancename>.atp.azure.com

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#522]
It is only specified to open connectivity to `*.atp.azure.com`. Can this be more specific, like

- `<instancename>.atp.azure.com` for the portal
- `<instancename>sensorapi.atp.azure.com` for the sensors

where `instancename` is the name of the MDI  instance, e.g. `contoso-corp`.

It is described [here](https://docs.microsoft.com/en-us/defender-for-identity/configure-proxy#enable-access-to-defender-for-identity-service-urls-in-the-proxy-server), but I wasn't looking for proxy configuration, as we don't have any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://docs.microsoft.com/en-us/defender-for-identity/prerequisites)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI  - Thanks again for your comment. I worked with the product team, and they informed me that for the sensors, the more specific <instancename>sensorapi.atp.azure.com is appropriate. I've updated the documentation accordingly.

They informed me that the portal address should not change (and in any case, it's better to use the Microsoft 365 Defender portal.)
