### ISSUE TITLE
What is this article for ? What product ? How/Why is this here ?

### ISSUE THREAD

**Issue by bencorley** [MicrosoftDocs/ATADocs#523]
I still can't get how this can be useful for people, what is this ? A product ? A feature ? Where can I use this ? HOW can I use this ? Such a poor article, is this related to any Defender solution ? It's a guess at this point !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b81b1f9-f9fc-8241-43a2-a0bd0cf34518
* Version Independent ID: 8530cdc1-c066-6487-625d-748a0782c9ef
* Content: [Microsoft Defender for Identity clear text exposure assessment](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-clear-text)
* Content Source: [ATPDocs/cas-isp-clear-text.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/cas-isp-clear-text.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
