### ISSUE TITLE
It seems upon closer review that the tool described here is for determining Stand-Alone Sensor capacity. I recommend revising to avoid confusion with customers using the new local install option. The current description is not clear on this point.

### ISSUE THREAD

**Issue by AndrewBlumhardt** [MicrosoftDocs/ATADocs#524]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ad0426-76e9-66e3-3fcb-712be559fc54
* Version Independent ID: 95812681-c99c-13d6-cbc2-1bcf6cd02632
* Content: [Planning your Microsoft Defender for Identity deployment](https://docs.microsoft.com/en-us/defender-for-identity/capacity-planning)
* Content Source: [ATPDocs/capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/capacity-planning.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@AndrewBlumhardt - The sizing tool isn't just for Stand-Alone installation. But I'd like to understand how you arrived at that conclusion. Was it something in the documentation or in the tool itself?

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
