### ISSUE TITLE
Issue running listed PS command

### ISSUE THREAD

**Issue by born-slippy** [MicrosoftDocs/ATADocs#526]
Hello:
I am attempting to follow the steps under the heading:
**To grant access for the sensor to the AD FS database using PowerShell:**

I receive the following error, which indicates perhaps the documentation is not correct:

PS C:\Windows\system32> $SqlDataReader = $SQLCommand.ExecuteReader()
Exception calling "ExecuteReader" with "0" argument(s): "Incorrect syntax near 'GO'."
At line:1 char:1
+ $SqlDataReader = $SQLCommand.ExecuteReader()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SqlException

Is the string within $SQLCommand.CommandText correct:

$SQLCommand.CommandText = @"
USE [master]; 
CREATE LOGIN [DOMAIN1\triservice] FROM WINDOWS WITH DEFAULT_DATABASE=[master];
USE [AdfsConfigurationV4]; 
CREATE USER [DOMAIN1\triservice] FOR LOGIN [DOMAIN1\triservice]; 
ALTER ROLE [db_datareader] ADD MEMBER [DOMAIN1\triservice]; 
GRANT CONNECT TO [DOMAIN1\triservice]; 
GRANT SELECT TO [DOMAIN1\triservice]; 
GO;
"@

What is the syntax error near GO in the query?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b394b6-8e07-4fe5-6d89-127482e13dd8
* Version Independent ID: d4b394b6-8e07-4fe5-6d89-127482e13dd8
* Content: [Microsoft Defender for Identity on Active Directory Federation Services (AD FS)](https://docs.microsoft.com/en-us/defender-for-identity/active-directory-federation-services#post-installation-steps-for-ad-fs-servers)
* Content Source: [ATPDocs/active-directory-federation-services.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/active-directory-federation-services.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@born-slippy -  Thanks again for your question. The line with **Go** in the PowerShell script should not have been there. We've removed it from the documentation.
