### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by toddjames** [MicrosoftDocs/ATADocs#527]
The "Add a sensor" link is broken in the "Add a sensor" section. I suspect this is the correct URL: https://docs.microsoft.com/en-us/microsoft-365/security/defender-identity/sensor-health?view=o365-worldwide#add-a-sensor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a7422f7-6221-1898-9290-8733a8943185
* Version Independent ID: 5a7422f7-6221-1898-9290-8733a8943185
* Content: [Deploy Defender for Identity with Microsoft 365 Defender](https://docs.microsoft.com/en-us/defender-for-identity/deploy-defender-identity#feedback)
* Content Source: [ATPDocs/deploy-defender-identity.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/deploy-defender-identity.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We've fixed the link.
