### ISSUE TITLE
Exposed Entities under LAPS Security Finding Dont List Names

### ISSUE THREAD

**Issue by timkatsapas** [MicrosoftDocs/ATADocs#528]
When going through Microsoft Defender for Identity Secure Score we found an issue relating to LAPS.
When we investigated it in MCAS under Identity Security Posture, we then saw that it doesn't list the device names, but only the domain instead. 
We are unable to figure out which devices these are since that domain name has been decommissioned. 
What is the proper way to determine the devices?
The issue is present on step 3 in that view from this page https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-laps.

Thank you kindly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: decb6614-439c-9765-5458-ab13cc6832e4
* Version Independent ID: fc4ff52d-3efb-6e16-08d7-f4497b4fec69
* Content: [Microsoft Defender for Identity Microsoft LAPS usage assessments](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-laps)
* Content Source: [ATPDocs/cas-isp-laps.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/cas-isp-laps.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. We've updated the documentation to make it more clear. If none of the devices in a domain are protected with LAPS, then you only see the domain, not the individual devices.
