### ISSUE TITLE
Always displayed in simplified Chinese except for English (en-)

### ISSUE THREAD

**Issue by todkm** [MicrosoftDocs/ATADocs#529]
This page is always displayed in simplified Chinese whatever language you set in the URL (e.g. "/ja-jp/", "/de-de/", "/fr-fr/") except for English ("/en-")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b394b6-8e07-4fe5-6d89-127482e13dd8
* Version Independent ID: d4b394b6-8e07-4fe5-6d89-127482e13dd8
* Content: [Microsoft Defender for Identity on Active Directory Federation Services (AD FS)](https://docs.microsoft.com/en-us/defender-for-identity/active-directory-federation-services)
* Content Source: [ATPDocs/active-directory-federation-services.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/active-directory-federation-services.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@todkm - I am able to view the page in the various language. It seems this may be a problem on your end.
