### ISSUE TITLE
ATA Lightweight Gateway: Some network traffic is not being analyzed

### ISSUE THREAD

**Issue by minhtran180199** [MicrosoftDocs/ATADocs#530]
[Enter feedback here]
Hi,

I am having a problem with the following error "Some network traffic is not being analyzed''. 
I tried to follow Microsoft's troubleshooting guide but I am facing the problem that when I configure "TsoEnable" on Exsi server, I can't restart after configuring because my server is running many important services.
Is there any other way to fix this problem? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca3a1e-2306-c908-1c80-29e0ee276466
* Version Independent ID: 6583a55c-abc4-a9fa-7d7f-b0f3e67345da
* Content: [Understanding ATA health alerts](https://docs.microsoft.com/en-us/advanced-threat-analytics/monitoring-alerts?source=docs#feedback)
* Content Source: [ATADocs/monitoring-alerts.md](https://github.com/Microsoft/ATADocs/blob/main/ATADocs/monitoring-alerts.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@minhtran180199  - We recommend you open a support case in these circumstances.

**Comment by minhtran180199** [comment]
Can you give me the support link?

**Comment by dcurwin** [comment]
You can open a ticket through the links here:

https://docs.microsoft.com/en-us/defender-for-identity/support
