### ISSUE TITLE
Microsoft Sentinel?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#531]
I don’t think this applies to MS Sentinel. Would it be an idea to put a note about this on this page, perhaps referring to documentation for MDI integration (M365 Defender?) into Sentinel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1a48e5-a4ea-495b-6656-793e23d807ef
* Version Independent ID: 9908c36d-b7b7-ab72-f162-77a54da8b42d
* Content: [Setting Syslog settings in Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/setting-syslog)
* Content Source: [ATPDocs/setting-syslog.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/setting-syslog.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI  - We've added a note - thanks again for your contribution.
