### ISSUE TITLE
incorrect link

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#532]
In 6. Set Honeytokens, the link refers to [exclusions](https://docs.microsoft.com/en-us/defender-for-identity/configure-detection-exclusions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75a8224-7830-90db-919d-68a068e130a1
* Version Independent ID: e0dbb2f0-0428-f2e6-fb32-f8ce7eae9c99
* Content: [Advanced Threat Analytics to Microsoft Defender for Identity move](https://docs.microsoft.com/en-us/defender-for-identity/migrate-from-ata-overview)
* Content Source: [ATPDocs/migrate-from-ata-overview.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/migrate-from-ata-overview.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks - the link has been fixed.
