### ISSUE TITLE
This lab is incomplete and incorrect

### ISSUE THREAD

**Issue by ditrautman** [MicrosoftDocs/ATADocs#533]
[Enter feedback here]
1.	The GPO setting required does not exist for Server 2012 R2, it was added in Server 2016.  I have even followed several guides to import it, update the server via patches from 2017, and finally installed a Server 2016 server and promoted to DC just to be able to see the GPO settings in the GUI.
2.	The lab expects us to set a specific security group as a sensitive group but doesn’t tell us whether we need to sync it from on-premises (need to install AADConnect - most likely) or create in the cloud, or whether it’s expected the Sensor installed is supposed to detect it.  After installing AADConnect, the group still doesn't show in the search.

and this is just for the lab setup.  I haven't even gotten to the point of actually using the product.

What needs to be included is either a GPO export to import that will actually display the setting to be configured, or an indication to use an appropriate version of Windows Server that includes it.  Also, clarity around what needs to be set up for the tenant and how/where to propagate the groups from.

I don't look forward to identifying the inconsistencies and invalid settings in the rest of your labs.

Dan Trautman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b9eb03-cb5e-ab2b-c088-2badd87cc682
* Version Independent ID: ab8cbfa9-7f3f-e635-f977-0652c8511397
* Content: [Microsoft Defender for Identity security alert lab setup tutorial](https://docs.microsoft.com/en-us/defender-for-identity/playbook-setup-lab)
* Content Source: [ATPDocs/playbook-setup-lab.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/playbook-setup-lab.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by ditrautman** [comment]
Thank you very much David.  I still have my server VM's set up, so let me know if there's anything I can do to help.  This lab is part of a requirement for certification, so I'm eager to complete it.

Have a great day,


Dan Trautman
Consultant, Workforce Consulting
Dell Technologies | Professional, Managed & Field Services
Mobile: (+1) 206-579-8993
***@***.***

How am I doing? Please email my manager ***@***.******@***.***>, with any feedback.

**Comment by dcurwin** [comment]
We are now revising our lab content.  No date is set for the revision, but the documentation will be updated with the new content when ready. Thanks for your patience.
