### ISSUE TITLE
Missing a 'Clear All' step for AD FS auditing configuration?

### ISSUE THREAD

**Issue by TheFiZi** [MicrosoftDocs/ATADocs#535]
Under [this section](https://docs.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#enable-auditing-on-an-adfs-object) after step 7 and [this section](https://docs.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#enable-auditing-on-an-exchange-object) after step 9 should there be a step to scroll to the bottom of the permissions window and click 'Clear all' like step 8 under [this section](https://docs.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-object-auditing)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#relevant-windows-events)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@TheFiZi  - Sorry, we didn't notice that this issue was still open. The documentation was updated a few months ago.
