### ISSUE TITLE
gmSA accounts and multiple domains

### ISSUE THREAD

**Issue by TheFiZi** [MicrosoftDocs/ATADocs#536]
The documentation as written leads one to believe that a gmSA can be used across domains within a single forest.

For example in our environment:

```
top.mydomain.com (Top of forest)
|-> sub1.top.mydomain.com (Sub domain)
|-> sub2.top.mydomain.com (Sub domain)
```

I've created my gmSA in `top.mydomain.com` and configured a Universal Security Group containing all of my domain controllers from all three domains.

I can use `Install-ADServiceAccount` in `top.mydomain.com` to install the gmSA account but when I try `sub1.top.mydomain.com` it fails saying it cannot find the gmSA in `sub1.top.mydomain.com`. There does not appear to be a way to specify which domain the gmSA is located.

[According to this blog post](https://thewindowsupdate.com/2021/11/10/using-gmsa-account-in-microsoft-defender-for-identity-in-multi-domain-forests/) the `Install-ADServiceAccount` [portion of the documentation](https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts#install-the-gmsa-account) is not required and Defender for Identity will work with out performing it.

That being said, [according to Microsoft](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/getting-started-with-group-managed-service-accounts) gmSA accounts are not supported across domains. This documentation is leading us to configure Defender for Identity in a unsupported way.

![image](https://user-images.githubusercontent.com/1762426/159096108-f28b1511-b8ef-4101-a551-235175d174a7.png)

I'm really not sure what the best way forward is. You could remove or caveat the `Install-ADServiceAccount` portion of the documentation but it still leads people into configuring a gmSA in a unsupported way if I am understanding things correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service Account recommendations](https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@TheFiZi  - Thank you again for your question. The table on https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/getting-started-with-group-managed-service-accounts has been updated, and the "scope" column has been removed, and the following sentence has been added:

Use of the gMSA is scoped to any machine that is able to use LDAP to retrieve the gMSA's credentials. 

So configuring gMSA as described is supported.
