### ISSUE TITLE
Pre-Requisite for unique gMSA name when deploying across multiple forests

### ISSUE THREAD

**Issue by Ayrezy** [MicrosoftDocs/ATADocs#538]
Hi,

During a complex deployment with a customer it has been noted that our documentation does not explicitly state that when using multiple forests a pre-requisite should be that each gMSA has a unique name. If not, this can cause issues with the service starting on the domain controllers.

Thanks

Chris Ayres
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service Account recommendations](https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We added a note here: https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts#how-to-create-a-gmsa-account-for-use-with-defender-for-identity saying:

"In a multi-forest environment, we recommend creating the gMSAs with a unique name for each forest or domain."
