### ISSUE TITLE
Translate in page it-it

### ISSUE THREAD

**Issue by nicogis** [MicrosoftDocs/ATADocs#541]
In url it-it -> https://docs.microsoft.com/it-it/advanced-threat-analytics/ata-prerequisites
This phrase 'The domain controller can be a read-only domain controller (RODC).' is translated "Il controller di dominio deve essere un controller di dominio di sola lettura (RODC)."

The translation should be : 'Il controller di dominio può essere un controller di dominio di sola lettura (RODC).'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b15d84d8-289c-11e0-7ce5-cc28456ae78e
* Version Independent ID: 9c3b04df-47c7-2e18-a4f7-06b957461a06
* Content: [Advanced Threat Analytics prerequisites](https://docs.microsoft.com/en-us/advanced-threat-analytics/ata-prerequisites)
* Content Source: [ATADocs/ata-prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATADocs/ata-prerequisites.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@nicogis  - Thank you for bringing this to our attention. I've let the localization team know about it, and they will hopefully resolve the issue soon.
