### ISSUE TITLE
Documentation needs updating for new Microsoft 365 Defender Portal

### ISSUE THREAD

**Issue by TheFiZi** [MicrosoftDocs/ATADocs#542]
Under https://docs.microsoft.com/en-us/defender-for-identity/integrate-mde#how-to-integrate-defender-for-identity-with-defender-for-endpoint

Step 3 is for the old Microsoft 365 Defender Portal.

For the new https://security.microsoft.com/ you want to go to https://security.microsoft.com/securitysettings and then 'Endpoints', 'Advanced Features' and toggle on 'Microsoft Defender for Identity integration' or go directly here https://security.microsoft.com/preferences2/integration and toggle on 'Microsoft Defender for Identity integration'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 125ce79b-c73e-e2f3-e4a9-8137f4811ae1
* Version Independent ID: 319128c4-aaf1-301a-a24b-103d2fc94042
* Content: [Microsoft Defender for Identity integration with Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/defender-for-identity/integrate-mde)
* Content Source: [ATPDocs/integrate-mde.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/integrate-mde.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@TheFiZi  - Thanks for bringing this to our attention. We're in the process of revising the Defender for Identity documentation to reflect the new M365 Defender portal. We'll be sure to include this suggestion in that revision.
