### ISSUE TITLE
Remove duplicate sensor directions are same as orphaned sensor

### ISSUE THREAD

**Issue by jrohrich** [MicrosoftDocs/ATADocs#544]
[Enter feedback here]
It appears the directions for removing a duplicate sensor are simply a copy of the directions for removing an orphaned sensor (including the word "orphaned") with no indication as to how to determine which of the duplicate sensors should be removed. If the procedure is in fact similar, the wording should be changed to "locate the duplicate sensor...", ideally with some instruction as to which of the two duplicates should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06061375-295c-21b2-3877-e53f8e0390ab
* Version Independent ID: 81f29361-c59f-260f-651a-40816343b522
* Content: [Uninstall Microsoft Defender for Identity sensor](https://docs.microsoft.com/en-us/defender-for-identity/uninstall-sensor#feedback)
* Content Source: [ATPDocs/uninstall-sensor.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/uninstall-sensor.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your comment. We've updated the documentation accordingly.
