### ISSUE TITLE
Screenshot for assigning rights for the gMSA

### ISSUE THREAD

**Issue by CsabaKe** [MicrosoftDocs/ATADocs#545]
Hello,

in the screenshot, you are doming assigning the rights for the gMSA at the domain root level. I believe this should be avoided and it should be linked to an OU. According to security best practices, you should not create a link between on premise and cloud so a cloud admin in this example can reset the password for an admin account on the domain. 

I know the screenshot is just "an indication" however, I think it would reflect better the requirement if linked to a user OU.

Thank you.

Csaba
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Version Independent ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Content: [Manage action accounts](https://docs.microsoft.com/en-us/defender-for-identity/manage-action-accounts)
* Content Source: [ATPDocs/manage-action-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/manage-action-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your comment. We've updated the screenshots.
