### ISSUE TITLE
Typos and suggestion

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#548]
Please fix the typos: in the section **Two or more DSA entries are configured**
emea.consoso.com (conSoso)
emea.constoso.com  (conStoso)
emea.consoto.com (conSoTo)

And please add an example for the case
`A.root` and `B.sub` domains, where `A.root` is the primary root domain in the forest and `B.sub` is the child domain. What if we have `A.root\GMSA01` or `B.sub\GMSA02` or both? (assume there is another forest too with `C.corp\GMSY03` so it is always the multiple DSA algorithm). What account(s) will be tried by `DC01.A.root` and `DC02.B.sub` and  in what order? I understand the case for `D.C.corp` (proper subdomain of `C.corp`, but not for the A/B situation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service Account recommendations](https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. The typos have been corrected. As far as your suggestion, we'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI  - The product team has responded to your issue as follows:

We cannot address all different scenarios; this is why we describe the flow in general, and we've now updated the docs to describe that the root/child matching is done by the DNS FQDN and not the parent/child relationship.
