### ISSUE TITLE
Exceptions for system accounts

### ISSUE THREAD

**Issue by Visor57** [MicrosoftDocs/ATADocs#549]
Are there any exceptions to the "password not required" check?
For example:

- Launch IIS Process Account
- Exchange Online-ApplicationAccount
- HealthMailbox[GUID]

Does removing the unsecure account attribute from these types of accounts impact functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade1b68-cd1e-0772-f0ed-f639cbc6bbce
* Version Independent ID: c43b2bee-dce5-4337-3618-5224aa13597e
* Content: [Microsoft Defender for Identity unsecure account attributes assessments](https://docs.microsoft.com/en-us/defender-for-identity/cas-isp-unsecure-account-attributes)
* Content Source: [ATPDocs/cas-isp-unsecure-account-attributes.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/cas-isp-unsecure-account-attributes.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
The response from the product team is they are not aware of legitimate reasons why this value should be set.

I suggest if you have any further questions about your particular environment, you open a support case.
