### ISSUE TITLE
Unique account names?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#550]
One of the Notes states: "In a multi-forest environment, we recommend creating the gMSAs with a unique name for each forest or domain."
Is it a recommendation or a requirement? That is not clear to me. We have many EventID 2947 events on all our DCs where a sensor is running, due to the sensor trying accounts not meant for that domain (we have 10 domains in 8 forests). It was suggested to use unique names by Premier support, but we deliberately chose the same name everywhere, so we can alwasy say "GMSA0123 is intended for Defender for Identity".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service Account recommendations](https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts#how-to-create-a-gmsa-account-for-use-with-defender-for-identity)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI - As noted in the document, this is a recommendation for ease of identifying the account in the logs, but is not a requirement.

**Comment by andrePKI** [comment]
Ok, thank you,. I see that some remarks about multi-forest environments were added. What about _trusted_ multi-forest envs?

**Comment by dcurwin** [comment]
@andrePKI - Not sure I understand your question. Can you clarify?

**Comment by andrePKI** [comment]
Well the statements about multi-domain/forests in the document are

•	In an **untrusted multi-forest** environment, a DSA account will be required for each forest.
•	In a **multi-domain forest**, it's recommended that the DSA account be created in the domain with the largest number of domain controllers.
•	In **multi-forest multi-domain** environments, consider creating a DSA entry for each domain in the environment to avoid failed authentications from being recorded due to the round robin method.

Does that cover the **trusted multi-forest** and/or **trusted multi-forest multi-domain** too? I.e. we have forest A with child Aa and forest B (no  childs); there is a bidirectional forest trust between A and B and an external trust between Aa and B.
We had a DSA (Group managed service accounts) in each domain, and Premier support advised use to have only 1 DSA per forest (second bullet above) and also have the accounts named uniquely to avoid confusion. Hence `Aa\GMSY01` and `B\GMSY02` (A has 2 DCs and Aa has 10)

But we have the **multi-forest multi-domain** as described in the third bullet, which would add a third account `A\GMSY03`.
In all, it is not clear to us, despite this document and what we see in practice (too many eventid 2947 events ('An attempt to fetch the password of a group managed service account failed') due to the round-robin trials) and what the Premier support engineer told us.

**Comment by dcurwin** [comment]
Ok, I'll ask the product group about that.

**Comment by dcurwin** [comment]
The product team has reported that in the weeks to come they plan to add better support for gMSAs in multi-forest (trusted) environments. This will decrease the number of failed authentication (2947) events.

When that update is released the documentation will be updated as well.
