### ISSUE TITLE
Applies to section

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/ATADocs#553]
Suggesting the addition of Applies to licensing plans / service plans which include this product. Same as seen below:
https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-mdo?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8df167b-3d6a-ebd1-4401-4596565b9238
* Version Independent ID: 56c40693-376f-4a86-ca85-5ecfd9cb3558
* Content: [What is Microsoft Defender for Identity?](https://docs.microsoft.com/en-us/defender-for-identity/what-is)
* Content Source: [ATPDocs/what-is.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/what-is.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion.

We already discuss licensing here: https://docs.microsoft.com/en-us/defender-for-identity/technical-faq#licensing-and-privacy

But based on your suggestion we added a link to the See Also section on the "What is MDI" page.
