### ISSUE TITLE
Tab is renamed?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#554]
I believe the tab has a new name **Recommended actions** instead of **Improvement actions**.

![image](https://user-images.githubusercontent.com/23510294/181068513-9bd34f94-115e-447e-a796-70053979ce1a.png)

This remark holds for other pages too, like [this one](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score?view=o365-worldwide) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f3bdcfa-e925-2280-0e37-e054bde0462f
* Version Independent ID: 0f3bdcfa-e925-2280-0e37-e054bde0462f
* Content: [Microsoft Defender for Identity's security posture assessments](https://docs.microsoft.com/en-us/defender-for-identity/security-assessment)
* Content Source: [ATPDocs/security-assessment.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI  - Thanks for pointing that out. I updated the text and images on the MDI page. 

As far as the other page you linked to, I suggest you open a GitHub issue there.
