### ISSUE TITLE
Unclear: on VMWare or in Windows?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#555]
In the section [Some network traffic could not be analyzed](https://docs.microsoft.com/en-us/defender-for-identity/health-alerts#some-network-traffic-could-not-be-analyzed) some settings are referred to:

- TsoEnable
- LargeSendOffload(IPv4)
- IPv4 TSO Offload
- IPv4 Giant TSO Offload

Of this list, only the second and third can be found on the configuration of the NIC in Windows.
In [VMWare documentation](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-D80AEC2F-E0DA-4172-BFFD-B721BF36C2E8.html) only LargeSendOffload(IPv4) and LargeSendOffload(IPv6) are mentioned.

Other settings are mentioned (like Jumbo packets) but that does not align with the terminology used in this article.

Could you please clarify what exactly is meant? Which must be set in Windows and which in VMWare VSphere?
What would be the best or recommended approach to solve the issue **"Some network traffic could not be analyzed"**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79c7f20-b009-da8a-5fdd-13f5902e772f
* Version Independent ID: 6c6fa2c6-1d3c-f8b3-af9a-9a6b7ca0d4af
* Content: [Microsoft Defender for Identity health alerts](https://docs.microsoft.com/en-us/defender-for-identity/health-alerts)
* Content Source: [ATPDocs/health-alerts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/health-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by f-bader** [comment]
Hi @andrePKI ,

from my experience the settings has to be disabled in the Windows VM, not VMware itself.

The exact cmdlets are described in the troubleshooting section "[VMware virtual machine sensor issue](https://docs.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues#vmware-virtual-machine-sensor-issue)".

```
Get-NetAdapterAdvancedProperty | Where-Object DisplayName -Match "^Large*"
Disable-NetAdapterLso -Name AdapterName
```

**Comment by andrePKI** [comment]
Ok, thank you, I am aware of that.
But 4 settings are mentioned by name, of which only 2 I can find in the adapter config, so the other 2 remain a mystery.
Hence, please clarify or update the doc, please

**Comment by dcurwin** [comment]
Thanks for your comments. The document has been updated to improve the clarity.
