### ISSUE TITLE
Get-Net* Commands no longer available

### ISSUE THREAD

**Issue by austin-stratton** [MicrosoftDocs/ATADocs#556]
Hey there! recent MSFT-alumni here, and used to teach MDI to customers and other students. 

The Powersploit module is no longer supported by PowershellMafia, and as such, enumerating groups with this tool is not possible unless you have an older version. The Recon folder now only contains Get-ComputerDetails, Get-HttpStatus, and Invoke-ReverseDnsLookup. 

The playbook will need to be updated to reflect this change. 

-Austin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfe698-05a4-8d4c-75b8-024ab912e18c
* Version Independent ID: 4d58c76d-b7b5-9900-9c14-557f892cc54e
* Content: [Microsoft Defender for Identity security alert lateral movement playbook](https://docs.microsoft.com/en-us/defender-for-identity/playbook-lateral-movement)
* Content Source: [ATPDocs/playbook-lateral-movement.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/playbook-lateral-movement.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by danaim1** [comment]
It's true that it's not supported anymore, but get commands still under PowerView:

https://powersploit.readthedocs.io/en/latest/Recon/

**Comment by dcurwin** [comment]
@austin-stratton  - What do you think?

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
