### ISSUE TITLE
Missing Unsecure Domain Configuration assessment link in assessments Overview page

### ISSUE THREAD

**Issue by lsousa-code** [MicrosoftDocs/ATADocs#557]
In the Assessment report list, inside the page in: https://docs.microsoft.com/en-us/defender-for-identity/security-assessment#assessment-reports the new Unsecure Domain Configuration assessment link is missing https://docs.microsoft.com/en-us/defender-for-identity/security-assessment-unsecure-domain-configurations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f3bdcfa-e925-2280-0e37-e054bde0462f
* Version Independent ID: 0f3bdcfa-e925-2280-0e37-e054bde0462f
* Content: [Microsoft Defender for Identity's security posture assessments](https://docs.microsoft.com/en-us/defender-for-identity/security-assessment)
* Content Source: [ATPDocs/security-assessment.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your comment. The link has been added.
