### ISSUE TITLE
"Install-Module ActiveDirectory" command fails

### ISSUE THREAD

**Issue by jschwager** [MicrosoftDocs/ATADocs#562]
Under the "Create a gMSA account" section, the provided PowerShell command fails on the "Install-Module ActiveDirectory" section with the following error:
```
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'ActiveDirectory'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
Replacing Install-Module with Import-Module appears to resolve the issue as the ActiveDirectory module is already installed by default on a Server 2019 DC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service account recommendations](https://docs.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.
