### ISSUE TITLE
Get-NetLocalGroupMember' is not recognized as the name of a cmdlet,  function, 

### ISSUE THREAD

**Issue by SuryenduB** [MicrosoftDocs/ATADocs#563]
[Enter feedback here]

In PowerSploit.psm1 I am getting the following error.

Get-NetLocalGroupMember : The term 'Get-NetLocalGroupMember' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ Get-NetLocalGroupMember 192.168.41.11 -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetLocalGroupMember:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfe698-05a4-8d4c-75b8-024ab912e18c
* Version Independent ID: 4d58c76d-b7b5-9900-9c14-557f892cc54e
* Content: [Microsoft Defender for Identity security alert lateral movement playbook](https://docs.microsoft.com/en-us/defender-for-identity/playbook-lateral-movement)
* Content Source: [ATPDocs/playbook-lateral-movement.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/playbook-lateral-movement.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.
