### ISSUE TITLE
Verification of ADFS sensor?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#564]
This article describes how to verify sensor installation on a Domain Controller (and/or standalone sensor) by using `nslookup`.
Is there a way to way to verify the same on an ADFS server? Obviously `nslookup`  will not work as ADFS usually does not run DNS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac5b74-85a1-6a19-3cf8-fc5d1899eaaf
* Version Independent ID: 4bac5b74-85a1-6a19-3cf8-fc5d1899eaaf
* Content: [Configure Microsoft Defender for Identity sensor settings](https://docs.microsoft.com/en-us/defender-for-identity/configure-sensor-settings)
* Content Source: [ATPDocs/configure-sensor-settings.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-sensor-settings.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI  - Thanks for your question. We've updated the page to include that information.
