### ISSUE TITLE
No information on how to set dsacls on Deleted Objects container for MDI

### ISSUE THREAD

**Issue by jxsmith786110** [MicrosoftDocs/ATADocs#565]
This page states that read permissions are recommended on Deleted Objects container by MDI service account and provides a link to the pre-req page.  That pre-requisite for MDI page provides no information on how to set the read permissions on Deleted Objects container.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e5897-d642-c71a-7212-0f7cca46c8b9
* Version Independent ID: 1b66013a-33ed-fe34-0ab6-241050ef1240
* Content: [Microsoft Defender for Identity personal data policy](https://docs.microsoft.com/en-us/defender-for-identity/privacy-compliance)
* Content Source: [ATPDocs/privacy-compliance.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/privacy-compliance.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@jxsmith786110  - Thanks again for your comment. We've updated the documentation to provide the informaiton you requested.
