### ISSUE TITLE
Delayed updates

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#566]
One of the sensor configuration steps is to enable delayed updates (if not done that by the installation parameter of the sensor install). I feel that that step is missing from this page. Could that be added (or a reference to a different page) to this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac5b74-85a1-6a19-3cf8-fc5d1899eaaf
* Version Independent ID: 4bac5b74-85a1-6a19-3cf8-fc5d1899eaaf
* Content: [Configure Microsoft Defender for Identity sensor settings](https://docs.microsoft.com/en-us/defender-for-identity/configure-sensor-settings)
* Content Source: [ATPDocs/configure-sensor-settings.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-sensor-settings.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for the suggestion. I've added a note to the document explaining how to configure delayed updates.
