### ISSUE TITLE
3.h is not clear enough

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/ATADocs#568]
[Enter feedback here]
3.h is not clear enough.  In much of the MDI documentation permissions changes involve clearing the existing permissions and only setting the specifically noted permissions in the document.  Here it seems that is not the case, but the document is not clear, it should be stated more clearly, specifically noting to " **leave** the existing settings and **add** the following **additional** permissions: "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Version Independent ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Content: [Manage action accounts](https://learn.microsoft.com/en-us/defender-for-identity/manage-action-accounts)
* Content Source: [ATPDocs/manage-action-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/manage-action-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your suggestion. We've updated the page accordingly.
