### ISSUE TITLE
verification only possible one time

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#571]
Please add a note that states that after an initial learning period (8 days?) a second attempt to do a zone transfer by the same user from the same machine will not trigger an alert anymore (as it is deemed a normal activity).
As far as I know there is no ad-hoc / on-demand way of verifying that a specific sensor is still working correctly. In my opinion the description of this verification procedure gives the impression that you could perform this anytime and as often as you like and it would trigger an alert (which is not the case).

Maybe I should file a feature request for a test alert triggered by some action like exists for Defender for Endpoint (see [here](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-detection-test))?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac5b74-85a1-6a19-3cf8-fc5d1899eaaf
* Version Independent ID: 4bac5b74-85a1-6a19-3cf8-fc5d1899eaaf
* Content: [Configure Microsoft Defender for Identity sensor settings](https://learn.microsoft.com/en-us/defender-for-identity/configure-sensor-settings)
* Content Source: [ATPDocs/configure-sensor-settings.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-sensor-settings.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrePKI  - Thanks for your comment. We've added a note indicating this on this page:

https://learn.microsoft.com/en-us/defender-for-identity/playbooks#network-mapping-reconnaissance-dns
