### ISSUE TITLE
Move the 'Permissions required for the DSA' down further.

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/ATADocs#572]
Move the 'Permissions required for the DSA' down further. It doesn't make sense to lead off the article with this section since the user can't complete it since they haven't created the DSA yet. Further, after having read the doc and created the account, they may forget to come back to the top and perform that section.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service account recommendations](https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@ianc911  - Thanks for your feedback. We've moved the section lower down on the page (the change should go live soon).
