### ISSUE TITLE
To install NPCAP or not?

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/ATADocs#573]
This page says to to install the NPCAP driver, whereas this page: https://learn.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues#defender-for-identity-sensor-nic-teaming-issue says it only needs to be installed if the server is using a NIC team. Which is it?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c37c4c7f-22ca-16c4-9060-4e587f9e5ad1
* Version Independent ID: c37c4c7f-22ca-16c4-9060-4e587f9e5ad1
* Content: [Install the Microsoft Defender for Identity sensor](https://learn.microsoft.com/en-us/defender-for-identity/install-sensor)
* Content Source: [ATPDocs/install-sensor.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/install-sensor.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@ianc911  - We've updated the documentation to indicate that teaming is only an issue if the Winpcap driver is installed. Thanks for your question!
