### ISSUE TITLE
Teamed NIC's no longer a problem

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/ATADocs#574]
Newer versions of the sensor downloaded from the port automatically install NPCAP, so teamed adapters are not an issue any longer and you not receive an error upon installation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Microsoft Defender for Identity prerequisites](https://learn.microsoft.com/en-us/defender-for-identity/prerequisites)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@ianc911  - We've updated the documentation to indicate that teaming is only an issue if the Winpcap driver is installed. Thanks for your question!
