### ISSUE TITLE
Use pre-existing gMSA account already created?

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/ATADocs#575]
The obvious question that immediately arises is 'can I use the same gMSA account I already created for MDI to run the sensors on my DC's for remediation?'. However, that question doesn't seem to be addressed here. How about providing an answer or some context to guide people?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Version Independent ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Content: [Manage action accounts](https://learn.microsoft.com/en-us/defender-for-identity/manage-action-accounts)
* Content Source: [ATPDocs/manage-action-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/manage-action-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@ianc911  - Thanks again for your comment. We've added a note to the page explaining that using the same account isn't recommended.
