### ISSUE TITLE
"A" domain controllers are unreachable by a sensor alert missing from this page

### ISSUE THREAD

**Issue by jackson-yang-microsoft** [MicrosoftDocs/ATADocs#577]
Hi Team,

I know is basically the same of 
"All" domain controllers are unreachable by a sensor
and
"A" domain controllers are unreachable by a sensor

but when Cx trying to find the exact same wording, they can't find it, sometime is a bit confusing
would you mind add "A" domain controllers are unreachable by a sensor alert in this page?
or revise as "All/A domain controllers/controller are unreachable by a sensor"

![image](https://user-images.githubusercontent.com/101696604/197461013-0aace282-9352-4e5f-b2e2-ed8592089436.png)

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52af70b6-86d4-5dd4-0c17-d4e0a5f6e0ed
* Version Independent ID: 63d594b0-4656-1938-98da-da5494321df9
* Content: [Microsoft Defender for Identity reconnaissance phase security alerts](https://learn.microsoft.com/en-us/defender-for-identity/reconnaissance-alerts)
* Content Source: [ATPDocs/reconnaissance-alerts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/reconnaissance-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@jackson-yang-microsoft We've updated the documentation. Thanks for your contribution.
