### ISSUE TITLE
Domain Controller object is missing a $ sign

### ISSUE THREAD

**Issue by TonitoDux** [MicrosoftDocs/ATADocs#578]
[Enter feedback here]
Hi,

the PowerShell command "Set-ADServiceAccount gmsaAccountName -PrincipalsAllowedToRetrieveManagedPassword Host1" under "Sensor service fails to start" is missing a $ sign after Host1. It should be "Host1$".
When I tried entering only the DC name, or FQDN of the server I got an error in PowerShell telling me it could not find this object.

The whole command with the correction:

"Set-ADServiceAccount gmsaAccountName -PrincipalsAllowedToRetrieveManagedPassword Host1$"

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3de7f0b7-1c29-6714-51b9-75df6731ce25
* Version Independent ID: c6ada0cd-4fb8-b1eb-db34-206660e33e9f
* Content: [Troubleshooting Microsoft Defender for Identity known issues](https://learn.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues#sensor-failed-to-retrieve-group-managed-service-account-gmsa-credentials)
* Content Source: [ATPDocs/troubleshooting-known-issues.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/troubleshooting-known-issues.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. The page has been updated.
