### ISSUE TITLE
Strange character in log samples and non-conformant samples with RFC5424

### ISSUE THREAD

**Issue by pablocantos** [MicrosoftDocs/ATADocs#579]
I’ve been reviewing it and I could see a strange character (ï»¿) in the log samples. On the other hand, I'm missing the Structured Data before the MSG part. Could you clarify that? As in the samples it seems to me that these logs are not conformant with RFC5424.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff82a4d-1c0d-7d05-f383-78a5506dda02
* Version Independent ID: 02bd7bc8-76ca-2511-93cb-f3f3de46337d
* Content: [Microsoft Defender for Identity SIEM log reference](https://learn.microsoft.com/en-us/defender-for-identity/cef-format-sa)
* Content Source: [ATPDocs/cef-format-sa.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/cef-format-sa.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@pablocantos  - Thanks for your comment. We removed the strange characters that you noticed. Regarding your other points, the log samples are just examples, and therefore it's not a documentation issue. This is how the messages will appear in your syslog.

If you have further issues, please open a support ticket.

**Comment by pablocantos** [comment]
Thanks for your reply @dcurwin. I could see the documentation updated the strange character disappeared, thanks for that. However, the Syslog is still a non-conformant Syslog RFC5424.

This is a real log that I could see in my systems and I've anonymized it to share here:
`1 2023-01-19T01:14:59.958551+00:00 SOMEHOST CEF 12345 PassTheTicketSecurityAlert 0|Microsoft|Azure ATP|2.196.16033.30643|PassTheTicketSecurityAlert|Suspected identity theft (pass-the-ticket)|5|start=2023-01-19T00:02:14.061254Z app=Kerberos suser=someuser msg=some message from externalId=2200 cs1Label=url cs1=https://example.atp.azure.com/securityAlert/00000000-1111-2222-3333-444444444444 cs2Label=trigger cs2=new cs3Label=mSecUrl cs3=https://security.microsoft.com/alerts/aaaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee`

And this is not RFC5424 conformant because it doesn't have a "structured data" section. According to the RFC5424, to be conformat it should be this way (added a dash before the MSG):
`1 2023-01-19T01:14:59.958551+00:00 SOMEHOST CEF 12345 PassTheTicketSecurityAlert - 0|Microsoft|Azure ATP|2.196.16033.30643|PassTheTicketSecurityAlert|Suspected identity theft (pass-the-ticket)|5|start=2023-01-19T00:02:14.061254Z app=Kerberos suser=someuser msg=some message from externalId=2200 cs1Label=url cs1=https://example.atp.azure.com/securityAlert/00000000-1111-2222-3333-444444444444 cs2Label=trigger cs2=new cs3Label=mSecUrl cs3=https://security.microsoft.com/alerts/aaaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee`

**Comment by dcurwin** [comment]
@pablocantos  - As I wrote, this is not a documentation issue. I suggest you open a support ticket to see if the issue can be resolved to your satisfaction.

**Comment by pablocantos** [comment]
Thank you David!
