### ISSUE TITLE
Incomplete step by step to GPO Domain controller policy

### ISSUE THREAD

**Issue by SabrinaKay** [MicrosoftDocs/ATADocs#580]
I realize your section https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#event-id-8004
has incomplete step by step written.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#event-id-8004)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@SabrinaKay - Thanks for the helpful feedback. We've updated the section to be clearer (should be live soon).
