### ISSUE TITLE
What 

### ISSUE THREAD

**Issue by Mrlongmustache** [MicrosoftDocs/ATADocs#581]
I liked the article, it was very interesting and informative. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8df167b-3d6a-ebd1-4401-4596565b9238
* Version Independent ID: 56c40693-376f-4a86-ca85-5ecfd9cb3558
* Content: [What is Microsoft Defender for Identity? - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/what-is)
* Content Source: [ATPDocs/what-is.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/what-is.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks!
