### ISSUE TITLE
Error in documentation for creating the gMSA acccount

### ISSUE THREAD

**Issue by rekoilgzs** [MicrosoftDocs/ATADocs#585]
In the section for "Create a gMSA account" ( https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts#create-a-gmsa-account ) , I believe that the code box for the line explicitly commented to create the gMSA needs to have a variable name updated to match the variable declaration that was made in the previous steps - from "$gMSA_HostsGroup.Name" to "$gMSA_HostsGroupName".

![image](https://user-images.githubusercontent.com/11196769/211606172-37305a4c-202d-49ed-a944-5a028b56472c.png)

Without the update, it repeatedly failed with the following error:

![image](https://user-images.githubusercontent.com/11196769/211609116-a66a3376-a463-47fe-a06d-9adac662ffbc.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service account recommendations - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts#create-a-gmsa-account)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@rekoilgzs  - Thanks for noticing. We've updated the document.
