### ISSUE TITLE
Directory Service Accounts

### ISSUE THREAD

**Issue by shellymoore23** [MicrosoftDocs/ATADocs#586]
1.	Directory Service Accounts
a.	[[https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdefender-for-identity%2Fdirectory-service-accounts&data=05%7C01%7Cshellymoore%40microsoft.com%7Cf943684fbd66441666bd08daf96dceb1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638096547373905942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YacjBvrZAh2%2FJptzgwLUDsoMdZngakhwibFQ5YG%2FMiY%3D&reserved=0)](url)
b.	This article discusses granting URA permissions to the gMSA account but does not discuss potential problems when using GPO.
c.	I would like this article to be updated with a note that if customers use GPO to configure the “Logon on as a service” permission, they will need to ensure that “NT Service\All Services” is added to the GPO.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service account recommendations - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by shellymoore23** [comment]
Hi @dcurwin checking for updates on this. Thanks in advance!

**Comment by dcurwin** [comment]
@shellymoore23  - Thanks again for your suggestion. We've updated the document.
