### ISSUE TITLE
Troubleshooting Microsoft Defender for Identity known issues

### ISSUE THREAD

**Issue by shellymoore23** [MicrosoftDocs/ATADocs#587]
1.	Troubleshooting Microsoft Defender for Identity known issues
a.	[[https://learn.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdefender-for-identity%2Ftroubleshooting-known-issues&data=05%7C01%7Cshellymoore%40microsoft.com%7Cf943684fbd66441666bd08daf96dceb1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638096547373905942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E8we0LD%2FJQmtE8Z7I2ycAMCv50SmZmYw%2Fyogxa4bhlA%3D&reserved=0)](url)
b.	The troubleshooting article is specifically targeted toward resolving general issues – particularly hard-to-troubleshoot problems.
c.	I would like a section for diagnosing and resolving this scenario where “NT Service\All Services” is not granted “Logon as a Service” permissions.
                                                    i.     This link here looks to have specific steps for diagnosing this error
d.	[[https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/microsoft-defender-for-identity-azure-atp-deployment-and/ba-p/1676122#:~:text=Clustered%20to%20Flat.-,Sensor,-service%20%22Azure%20Advanced](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Ft5%2Fcore-infrastructure-and-security%2Fmicrosoft-defender-for-identity-azure-atp-deployment-and%2Fba-p%2F1676122%23%3A~%3Atext%3DClustered%2520to%2520Flat.-%2CSensor%2C-service%2520%2522Azure%2520Advanced&data=05%7C01%7Cshellymoore%40microsoft.com%7Cf943684fbd66441666bd08daf96dceb1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638096547373905942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L%2B9esqh%2F2SIEgs0ys8YMs%2FbcrHKzJ5PojHkkHWS%2FV8k%3D&reserved=0)](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3de7f0b7-1c29-6714-51b9-75df6731ce25
* Version Independent ID: c6ada0cd-4fb8-b1eb-db34-206660e33e9f
* Content: [Troubleshooting known issues - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/troubleshooting-known-issues)
* Content Source: [ATPDocs/troubleshooting-known-issues.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/troubleshooting-known-issues.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by shellymoore23** [comment]
Hi @dcurwin checking for updates on this. Thanks in advance!

**Comment by dcurwin** [comment]
@shellymoore23  - Thanks again for your suggestion. We've updated the document.

**Comment by shellymoore23** [comment]
Thank you so much!

Shelly Moore

Incident Manager US Public Sector
Hours: M-F 8am-5pm CST
Office: +1 (469) 775-0677

Microsoft Services Support:
https://serviceshub.microsoft.com<https://serviceshub.microsoft.com/>
Support ((24/7): 1-800-936-3100
Support (US NAT): 1-800-936-3200
GCC High: 1-877-966-7787
[cid:1e215f5a-59e4-4eb2-8ad6-a7715edae4f6]

Please @ me for Escalations and High Priority issues.
For feedback or concerns, please email my manager,  Kevin Dozier– ***@***.******@***.***>).


________________________________
