### ISSUE TITLE
Permissions to view settings

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/ATADocs#589]
Please add some information about what role is needed to view the MDI settings page. 

Security reader does not seem to be sufficient, but I would like some documentation to confirm what is actually required. 

This page states what is required for initial configuration but not for subsequent VIEWING
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Prerequisites - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/prerequisites)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your question. The information you're looking for is in https://learn.microsoft.com/en-us/defender-for-identity/role-groups. We've added a link from the Prerequisites section to that page.

More specifically to your case, Security reader allows you to view health issues and the about page in the settings. For a custom role, see Role Groups.
