### ISSUE TITLE
Everyone as permissions

### ISSUE THREAD

**Issue by xrysmu-bsd** [MicrosoftDocs/ATADocs#591]
I was reviewing this article and it references setting the everyone permission with read/write access.  Even if it was just read only isn't there a possibility to set it to a specific account?  This seem a poor security design unless I'm missing something or the article should be referencing a specific account.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-object-auditing)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by xrysmu-bsd** [comment]
David,
I saw this was opened and closed, does the closure mean the article is accurate?  If so are there any comments on whether or not the everyone setting is a risk factor, and if there are mitigations that can be taken if so, and if not a risk how the everyone setting is not as risky as it sounds?  Thanks, just seeking clarification as I've never provided comment before.

**Comment by f-bader** [comment]
Hi @xrysmu-bsd 

The everyone permission is not a permission but the auditing in active directory.
So this means that when somebody changes an object it will be logged in the event log.
And the everyone is meant to monitor actions regardless which user does change the object

Cheers, Fabian

**Comment by dcurwin** [comment]
@xrysmu-bsd : @f-bader  explained this well. There is no reason for concern.

**Comment by xrysmu-bsd** [comment]
Thanks for the clarification, much appreciated.
