### ISSUE TITLE
MDE / MDI integration incorrect

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/ATADocs#593]
[Enter feedback here]
As of Jan 2023, this portal redirects to M365 Defender portal for all tenants. It also appears that the MDE integration has been removed from old portal.  MDE still has the option for MDI integration; however, in my test tenant MDI does not.

Need to update this article with instructions for enabling MDE & MDI integration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 547b8a73-8547-5473-da56-14b9db11f538
* Version Independent ID: 547b8a73-8547-5473-da56-14b9db11f538
* Content: [Classic portal - Microsoft Defender for Identity integration with Microsoft Defender for Endpoint - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/classic-integrate-mde)
* Content Source: [ATPDocs/classic-integrate-mde.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/classic-integrate-mde.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by danaim1** [comment]
This Intergration will be removed from MDE soon too.

**Comment by dcurwin** [comment]
@davebirr  - And we will also update the documentation accordingly.
