### ISSUE TITLE
would like to know external ID and investigation guide for new alert

### ISSUE THREAD

**Issue by bellspeal** [MicrosoftDocs/ATADocs#595]
[Enter feedback here]
customer would like to know the external ID and investigation guide of New honeytoken alert and Suspicious certificate usage over Kerberos protocol (PKINIT).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8e6d13b-650d-b12b-5f80-dbe24fa0b329
* Version Independent ID: b8e6d13b-650d-b12b-5f80-dbe24fa0b329
* Content: [Microsoft Defender for Identity security alert guide - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/alerts-overview)
* Content Source: [ATPDocs/alerts-overview.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/alerts-overview.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
The PR was approved. When you're ready to publish, please type `#sign-off` in a new comment box, and click **Comment**.

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by danaim1** [comment]
Can I ask what do you use the external ID for?

**Comment by batamig** [comment]
Hi @bellspeal thanks again for writing into docs. I've asked @danaim1, our SME to advise. 
Can you clarify what you're using the external ID for?

**Comment by bellspeal** [comment]
hello @batamig 

Thank you for your reply and very soorry I did not notice your comments and reply late.

![image](https://github.com/MicrosoftDocs/ATADocs/assets/66524799/b81b4896-e7c8-4698-803f-c9b67cc630c8)
this "Unique External ID" column for new Honeytoken Alert and Suspicious certificate usage over Kerberos protocol (PKINIT). 

In my recognition, When Sentinel grab MDI alert, there is included this ID.

**Comment by batamig** [comment]
Thanks @bellspeal!
@danaim1 - does this clarification help and should we be updating the docs?

**Comment by batamig** [comment]
Hi @bellspeal 
I'm coming back here to update you that both the Suspicious certificate usage over Kerberos protocol (PKINIT) alert and all honeytoken alerts now have external IDs hosted on this page.
I know that you'd opened this issue a while ago - can you confirm that you have the information that you need? Was there any further feedback you'd had on this page?

**Comment by batamig** [comment]
We haven't heard back from you since the fix, so we're closing the issue for now. Feel free to add more comments and tag me if you have additional feedback. 
Thanks again for your contribution!
#please-close
