### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by cheapscotman** [MicrosoftDocs/ATADocs#596]
9. You'll then return to Auditing Entry. Make the following selections:

For Type select Success.

For Applies to select Descendant User objects.

Under Permissions, scroll down and select Clear all. There is no Clear all under permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-audit-policies)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@cheapscotman  - Thanks again for your comment. We've updated the documentation to make the step more clear.
