### ISSUE TITLE
Event ID 7045 Reference in "Audit Security System Extension" Subcategory

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/ATADocs#598]
Under [Configure Audit Policies](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-audit-policies), it references Event ID 7045 for Audit Policy "System" Subcategory "Audit Security System Extension". However when referencing this audit policy and subcategory at [Audit Security System Extension](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-security-system-extension) I do not see event ID 7045 listed on this page.

Is the Audit Policy "System" and Subcategory "Audit Security System Extension" specified on this page correct? If so, should the other page [Audit Security System Extension](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-security-system-extension) page be updated to also add 7045?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-object-auditing)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@aakash-shah  - Thanks for your question. These are two different services, and so the documentations are different.
