### ISSUE TITLE
Powersploit command does not exist in the powershell module

### ISSUE THREAD

**Issue by bekirdur** [MicrosoftDocs/ATADocs#601]
This command in this page doesn't work as this commandlet does not exist in powersploit powershell module:
Get-NetLocalGroupMember

The correct command looks like to be Get-NetLocalGroup
Get-NetLocalGroup   -   gets the members of a localgroup on a remote host or hosts

Ref: 
https://powersploit.readthedocs.io/en/stable/Recon/README/

However, the command needs to be tested to see if it creates the same effect at the MDI side.

Regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfe698-05a4-8d4c-75b8-024ab912e18c
* Version Independent ID: 4d58c76d-b7b5-9900-9c14-557f892cc54e
* Content: [Lateral movement playbook - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/playbook-lateral-movement?source=docs)
* Content Source: [ATPDocs/playbook-lateral-movement.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/playbook-lateral-movement.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @bekirdur, based on conversations with our stakeholders, it looks like this cmdlet does exist: https://powersploit.readthedocs.io/en/latest/Recon/Get-NetLocalGroupMember/

I'll be adding a link from our docs to theirs to clarify this point.
If this is still not working for you, please open a support ticket to continue the investigation. 
I'm going to close this for now but feel free to add more comments if you have additional feedback.
Thanks for contributing to docs! 
#please-close
