### ISSUE TITLE
Typosquatting

### ISSUE THREAD

**Issue by iliaselmatani** [MicrosoftDocs/ATADocs#605]
Typosquatting:
Download the Defender for Identity sensor from the [Microsoft 365 Defender portal](https://security.micrsoft.com/) in the Settings -> Identities -> Sensors page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Version Independent ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Content: [Quick installation guide - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/quick-installation-guide)
* Content Source: [ATPDocs/quick-installation-guide.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/quick-installation-guide.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@iliaselmatani  - Thanks for letting us know - it's been fixed.
