### ISSUE TITLE
Windows Laps (April 2023)

### ISSUE THREAD

**Issue by AndrewEmmett** [MicrosoftDocs/ATADocs#613]
Will this documentation be updated to clarify if this setting looks at Legacy LAPS or the new Windows Laps released in April 2023. It would be great if the rule itself evaluated both recommendations.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8ebcd07-610e-2dea-fdbb-40a48c67366f
* Version Independent ID: f8ebcd07-610e-2dea-fdbb-40a48c67366f
* Content: [Microsoft LAPS usage assessment - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-laps)
* Content Source: [ATPDocs/security-assessment-laps.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment-laps.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
@danaim1 - can you please advise?

**Comment by danaim1** [comment]
It's the previous one, I'll see if we can update to the new one in the product in the future

Thanks,
Daniel
________________________________

**Comment by batamig** [comment]
Thanks! @AndrewEmmett, please confirm whether this answers your question. I'm opening a backlog item to clarify this correctly in our docs.
#label:"backlog-item-created"

**Comment by AndrewEmmett** [comment]
@batamig , happy this answers the question. Would be great to see greater clarity in the documentation.
Thanks

**Comment by batamig** [comment]
Hi @AndrewEmmett, the doc page is now updated. See here: 
https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-laps#what-is-microsoft-laps

Feel free to continue commenting if you have any further questions or feedback.
