### ISSUE TITLE
Please add how each attribute maps to AD setting/powershell attributes

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/ATADocs#616]
Would be handy to know how to find if the following attributes are set, and/or how to adjust them:

- Do not require Kerberos preauthentication
- Store password using reversible encryption
- Password not required
- Password stored with weak encryption
- Kerberos AES encryption support
- Use Kerberos DES encryption types for this account

For example, through trial and error, some were easy to spot in the object properties page in AD, and also in powershell (```UseDESKeyOnly```, ```DoesNotRequirePreAuth```) but others I'm unable to find definitively in either.

That makes it hard to remediate!

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbfbdafc-2e4a-fea0-27cc-708293401980
* Version Independent ID: dbfbdafc-2e4a-fea0-27cc-708293401980
* Content: [Unsecure account attributes assessment - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-unsecure-account-attributes)
* Content Source: [ATPDocs/security-assessment-unsecure-account-attributes.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment-unsecure-account-attributes.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @SpitFire-666, you might be able to find more information in these docs:

- https://learn.microsoft.com/th-TH/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties
- https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd861342(v=ws.11)
- https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd871105(v=ws.11)
- https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/adac/introduction-to-active-directory-administrative-center-enhancements--level-100-

We're working on adding references to these articles inside our MDI docs. In the meantime, please let us know if these are helpful.

If you have more questions that these articles don't answer, I suggest that you open a support ticket.

**Comment by batamig** [comment]
Hi - I'm closing this issue now. Thanks again for writing into docs!
