### ISSUE TITLE
I would like to understand which groups are classified as "sensitive"

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/ATADocs#624]
This is to ensure no other accounts get added to them in future. I'm guessing one of the sensitive ones is Account Operators?

This will make it easier to remediate than deleting the dormant account.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6534bb97-1acf-8f6a-cb39-95ce198c52d4
* Version Independent ID: 6534bb97-1acf-8f6a-cb39-95ce198c52d4
* Content: [Dormant entities security assessment - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-dormant-entities)
* Content Source: [ATPDocs/security-assessment-dormant-entities.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment-dormant-entities.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @SpitFire-666, thanks for writing into docs! I'm tagging an SME to help answer this questions.
@danaim1 can you take a look please?

**Comment by batamig** [comment]
#label:"tagged-sme"

**Comment by batamig** [comment]
Hi @SpitFire-666, you can find a list of sensitive entities on this page: [Sensitive tags](https://learn.microsoft.com/defender-for-identity/entity-tags#sensitive--tags)

I'll add a link to this page to clarify. Please let me know if this helps your issue. 
#label:"backlog-item-created"

**Comment by batamig** [comment]
Hi @SpitFire-666 - this page is now updated with a more explicit link: [What are sensitive dormant entities?](https://learn.microsoft.com/defender-for-identity/security-assessment-dormant-entities#what-are-sensitive-dormant-entities)

Please let us know if you have any additional feedback.  Thanks for your contribution to docs!

**Comment by batamig** [comment]
Hi, it's been a week since my last comment.  I'm going to close this issue for now but welcome further feedback if you have more comments. You can continue commenting here as needed. 
Thanks again!
#please-close
