### ISSUE TITLE
Wrong text in "Quick installation guide"

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/ATADocs#625]
[Enter feedback here]

This information is wrong from your documentation:

Download the Defender for Identity sensor from the [Microsoft 365 Defender portal](https://security.microsoft.com/) in the Settings -> Identities -> Sensors page.

Settings doesnt show Identities:

![image](https://github.com/MicrosoftDocs/ATADocs/assets/46280077/233ae86f-75fe-4dcf-9ea6-d555a5571977)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Version Independent ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Content: [Quick installation guide - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/quick-installation-guide)
* Content Source: [ATPDocs/quick-installation-guide.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/quick-installation-guide.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
#label:"backlog-item-created"

**Comment by batamig** [comment]
Hi @bedo1976, this article now has the prerequisites listed at the top of the page to clarify that a license is needed before you start: [Quick installation guide](https://learn.microsoft.com/defender-for-identity/quick-installation-guide)

Please comment again if you have additional feedback.

**Comment by batamig** [comment]
Hi @bedo1976, I'm going to close this issue as it looks like it's been resolved. If that's not the case, or if you have additional feedback, feel free to reopen the issue or add more comments as needed.
Thank you for your contribution to Microsoft docs!
#please-close
