### ISSUE TITLE
How to install Microsoft Defender for Identity

### ISSUE THREAD

**Issue by Linas08** [MicrosoftDocs/ATADocs#628]
How to install direction's show 
Microsoft 365 Defender portal in the Settings -> Identities -> Sensors page.
but there is no Identities page under settings?

how to download installer?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Version Independent ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Content: [Quick installation guide - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/quick-installation-guide)
* Content Source: [ATPDocs/quick-installation-guide.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/quick-installation-guide.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Linas08, thanks for writing into docs!

If you don't see the Identities page, you might have a license or permissions issue. You need a Defender for Identity license and relevant roles and permissions. Please see the following content:

- [Types of Defender for Identity security groups](https://learn.microsoft.com/defender-for-identity/role-groups#types-of-defender-for-identity-security-groups)
- [Unified role-based access control (RBAC)](https://learn.microsoft.com/en-us/defender-for-identity/role-groups#unified-role-based-access-control-rbac)

If you have a Defender for Identity license and you're still having issues, please open a support ticket.
In the meantime, I'm also opening a backlog item to ensure that these prerequisites are clear in this article.

Please let me know if this information helps you. We appreciate your contribution to docs!

**Comment by batamig** [comment]
#label:"backlog-item-created"

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
