### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by GammaProtocol** [MicrosoftDocs/ATADocs#631]
Network Security: Restrict NTLM: NTLM authentication in this domain "Enable All" is not a option under the latest functional level. Choices are: 

- Disable
- Deny for domain accounts to domain servers
- Deny for domain accounts
- Deny for domain servers
- Deny all

![image](https://github.com/MicrosoftDocs/ATADocs/assets/23410069/e514452a-41b1-4d78-aaa6-a4943e9d93f2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-audit-policies)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.
#label:"backlog-item-created"

**Comment by batamig** [comment]
Hi @GammaProtocol, thanks for writing into docs! 
We checked and our docs here are correct. It looks like you're looking for the **Network Security: Restrict NTLM: NTLM authentication in this domain** setting. However, we required the **Network security: Restrict NTLM: Audit NTLM authentication in this domain**.

I'm going to close this issue for now as there isn't a doc update needed. However, please feel free to continue commenting here if you have more feedback.
We appreciate your contribution to docs!
#please-close

**Comment by GammaProtocol** [comment]
Apologies for giving you guys the run around
