### ISSUE TITLE
Enable auditing on an Exchange object, has no step related to Exchange object

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/ATADocs#633]
Why is this section "Enable auditing on an Exchange object", has no direct correlation with **Exchange Object**, the setting is about using ADSI to edit Configuration? This misled and causing confusion to my customer, could you please assist to check?
https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#enable-auditing-on-an-exchange-object

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#enable-auditing-on-an-exchange-object)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @AndNovian, thanks for your feedback! If you're internal to Microsoft (you refer to "your customer"), please communicate internally by email so that we can include the relevant stakeholders. I'll try and locate you so that we can be in touch.

**Comment by batamig** [comment]
closing to continue internally.
#please-close
