### ISSUE TITLE
Everyone - Write All?

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/ATADocs#636]
Are you able to elaborate on the "Enable auditing on an Exchange object" section.  As in, what making this change is doing and why we're giving the Everyone group Write All?  In 2023 that doesn't read like something we should be doing anymore in a only give the least privileges required world of IT.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by martin77s** [comment]
Please follow the instructions carefully (step 7). 
The "Everyone group Write All" is not a DACL (who has access to an object and who is denied access) requirement, but a SACL (which access-granted or access-denied events are to be recorded for **auditing**) requirement.

**Comment by batamig** [comment]
Hi @mattsmacblog, please let us know if this solves your issue. Thanks!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
