### ISSUE TITLE
Locked Out

### ISSUE THREAD

**Issue by npai20** [MicrosoftDocs/ATADocs#638]
Both 'Defender for Identity' and 'Azure AD Identity Protection' appears to be Locked Out on my https://security.microsoft.com/ . How do I unlock this feature or the underlying account ?

![image](https://github.com/MicrosoftDocs/ATADocs/assets/55107412/421fdf0c-29ec-4759-a7b7-e1674df719ed)

**Comment by batamig** [comment]
Hi @npai20, this may be an issue with licensing or permissions. 
Please check with your admin or open a support ticket to handle your specific use case. The support team can help us update the docs if there's anything missing or unclear. 
I'm closing this in the meantime, but feel free to add more comments if you have feedback on the documentation.
#please-close
