### ISSUE TITLE
MDI Action Account Delegations

### ISSUE THREAD

**Issue by Crowbar3** [MicrosoftDocs/ATADocs#639]
The MDI action account shows it needs rights for Reset Password, PwdLastSet, and UserAccountControl.  Each of these are explained as to why they are needed and it all aligns to what the remediation account would do.

What is not explained is why we need to delegate the account for read/write members on descendant group objects.  Which group objects would it be writing to?  Is this delegation necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Version Independent ID: 9942b0e9-6ca2-fe02-d1df-0ac98d78c928
* Content: [Manage action accounts - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/manage-action-accounts)
* Content Source: [ATPDocs/manage-action-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/manage-action-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Crowbar3, thanks for writing into docs! I'm tagging a subject matter expert here to advise. @martin77s, can you take a look?

**Comment by batamig** [comment]
Hi @Crowbar3, I'm returning to your question after our internal investigation. 
These permissions aren't mandatory right now but create an environment to support roadmap features. 

For more information about roadmap features, please use our [TechCommunity forum](https://techcommunity.microsoft.com/t5/microsoft-defender-for-identity/bd-p/AzureAdvancedThreatProtection), where we have experts available to discuss this more, or open a support ticket. 

In the meantime, I'll see if we can clarify the docs to indicate what's mandatory and what isn't. 
Thanks for your contribution to docs!

**Comment by batamig** [comment]
Hi @Crowbar3, I've updated these docs to indicate that this step is optional. 
Do you have any additional feedback on this issue?

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
