### ISSUE TITLE
Unclear Deleted Objects documentation

### ISSUE THREAD

**Issue by alexhass** [MicrosoftDocs/ATADocs#640]
It is not clear from documentation what $Identity = 'CONTOSO\mdisvc' is. User or group?

It is not documented at all. It would be clear if you document that a security group need to be created in AD and the gMSA user need to e added. And do not hide it in inline documentation, please.

You missed to provide the powershell commands for this:
```
New-ADGroup -Name "mdiUsr01Group" -SamAccountName mdiUsr01Group -GroupCategory Security -GroupScope Universal -DisplayName "mdiUsr01Group" -Description "Microsoft Defender - Members of this group are allowed to monitor Deleted Objects in AD"
Add-ADGroupMember -Identity "mdiUsr01Group" -Members mdiSvc01$
```

Than change the line:
`$Identity = 'CONTOSO\mdisvc'
`
to :
`$Identity = 'CONTOSO\mdiUsr01Group'
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service account recommendations - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by martin77s** [comment]
I moved the note on the group required for the gMSA from the code snippet to a note block above it, and updated the code snippet to handle the group creation if needed.

**Comment by batamig** [comment]
Thanks for the quick fix, @martin77s! @alexhass, please let us know if this helps your issue.

**Comment by alexhass** [comment]
Thanks for the quick fix. I like the code change.

**Comment by alexhass** [comment]
Just tested it in a fresh domain. The code has a bug.

`Add-ADGroupMember -Identity $group -Members ('{0}$' -f $account)
`

Need to be 
`Add-ADGroupMember -Identity $group -Members ('{0}$' -f $Identity)`

**Comment by alexhass** [comment]
How about adding a Description to mdiSvc01Group, too? :-)

**Comment by batamig** [comment]
Thanks @alexhass! @martin77s, any thoughts?

**Comment by martin77s** [comment]
@batamig 
Already made the changes to the snippet.

**Comment by batamig** [comment]
Great- thanks so much. @alexhass - please check again and let us know if you have any further feedback.

**Comment by alexhass** [comment]
I’m fine. Thank you.
