### ISSUE TITLE
Missing Installation Steps

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/ATADocs#641]
In the installation steps, it says to go to Settings > Identities > Sensor pages and then to copy the access key. Ther ei sno access key on this page. It only appears when you click the Add Sensor button. This is shown in the video, but not in the written steps.

It is also worth noting that the installation download is blocked by pop-ups blockers. So, you may want to note that pop-ups need to be allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Version Independent ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Content: [Quick installation guide - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/quick-installation-guide)
* Content Source: [ATPDocs/quick-installation-guide.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/quick-installation-guide.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.
#label:"backlog-item-created"

**Comment by thalpius** [comment]
I validated the steps and it was indeed missing the "Add sensor" part. I also included additional text about the pop-up blocker. Thanks @DontNeedNoGit 🙏🏻

https://github.com/MicrosoftDocs/ATADocs/pull/645

**Comment by batamig** [comment]
Thanks @thalpius! We've included both of your changes and the content should now be updated.
Please let us know if there's any further feedback here!
