### ISSUE TITLE
Identities portion missing to download sensor

### ISSUE THREAD

**Issue by Mykness** [MicrosoftDocs/ATADocs#643]
The video and documentation is a bit out of date, there is no "identity" section in the settings menu anymore. Not sure where to get the sensor, checked MS documentation, but still a bit roadblocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Version Independent ID: 1f9554f0-2efb-a580-c897-9a809a5de54d
* Content: [Quick installation guide - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/quick-installation-guide)
* Content Source: [ATPDocs/quick-installation-guide.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/quick-installation-guide.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**
![ms-git](https://github.com/MicrosoftDocs/ATADocs/assets/141252783/43c53a21-dae8-44b3-9c65-5e1ef2a211d4)

**Comment by batamig** [comment]
Hi @Mykness, thanks for writing into docs.
Looking at your screenshot, you should have a **Settings** area named **Identities**. 
If you don't see this, please verify that you have a Defender for Identity license and relevant permissions. If, after verifying that you do have a license and are signing in with the relevant role, you still don't see this area, please open a support ticket to resolve your issue.

I'm going to close this issue for now but feel free to continue commenting if you have additional feedback on the documentation. Support will also be in touch with us about any updates needed after working on your ticket.
We appreciate your contribution to docs!
#please-close
