### ISSUE TITLE
Unclear language

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/ATADocs#644]
Your FAQ states : 
How many Defender for Identity sensors do I need?
We recommend that you make sure that each of your domain controllers is covered by a Defender for Identity sensor or standalone sensor. For more information, see [Defender for Identity sensor sizing](https://learn.microsoft.com/en-us/defender-for-identity/capacity-planning#sizing).

If you think that each DC should have its own sensor, state that. And put it into the installation guide.

"Is Covered by" can mean that it is enough with one sensor somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b234d2-4a23-99df-d67f-2891645145ea
* Version Independent ID: ded9e856-0cd7-79d0-9f9c-e66adca87863
* Content: [Microsoft Defender for Identity frequently asked questions - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/technical-faq#how-many-defender-for-identity-sensors-do-i-need)
* Content Source: [ATPDocs/technical-faq.yml](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/technical-faq.yml)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by thalpius** [comment]
It seems to be fixed ☺️

https://github.com/MicrosoftDocs/ATADocs/commit/34c7928128bb3539e6b5e7a10a18efb72e68233f

**Comment by batamig** [comment]
Indeed, thanks for the note @thalpius!

@Tarjei-stavanger, we've updated this item to clarify, that yes - you should have a sensor for each of your domain controllers. Please feel free to close this issue or continue commenting if you have further feedback. 

We appreciate your contribution to docs!

**Comment by Tarjei-stavanger** [comment]
The language has been fixed and is now clear about the recommendation.

Thanks!
