### ISSUE TITLE
Something not right on Deleted Objects Container permissions

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/ATADocs#646]
1. Is it really **required** to have a seurity group to which the gMSA is added that has access to the Deleted Objects Container? Why not just add the gMSA account directly if we're ok with that? I don't remember this from earlier versions of the documentation?

2. Looking at the PowerShell code to accomplish this, it seems like it's not correct. Sure, you create a GROUP but look at the part where you grant the permissions:
```
# Grant the 'List Contents' and 'Read Property' permissions to the user or group:
$params = @("$deletedObjectsDN", '/G', ('{0}\{1}:LCRP' -f ([adsi]'').name.Value, $Identity))
C:\Windows\System32\dsacls.exe $params
```
Seems like you add $Identity which is the USER, not the group.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Version Independent ID: 12a9a5e8-afc3-7554-6a0b-248fae64a53f
* Content: [Directory Service account recommendations - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/directory-service-accounts)
* Content Source: [ATPDocs/directory-service-accounts.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/directory-service-accounts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
HI @JonesMikael, thank you for your question. We're investigating and will get back to you shortly, and will also plan a doc update to clarify as needed.

@martin77s, can you please take a look?

**Comment by martin77s** [comment]
Yes, it is required, as you cannot add permissions there to a gMSA class object, only to a user or a group.
As for the code, if you look a few lines above in the code example, you'll see that it overwrites the initial $identity value with the group's name
```
$Identity = $group.Name
```

**Comment by batamig** [comment]
thanks @martin77s! @JonesMikael, please let us know if this helps your question and we can close this issue.

**Comment by batamig** [comment]
Closing this issue as we haven't heard any updates. Please feel free to get in touch again if you have further feedback.
#please-close
