### ISSUE TITLE
Open Port 443 when proxy is configured

### ISSUE THREAD

**Issue by LennardMa** [MicrosoftDocs/ATADocs#647]
Hello,

it is recommended to allow the MDI sensor connection to the internet by configuring a proxy, like is common in larger organizations. But in the Port list below, it is written that you have to allow Port 443. This is only necessary if you don't have a proxy configured, correct? If yes, I would wish there was an indication in the ports table that it's either 443 OR Proxy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Prerequisites - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/prerequisites)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by martin77s** [comment]
Updated the doc to indicate that the connectivity required is either directly on port 443 or through a proxy.

**Comment by batamig** [comment]
thanks @martin77s! 
@LennardMa, I'm going to close this PR for now but feel free to continue commenting if you have further comments on docs. We appreciate your contribution!
#please-close
