### ISSUE TITLE
Update to reflect CA

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/ATADocs#648]
Defender for Identity is great stuff, love the expansions lately.
I would like to note that, with the expansion for coverage of CS/CA environments (see [here](https://techcommunity.microsoft.com/t5/microsoft-365-defender-blog/microsoft-defender-for-identity-expands-its-coverage-with-new-ad/ba-p/3894215)) the article can use an overhaul. Especially with the graphic (that I see used a lot on the internet) requiring an update.
Hope it helps, thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d74f052e-fd05-b96e-fb2a-0f67b7a6d4da
* Version Independent ID: 80591357-4e2e-be6c-e31f-c92b2d5215b0
* Content: [Architecture - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/architecture)
* Content Source: [ATPDocs/architecture.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/architecture.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @jotheman0303, thanks for writing into docs. Glad to hear that this image gets used often - and I'll take it back to the team to make sure this article is up to date. I'll reply when we have an update ready.

We appreciate your contribution!

**Comment by batamig** [comment]
Hi @jotheman0303, I'm writing to update you that the image is now updated to include ADCS and the article is somewhat refreshed. Feel free to take another look and write back if you think there's something still missing. 
Thanks again for this feedback!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
Thanks for your contribution!
#please-close
