### ISSUE TITLE
missing information on Azure AD joined only systems

### ISSUE THREAD

**Issue by PatrickF11** [MicrosoftDocs/ATADocs#651]
There are only information on configuring the group policy for all computers except domain controllers.
But what to do, when just using azure ad joined only devices, no hybrid joined devices? Is there nothing to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f062e9b-4e70-b4cf-df2c-ac6600d3195f
* Version Independent ID: 7f062e9b-4e70-b4cf-df2c-ac6600d3195f
* Content: [Configure SAM-R to enable lateral movement path detection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/remote-calls-sam)
* Content Source: [ATPDocs/remote-calls-sam.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/remote-calls-sam.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @PatrickF11 and thanks for your feedback! I'm tagging a subject matter expert to advise, and we'll update the docs as needed accordingly.

@martin77s, can you take a look?

**Comment by batamig** [comment]
Hi @PatrickF11, thanks again for writing into docs for this procedure. We've just added this content to our docs, and I invite you to take a look here: [Configure a Device profile for Microsoft Entra joined devices only](https://learn.microsoft.com/en-us/defender-for-identity/deploy/remote-calls-sam#configure-a-device-profile-for-microsoft-entra-joined-devices-only). 

Please let us know if this helps your situation and we should close the issue. We appreciate your contribution!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
