### ISSUE TITLE
Further detail regarding MDI support on Windows Server 2012

### ISSUE THREAD

**Issue by alicain** [MicrosoftDocs/ATADocs#653]
[Enter feedback here]

The following article regarding MDI support on Windows Server 2008 R2 

[End of support for Microsoft Defender for Identity on Windows Server 2008 R2 - Microsoft Community H...](https://techcommunity.microsoft.com/t5/microsoft-defender-for-identity/end-of-support-for-microsoft-defender-for-identity-on-windows/m-p/3248016)

Includes the following:

"How will this affect your organization:

For two months, the sensor will continue to function with all the functionality available up to June 15th, 2022. After this two-month period, starting August 15th, 2022, the sensor will no longer function on Windows Server 2008 R2 platforms. There will be no Defender for Identity support available for any sensors running on a Windows server 2008 R2 operating system."

 

The Defender for Identity sensor requirements section on Learn states the following but is not clear if the sensor will cease to function at that point or not:

"Windows Server 2012 and Windows Server 2012 R2 will reach extended end of support on October 10, 2023. You should plan to upgrade those servers as Microsoft will no longer support the Defender for Identity sensor on devices running Windows Server 2012 and Windows Server 2012 R2."

[Prerequisites - Microsoft Defender for Identity | Microsoft Learn](https://learn.microsoft.com/en-us/defender-for-identity/prerequisites#defender-for-identity-sensor-requirements)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e18c2-8abe-fd65-57e0-506e106866e6
* Version Independent ID: 42816160-c911-abd8-2a0d-a96c6311eea3
* Content: [Prerequisites - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/prerequisites?source=docs#defender-for-identity-sensor-requirements)
* Content Source: [ATPDocs/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @alicain, thanks again for your feedback. 

Our docs are updated with more information about legacy systems - please see [Legacy operating systems](https://learn.microsoft.com/en-us/defender-for-identity/prerequisites?source=docs#legacy-operating-systems) and let us know if this is clearer.

Looking forward to hearing back from you!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
