### ISSUE TITLE
MDI on ADCS servers - additional info

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/ATADocs#654]
The MDI sensor can now be used on AD CS servers (Issuing CAs). The installation may fail due to "connection errors". Despite the fact that connectivity is in order, still this message is displayed. It turns out that the server certificate may not be not trusted, because the corresponding Root CA certificate is not present on the CA server - this is because CA servers are exempt from automatic certificate trus list (CTL) updates. So this error is not encountered on DCs and ADFS servers, but may be new for sensor installations on AD CS servers. Maybe it is good to add this information to the documentation (prerequisites)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c37c4c7f-22ca-16c4-9060-4e587f9e5ad1
* Version Independent ID: c37c4c7f-22ca-16c4-9060-4e587f9e5ad1
* Content: [Install the sensor - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/install-sensor)
* Content Source: [ATPDocs/install-sensor.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/install-sensor.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
HI @andrePKI, thanks for the feedback! 
We've now added the certificates to the [prerequisites](https://learn.microsoft.com/en-us/defender-for-identity/deploy/install-sensor#prerequisites) as requested. I'm going to close this issue now, but feel free to continue commenting if you have more comments. 

We appreciate your contribution to docs! 
#please-close

**Comment by andrePKI** [comment]
Excellent! (just a small typo there: "you may rec**ie**ve a connection error" should read **receive**.
