### ISSUE TITLE
Type field values on Server 2022 are Allow and Deny, not Success 

### ISSUE THREAD

**Issue by SiloReed** [MicrosoftDocs/ATADocs#655]
Step 9 a in the [section](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-object-auditing) reads: "For Type select Success."  But on Windows Server 2022 the available options in the Type dropdown are "Allow" or "Deny". 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b032a29d-2d3a-d737-28fb-3e6632a667e2
* Version Independent ID: b75dd591-4cd7-259a-1fe7-a581d6e356c9
* Content: [Configure Windows Event collection - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#configure-object-auditing)
* Content Source: [ATPDocs/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @SiloReed, our team validated this procedure again and found that the current docs are correct. 
If this issue persists, please open a support ticket to handle your specific scenario. 

I'm going to close this issue for now, but feel free to add more comments if you have additional feedback for docs. Thanks for your contribution!

#please-close
