### ISSUE TITLE
MDI User RBAC permissions

### ISSUE THREAD

**Issue by aaronsgutierrez** [MicrosoftDocs/ATADocs#658]
Please clarify the following permissions needed for (https://learn.microsoft.com/en-us/defender-for-identity/role-groups#unified-role-based-access-control-rbac) *MDI User: microsoft.xdr/configuration/security/manage*
It does not conform to the rest of the roles in the M365D portal.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 506d38e9-6b3d-12df-8c1f-808be86d349b
* Version Independent ID: dbb31d1c-bcf7-eb6c-c004-4c1946acad4f
* Content: [Role groups - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/role-groups)
* Content Source: [ATPDocs/role-groups.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/role-groups.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by ortsemah** [comment]
Hi, I'm Or Tsemah, MDI product manager working on permissions, can you please clarify what you mean by "It does not conform to the rest of the roles in the M365D portal" ?

**Comment by batamig** [comment]
Hi @aaronsgutierrez, we'd like to understand your issue better. Are you able to add any more details?
