### ISSUE TITLE
No information regarding how this was detected nor how to resolve

### ISSUE THREAD

**Issue by expsimonsr** [MicrosoftDocs/ATADocs#659]
No information is supplied in this article about how this MDI finding was determined nor how to resolve it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40a1d1a1-76d2-767b-7aa1-1777d142bc11
* Version Independent ID: 40a1d1a1-76d2-767b-7aa1-1777d142bc11
* Content: [Remove access rights on suspicious accounts with the Admin SDHolder permission - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-remove-suspicious-access-rights)
* Content Source: [ATPDocs/security-assessment-remove-suspicious-access-rights.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment-remove-suspicious-access-rights.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @expsimonsr, thanks again for your feedback!
We've added more information [here](https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-remove-suspicious-access-rights#how-do-i-use-this-security-assessment-to-improve-my-organizational-security-posture) and hope it's helpful.
Please let us know if you have any additional comments. Thanks!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
