### ISSUE TITLE
CRL CDP URLs

### ISSUE THREAD

**Issue by tobiasabele** [MicrosoftDocs/ATADocs#662]
Often fell over CRL CDP URLs missing to be allowed through proxies or firewall. Maybe worth mentioning in the docs here. So for example http://www.microsoft.com/pkiops/crl is needed to be accesible. This always happens when the firewall/proxyadmins really do explicit whitelisting of URLs for the domain controllers.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7823584-21cb-81b3-7e2b-8fd521bc3ae1
* Version Independent ID: f312a146-a76c-9adb-0e36-f0f98d91051a
* Content: [Configure endpoint proxy and Internet connectivity settings - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-proxy)
* Content Source: [ATPDocs/configure-proxy.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-proxy.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment! We'll investigate and get back to you.
#label:"backlog-item-created"

**Comment by batamig** [comment]
Hi @tobiasabele, thanks for your contribution! 
The docs are now updated with the URLs to allow. Please see [Enable access to Defender for Identity service URLs in the proxy server](https://learn.microsoft.com/en-us/defender-for-identity/configure-proxy#enable-access-to-defender-for-identity-service-urls-in-the-proxy-server).

Please check and confirm that this is clear for you. We appreciate your feedback on the docs!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
