### ISSUE TITLE
Typo in first code block

### ISSUE THREAD

**Issue by coaldric** [MicrosoftDocs/ATADocs#666]
Typo in first code block

"ninrm quick config"

should be 

"winrm quickconfig"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62f240ce-e9e6-2496-305a-26d027f02783
* Version Independent ID: 05a9a02a-c556-8e91-34fd-909a1da6c2b3
* Content: [Configure Windows event forwarding - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/configure-event-forwarding)
* Content Source: [ATPDocs/configure-event-forwarding.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/configure-event-forwarding.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @coaldric, thanks for your contribution! The docs are now updated to read "winrm quickconfig" as you suggested.
I'm closing this issue for now, but feel free to either continue commenting or write in again if you have more feedback. 
Thanks!
#please-close
