### ISSUE TITLE
Can I collect events 4768 and 4769

### ISSUE THREAD

**Issue by vbianconi88** [MicrosoftDocs/ATADocs#668]
Hello team

Many thanks for the very well written documentation. 

Can I please ask if it would be possible to configure the sensor to collect logs that aren't listed in here: https://learn.microsoft.com/en-us/defender-for-identity/deploy/event-collection-overview ?

More specifically, can the sensor be configured to collect event logs 4768 and 4769, please?

**Comment by batamig** [comment]
Hi @vbianconi88, thanks for writing into docs. Only the events listed in the docs are those that are supported for collection with Defender for Endpoint. If you'd like to collect other events, I suggest you contact the support team to understand how Microsoft tools can be answer your teams needs for these events. 

I'm going to close this issue for now, but feel free to continue commenting if you have specific comments on the docs. We appreciate your contributions!
#please-close
