### ISSUE TITLE
Audit config discrepency

### ISSUE THREAD

**Issue by Ayrezy** [MicrosoftDocs/ATADocs#670]
In the https://learn.microsoft.com/en-us/defender-for-identity/deploy/configure-windows-event-collection#configure-advanced-audit-policy-settings section of this page we detail to enable the audit events for both success and failure. However, the following events do not actually support failure configurations:

Account Management: Security Group Management: https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-security-group-management

Account Management: Computer Account Management: https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-computer-account-management

System: Security System extension: https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-security-system-extension

The docs should be updated to reflect these settings as being superfluous. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4de08b4-780d-2ea2-239b-5f28e7e7c7e9
* Version Independent ID: b4de08b4-780d-2ea2-239b-5f28e7e7c7e9
* Content: [Configure audit policies for Windows event logs - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/deploy/configure-windows-event-collection)
* Content Source: [ATPDocs/deploy/configure-windows-event-collection.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/deploy/configure-windows-event-collection.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @Ayrezy - I'm closing this so that we can communicate internally. Thanks!
