### ISSUE TITLE
Suggestion - a query or more info to help track down simple LDAP auths

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/ATADocs#671]
I know I've seen a log analytics query to discover simple LDAP auths which has a lot of detail compared to the basic report that Secure Score shows.

It would be great if it could be included or referenced on this page. Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64b0da12-cea4-e125-6a6c-bde55755e28e
* Version Independent ID: 64b0da12-cea4-e125-6a6c-bde55755e28e
* Content: [Clear text exposure assessment - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/security-assessment-clear-text)
* Content Source: [ATPDocs/security-assessment-clear-text.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/security-assessment-clear-text.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks @SpitFire-666! I'm going to investigate and get back to you.

**Comment by batamig** [comment]
Hi @SpitFire-666 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. 

I recommend that you ask this question in our [TechCommunity](https://techcommunity.microsoft.com/t5/microsoft-defender-for-identity/bd-p/AzureAdvancedThreatProtection) forum for Defender for Identity, where product experts are available to answer questions like these. We already have a backlog open for our team, so if there's a response with a relevant query, we can add it to that work item and make the update in the docs. 

I'm going to close this issue for now but feel free to tag me if you have any further feedback.
We appreciate your contributions!

#please-close
