### ISSUE TITLE
Prerequisites do not mention the M365 F5 SKUs as including an MDI license

### ISSUE THREAD

**Issue by Jon-Wojan** [MicrosoftDocs/ATADocs#675]
[Enter feedback here]
The PreReqs section of this doc only lists E5/A5/G5 licenses as having an MDI license, however F5 also includes an MDI entitlement. This is noted here:

https://m365maps.com/files/Microsoft-365-F5.htm

Please update the pre-reqs section to include this Frontline Worker SKU.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0adc0040-f198-edd7-b47f-f7ad9ad2c609
* Version Independent ID: 0adc0040-f198-edd7-b47f-f7ad9ad2c609
* Content: [Prerequisites - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/deploy/prerequisites?source=docs)
* Content Source: [ATPDocs/deploy/prerequisites.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/deploy/prerequisites.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.
