### ISSUE TITLE
Clarification regarding "non-Windows and mobile devices"

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/ATADocs#677]
> Does Defender for Identity monitor only domain-joined devices?
> No. Defender for Identity monitors all devices in the network performing authentication and authorization requests against Active Directory, including non-Windows and mobile devices.

I would like to understand better how MDI monitors "non-Windows and mobile devices"... is it meaning NNR and SAM-R, or is it something else altogether?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b234d2-4a23-99df-d67f-2891645145ea
* Version Independent ID: ded9e856-0cd7-79d0-9f9c-e66adca87863
* Content: [Microsoft Defender for Identity frequently asked questions - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/technical-faq)
* Content Source: [ATPDocs/technical-faq.yml](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/technical-faq.yml)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @LijuV-MSFT, this doesn't use NNR/SAM-R. MDI monitors user / identity authentications coming from all devices in the network.

I suggest we continue internally if you need more clarifications, and I can loop in the relevant focal points as needed.

I'm going to close this issue for now, but again - please be in touch internally if you have more questions. Thanks!
#please-close
