### ISSUE TITLE
Verify security alert functionality steps require non-MDI licenses

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/ATADocs#678]
The steps to verify sensor functionality asks one to go to the Devices section of the Defender portal.  Devices is only accessible if MDE licenses are available in the tenant.  It is not possible to complete the published verification step if only MDI licenses are available.  Please update the **Verify security alert functionality** section with steps that work correctly with only an MDI license.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef81d67-f052-1f48-d344-73658bb240fd
* Version Independent ID: 9ef81d67-f052-1f48-d344-73658bb240fd
* Content: [Configure sensor settings - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/deploy/configure-sensor-settings#verify-security-alert-functionality)
* Content Source: [ATPDocs/deploy/configure-sensor-settings.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/deploy/configure-sensor-settings.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @dloder0, thanks again for writing into docs. If you're unable to access the **Devices** page, you can also locate your device from elsewhere in the Defender portal, such as by searching for the device name.

We're updating the docs to reflect this and appreciate your contribution! 
I'm going to close this for now but feel free to tag me in further comments if you have more feedback on the docs. 
#please-close
