### ISSUE TITLE
Defender for Identity sizing tool validity

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/ATADocs#679]
According to the repo for the [Defender for Identity sizing tool], it's 4 years old.
Is it still valid and necessary? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb046bc-b71e-195f-d67e-2f126ec0aa0c
* Version Independent ID: 2fb046bc-b71e-195f-d67e-2f126ec0aa0c
* Content: [Plan capacity for deployment - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/deploy/capacity-planning)
* Content Source: [ATPDocs/deploy/capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/deploy/capacity-planning.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @gb5757870, thanks for writing into docs!
Yes, the sizing tool is still relevant when working with domain controllers, to make sure that you have the required resources to run the sensor. 

Are there any other clarifications I can help you with?

**Comment by gb5757870** [comment]
I did notice that Server 2019 and Server 2022 aren't on there. Which is partially whyI thought this might have been redundant

**Comment by batamig** [comment]
Thanks - I recommend you ask about this in our [Tech Community forum](https://techcommunity.microsoft.com/t5/microsoft-defender-for-identity/bd-p/AzureAdvancedThreatProtection) where our team is available to answer questions about product features, or open a support ticket if you have an issue.

I'm going to close this work item for now but appreciate your feedback! Please feel free to continue commenting if you have additional updates.
#please-close
