### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/ATADocs#680]
The content on this page here - https://learn.microsoft.com/en-us/defender-for-identity/deploy/configure-proxy#test-connectivity

Appears to the same as at the start of this page - https://learn.microsoft.com/en-us/defender-for-identity/deploy/test-connectivity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5eff576d-c934-f341-25a0-b229389e541a
* Version Independent ID: 5eff576d-c934-f341-25a0-b229389e541a
* Content: [Verify connectivity to the Defender for Identity service - Microsoft Defender for Identity](https://learn.microsoft.com/en-us/defender-for-identity/deploy/configure-proxy)
* Content Source: [ATPDocs/deploy/configure-proxy.md](https://github.com/Microsoft/ATADocs/blob/main/ATPDocs/deploy/configure-proxy.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @gb5757870, thanks so much for this feedback! Indeed - we should only list this procedure once. 
I've opened a backlog item for this to get it fixed in an upcoming sprint.

**Comment by batamig** [comment]
Hi @gb5757870, I'm coming back to say that our work item was completed and the duplicated content removed.
I'm going to close this issue as fixed but feel free to tag me in any additional feedback you might have.

Thanks for contributing to our docs!
#please-close
