### ISSUE TITLE
ATA Update 

### ISSUE THREAD

**Issue by nicogis** [MicrosoftDocs/ATADocs#684]
In this page the [link ](https://support.microsoft.com/en-us/topic/description-of-update-3-for-microsoft-advanced-threat-analytics-1-9-954cb9b7-9646-78ce-2000-2a257b64df7c) last version of ATA (1.9.7576.49398) isn't available (error 404 not found)

**Comment by batamig** [comment]
Hi @nicogis, thanks for writing into docs about this! Please report a support ticket about this issue as it's not related to our docs on learn.microsoft.com.
 
Note that the [mainstream support](https://support.microsoft.com/lifecycle/search?alpha=Advanced%20Threat%20Analytics) of Microsoft Advanced Threat Analytics (ATA) ended on January 12, 2021. Only extended support will be continued until January 13, 2026.

I'm going to close this issue for now, but feel free to open further issues if you have comments on the docs content. 

#please-close
