### ISSUE TITLE
broken link for [Change the ATA Center certificate]

### ISSUE THREAD

**Issue by billypms** [MicrosoftDocs/ATADocs#85]
link is incorrect (404) in this section:

 > If you cannot export the private key, you must create a new certificate and deploy it to ATA, as described in [Change the ATA Center certificate](modifying-ata-config-centercert.md), and then export it. 

should link to same guidance here: https://docs.microsoft.com/en-us/advanced-threat-analytics/modifying-ata-center-configuration#the-ata-center-certificate

**Comment by rkarlin** [comment]
this was taken care of, thanks
