### ISSUE TITLE
This policy breaks Citrix and RDP logins on pre-Server 2016 systems

### ISSUE THREAD

**Issue by cmilte-lsuhsc** [MicrosoftDocs/ATADocs#92]
Within minutes of enabling this policy all RDP and Citrix logins to pre-Server 2016 systems were blocked. I backed out of the policy, but the registry change on the servers wasn't reversed. Rather than manually edit the registry on several hundred servers I re-enabled the policy, but added Authenticated Users to the ACL to recover. Did anyone at Microsoft ever consider that Server 2008 and Server 2012 are still in use and should be included in testing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af4ac6cb-9755-50f5-b7f1-b7ce2a2a2f17
* Version Independent ID: 88cde4bc-114b-31ed-7eba-f3aefdce7dda
* Content: [Configure SAM-R to enable lateral movement path detection in Advanced Threat Analytics](https://docs.microsoft.com/en-us/advanced-threat-analytics/install-ata-step9-samr)
* Content Source: [ATADocs/install-ata-step9-samr.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/install-ata-step9-samr.md)
* Service: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by Jc692488** [comment]
Is this means is fixed?

**Comment by msmbaldwin** [comment]
Hi, @cmilte-lsuhsc. This product feedback is better suited for our UserVoice channel at https://microsoftsecurity.uservoice.com/forums/905158-advanced-threat-analytics.  Thank you! #product-question
