### ISSUE TITLE
Update needed for 1.9 update 1 

### ISSUE THREAD

**Issue by billypms** [MicrosoftDocs/ATADocs#93]
document update needed to show 1.9 update 1 release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cddc0d9a-9a14-4993-cb28-43b72d8dbe4f
* Version Independent ID: 499064ba-7008-0d40-6cb0-457494a4cb13
* Content: [Advanced Threat Analytics recommended upgrade path](https://docs.microsoft.com/en-us/advanced-threat-analytics/upgrade-path#feedback)
* Content Source: [ATADocs/upgrade-path.md](https://github.com/Microsoft/ATADocs/blob/master/ATADocs/upgrade-path.md)
* Service: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thank you for your feedback. The upgrade path was added.

**Comment by msmbaldwin** [comment]
#doc-bug
