### ISSUE TITLE
Wrong Syntax for sensor install cmd

### ISSUE THREAD

**Issue by HartD92** [MicrosoftDocs/ATADocs#98]
The syntax listed for silently installing the sensor has accesskey listed as an option, not a parameter, which causes the install to fail with "Option '/accesskey' is unknown".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4856b2df-3ad3-526f-b7cf-a24a44340744
* Version Independent ID: fd11c910-7991-cdf1-8ca7-7e7d61ec19bf
* Content: [Install Azure Advanced Threat Protection Silently](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-silent-installation)
* Content Source: [ATPDocs/atp-silent-installation.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-silent-installation.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mlottner** [comment]
Thank you for your feedback. Documentation updated with corrected syntax for fully silent installation.
